### ISSUE TITLE
Synoptic Macros, Update description unknown

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1289] opened 2016-06-23 15:51 UTC
As a user when I am setting OPI macros in a synoptic I do not want the description to read unknown e.g. attenuator. Check all descriptions.

**Comment by IsabellaRey** [comment] 2016-09-15 14:48
Is this a duplicate of ISISComputingGroup/IBEX#769 ?

**Comment by kjwoodsISIS** [comment] 2016-09-15 14:56
Yes, this ticket is, effectively a duplicate of #769 (which also refers to #844).
Because #769 and #844 are so old, I suggest we close them, but check that any work we do under this ticket includes the work proposed by #769 and #844.

**Comment by IsabellaRey** [comment] 2016-12-13 14:19
NOTE: Ticket #1617 can also be done at the same time

**Comment by IsabellaRey** [comment] 2016-12-14 17:24
Note for reviewer:
The work for this ticket covers also #769 and #1617, so can you please move those tickets too.
Work for #844 was not done (see comment in #844)

**Comment by AdrianPotter** [comment] 2016-12-20 11:36
Rework will need picking up by someone else as Isabella is on maternity leave

**Closed** 2017-01-11 16:22 UTC
Labels: 0.5, completed, fixed, rework, task
