### ISSUE TITLE
After restarting the BlockServer, the client cannot edit the current configuration

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1068] opened 2016-02-25 17:04 UTC
If the BlockServer is restarted, say by running start_inst, with the client running, then the client can no longer edit the current configuration (the dialogue does not appear).
Some investigation should be done to find any other times the edit current config/edit config dialogue fails to appear.

Acceptance Test:

1) Start Instrument
2) Start IBEX gui
3) restart the block server, nothing else. Using the `console -m localhost BLOCKSVR` then crt + x
4) Do Menu -> Configurations -> Edit current configuration.
5) Popup should appear.

**Comment by ianbush** [comment] 2016-03-11 15:46
I could not reproduce this again. Could the reviewer just try this out too, and close the ticket if they can not reproduce the problem either.

**Comment by John-Holt-Tessella** [comment] 2016-06-14 13:15
This bug was rediscovered as part of #1165 because I wanted to restart the block server then add a block to the current configuration. I believe this because the update function which works as part of the observables does not update a value if there is an error. When the block server is restarted there is often an error in converting the current config (it is empty and translates as an empty character which then can not be converted to json). Then when the new config is created an observable is pointed at the observable which had the error. It also inherits the error but not the value and so the menu can not be fired because there is no current configuration.

**Comment by AdrianPotter** [comment] 2016-06-15 10:45
Works as expected. Thanks! I'll just do a quick code review before closing...

Note that in step 3, the arg is `-M` not `-m`

**Comment by AdrianPotter** [comment] 2016-06-15 10:54
Just some copyright statement updates. Nothing major.

**Closed** 2016-06-15 15:10 UTC
Labels: 1, completed, fixed, story
