### ISSUE TITLE
GUI: Symbol ₹ not displayed correctly in experiment details

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2246] opened 2017-04-19 10:35 UTC
The symbol ₹, U+20B9, is not displayed correctly in the experiment details panel.

- Go to the experiment details panel
- Add a user with name ₹
- Click `Set`
- The name field of the table will not match the symbol

**Comment by John-Holt-Tessella** [comment] 2017-11-10 09:12
duplicate of #2728

**Closed** 2017-11-10 09:12 UTC
Labels: bug, duplicate
