### ISSUE TITLE
Ibex GUI: Gui crashes when opening Keithley 2400 OPI

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2693] opened 2017-10-16 11:02 UTC
Seen on Polaris (by Ron) and reproduced on two development machines.

The behaviour was:
- Open synoptic containing Keithey 2400
- Click to open the Keithley 2400 OPI
- Entire GUI hangs and crashes out
- The Keithley in question was giving timeout errors (i.e. wasn't talking properly). It may be that a script in the OPI hung when it couldn't get a value.

**Comment by Tom-Willemsen** [comment] 2017-10-16 14:15
This is caused when a PV has a very high value. In Polaris' case they didn't have a sensor plugged into their Keithley, so it reported a current of `10^38`. This value caused the CSS graph widget to choke.

@DominicOram and I had a quick go at putting limits on the PV but didn't have any luck.

We've removed the relevant OPI from Polaris' synoptic.

**Comment by kjwoodsISIS** [comment] 2017-10-18 15:59
What does the Keithley manual say about values it returns when no sensor is attached?  The maximum representable 32-bit IEEE-754 floating-point value is ~ `3.402823 x 10^38`.  I suspect the Keithley is returning something like 0xFFFFFFFF or 0x7FFFFFFF.  If you could check the hex value of the input, you could probably prevent the graph widget from choking.

**Comment by John-Holt-Tessella** [comment] 2017-10-19 08:33
We should add a sensor connected PV. Then if this is on the readback for the GUI should have a alarm and the value of 0.
In addition to this (and potentially harder) we should look to see if this is fixed in E4 and if not fix it in E4.

**Comment by kjwoodsISIS** [comment] 2017-10-26 09:39
The goal of this ticket is to fix the Keithley IOC/OPI.

**Comment by DominicOram** [comment] 2017-10-30 18:33
I assume this was discussed in the planning meeting but why did we choose to fix the IOC rather than look into fixing CSS? It seems like a good opportunity to contribute back into CSS as it is definitely a bug someone else could come across.

**Comment by John-Holt-Tessella** [comment] 2017-10-31 08:38
This is a definite problem in the IOC and because we are not on the latest version of CSS we would have to fix it twice (once now and once when we migrate). I think if there was time left on the ticket investigating the cause in CSS was an option.

**Closed** 2017-11-16 14:33 UTC
Labels: 2, bug, completed, fixed, urgent
