### ISSUE TITLE
SQL databases: remote admin

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1900] opened 2016-12-12 15:39 UTC
At the moment there is no remote admin access to the system. It would be helpful to have that kind of admin access, so that changes can be made remotely.

Note that the password for this should not be made available via any public, or potentially public, method (such as via any aspect of git).

It would be worth considering this within the discussions for #1831, and if agreed on made for roll out with #1765.

**Comment by DominicOram** [comment] 2019-08-22 19:23
Duplicate of https://github.com/ISISComputingGroup/IBEX/issues/4437, keeping the newer one

**Closed by DominicOram** 2019-08-22 19:23 UTC
Labels: duplicate
