### ISSUE TITLE
MERLIN: error message in IOCLOG log

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2956] opened 2018-02-08 21:31 UTC
Since 13:50 today merlin has been writing once a second to its IOCLOG

[Thu Feb  8 13:50:45 2018] Database error, error: 'Message Type "-" not recognised' Will retry.

It doesn't seem to have been doing it prior to then

**Comment by FreddieAkeroyd** [comment] 2018-06-06 17:20
See #3240

**Comment by DominicOram** [comment] 2019-01-25 11:57
Closing as duplicate of #3240

**Closed by DominicOram** 2019-01-25 11:57 UTC
