### ISSUE TITLE
Ioc Test Framework: allow running against real devices

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6788] opened 2021-09-17 15:52 UTC
As a developer I would like to use run IOC test framework against real devices to test behaviour with hardware, this was particularly targeted at testing the new galil driver

## acceptance criteria

a NOSIM mode is added to the framework

**Comment by DominicOram** [comment] 2021-09-30 09:12
Is this a duplicate of https://github.com/ISISComputingGroup/IBEX/issues/3936?

**Comment by FreddieAkeroyd** [comment] 2021-09-30 10:22
Looks similar,  though this seems to talk about adding a manual test options (prompt user to check setpoint on device etc) whereas what I was wanting to do was run the automated tests (or as many as possible) against a real device. I think that may have been what Liam was suggesting in the original description. It would have been convenient if all  devsim tests could also apply to real hardware, but some use the lewis backdoor (which is sort of equivalent to looking at the device front panel)

**Closed** 2022-01-04 10:48 UTC
Labels: 2, no_release_notes
