### ISSUE TITLE
HRPD: In-Situ DSC

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4987] opened 2019-11-28 13:54 UTC
As a user of the scientific program on HRPD I want to be able to conduct in-situ calorimetry within IBEX.

**Acceptance Criteria**
1. There is a component on HRPD (or that could be copied there during the next opportunity) that contains the appropriate blocks for calorimetry
1. There are PVs available relating to the differential values
1. There is an OPI as described in the comments

**Notes**
1. From an experiment controls perspective, this is made of two devices: a Lakeshore 336 and a 3 unit Eurotherm crate
1. The required blocks from the Eurotherm are: heater set point * 4, heater ramp rate * 4, RhFe sensor * 2
1. The required blocks from the Lakeshore 336 are: CernOx sensor * 4
1. The differential pairs are as follows: `CernOx 1, CernOx2`, `CernOx 1, CernOx 3`, `CernOx 2, CernOx 4`, and `CernOx 3, CernOx 4`. These should probably be somewhat variable, e.g. forcing `CernOx 1 - CernOx 2` could be limiting. This might be an opportunity to use some of the recently incorporated INP/OUTP field options
1. The Eurotherm conversion to temperature will be undertaken as a standard Eurotherm in IBEX with RhFe calibration files, as such links to the associated Eurotherm OPI from the OPI for this should be considered
1. The most basic requirement for this is the sub-config with blocks
1. The desired version includes the differentials and an OPI with a plot of a selectable sensor/differential
1. There is a need in the longer term for offline use which would be covered by #4994

**Comment by KathrynBaker** [comment] 2019-11-29 16:02
A suggestion for the OPI - this needs to be verified with the HRPD scientists:

![image](https://user-images.githubusercontent.com/10552381/69880338-9ff76480-12c1-11ea-9235-564081aaaeba.png)

**Comment by KathrynBaker** [comment] 2019-11-29 16:20
Original text of ticket:

This is a placeholder ticket to ensure that this is prioritised

There is a meeting on 29/11 which will be the final design review for the mechanical side of the project, the information currently known has been recorded on https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/In-Situ-DSC

Tickets and corrections will be made after the meeting tomorrow. At present, the aim is to test this at the end of January so this is the time to undertake the work. It is likely to be limited to minor db work and config setups based on the interim review

**Comment by KathrynBaker** [comment] 2019-12-04 14:22
OPI with a graph suggestion:
![image](https://user-images.githubusercontent.com/10552381/70150132-63e94880-16a1-11ea-93ed-62152fe8f046.png)

**Comment by KathrynBaker** [comment] 2020-01-07 13:04
Latest update for the custom parts delivery is 20/3/20 - towards the end of cycle 2019/04

**Comment by JamesKingWork** [comment] 2020-11-30 15:31
Work to add component is being done on the branch HRPD_in_situ_dsc, when complete merge back into NDXHRPD

**Comment by rerpha** [comment] 2020-12-08 17:42
- Does the config need to be merged as part of this ticket or does a separate task need to be created for it for afterwards?
  - there seems to be a lot of rcptt configs that need to be cleaned up as they are failing against the schema
  - the hrpd config seems to also be failing against the schema
- these are probably linked to https://github.com/ISISComputingGroup/IBEX/issues/5069 not being merged yet? 


- I'm not sure from the acceptance criteria what this means or if this solution has covered it: 
  >These should probably be somewhat variable, e.g. forcing CernOx 1 - CernOx 2 could be limiting. This might be an opportunity to use some of the recently incorporated INP/OUTP field options


- We should add somewhere in the documentation that if you change the name of any of those blocks you'll need to update the db file too 

- Is it required that multiple plots are required at the same time? from Kathryn's graph it looks that way? currently you can only plot 1, if so i guess "show" tickboxes for each would be nice
- If it is only required to draw a single plot, we should use local pvs instead of server-side pvs as even if an OPI is not stored on the server changing which PVs are plotted will do it for any OPIs that are in use. This means that it could change what scientists are seeing if a developer comes along and changes which sensor to plot. You can find these in the BOY examples using the loc:// prefix

**Comment by JamesKingWork** [comment] 2020-12-09 10:16
- I think the config merge can be done as part of this ticket, once it's approved
  - Yes we don't want to merge anything from configs or components except the in_situ_dsc component. I have tidied it up a bit now, but we will still need to be aware when merging.
  - Which hrpd config is failing?
- I don't believe the DETMON issues are related to this ticket, unless I'm missing something?
- I am also not sure of that acceptance criteria, I will discuss it with @KathrynBaker 
- I think I should actually not use block names in the custom_records.db and OPI, I will use macros to decide on the lakeshore and eurotherm to use
- I don't believe multiple plots are required at the same time @KathrynBaker may know more though
- I will have a look at changing this

**Comment by rerpha** [comment] 2020-12-09 10:19
I think all the configs were failing, @DominicOram do you remember what they were failing on?

**Comment by DominicOram** [comment] 2020-12-09 11:03
The configs are failing because they contain the `configuresBlockGWAndArchiver` tag, which is not on the schema merged into master.

**Comment by JamesKingWork** [comment] 2020-12-09 11:31
Ok I did miss that, I clearly have a branch checked out that shouldn't be, good spot

**Comment by JamesKingWork** [comment] 2020-12-11 12:47
- Multiple plots are now possible with tick boxes
- It has been confirmed that the calc record of custom_records.db is sufficient, and we can generalise later if need be

**Closed** 2020-12-17 08:20 UTC
Labels: 5, completed, fixed, rework, training
