### ISSUE TITLE
run control not shown on alarmed blocks?

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2200] opened 2017-03-23 17:55 UTC
Had a call from Vicky on IRIS - she had enabled run control on H2Temp which was working correctly, but the red x indicating out of range wasn't appearing. The other global PV block for frequency was showing a tick, the only difference is the H2Temp was in an alarm state with an orange border. Does an alarm state stop a run control tick/cross being drawn?

**Comment by ThomasLohnert** [comment] 2017-04-06 13:22
Tried to reproduce this but it seems the GUI correctly renders alarms and run control together:
![rc_alarm](https://cloud.githubusercontent.com/assets/18398579/24755903/cd32ac7c-1ad3-11e7-9676-1bbde337ed22.png)

What I did come across though, which I did not know until John told me, was that the run control settings as accessed from the menu bar and the run control settings as set in individual block settings are not the same. So when I saved my config it would overwrite the run control set in the dialog from the menu bar (where it was enabled) with whats set in the block settings (where it was disabled), disabling run control for all my blocks and thus removing the icons too. Is there any chance this could have been the source of confusion?

**Comment by ThomasLohnert** [comment] 2017-04-10 09:27
I can't currently reproduce the error, and as far as I can see the alarm and the run control indicators should be working completely independently, so it might be something else. I will be monitoring the PVs mentioned in this ticket throughout the week as they are meant to be ramping up and down, see if the GUI gets into the state described above again.

**Comment by ThomasLohnert** [comment] 2017-04-26 14:01
Was not able to reproduce this bug, I'm fairly certain the various status indicators do not conflict as suggested in the ticket. I'll put in a note to bring it up with Vicky for whoever is demoing to IRIS whilst there, see if we can get some more information on what happened exactly. Meanwhile I'll close this ticket and we'll just wait and see if it happens again.

**Closed by ThomasLohnert** 2017-04-26 14:01 UTC
Labels: 1, in progress
