### ISSUE TITLE
SCAN command: serious problems with reproducibility & validity

### ISSUE THREAD

**Issue by smk78** [ISISComputingGroup/IBEX#4964] opened 2019-11-18 14:39 UTC
This issue refers to commands of the form

```
scan(axis_name, start_position, stop_position, position_step, measurement_duration, monitor#)
```

This last weekend we were measuring small gauge volumes in unconventional engineering samples on Zoom which necessitated us knowing where the edges of the samples were. So we spent a lot of time scanning SampleStack_Y (left-right) or SampleStack_loZ (up-down). In the process we identified some serious problems with how scan currently works.

Consider this scan:

![empty-beam-scanning-test-5x2mm-aperture-monitor5](https://user-images.githubusercontent.com/10938679/69057355-9b9d9280-0a09-11ea-85f9-ab51351ec878.png)

There are two things wrong with it. First, this was a scan without a sample in place (what the SANS Team call an Empty Beam run) at essentially a fixed position (observe that the total motion of the axis is only 0.1mm). So why should the Integrated Intensity vary at all (the variation shown is ~0.5%)? The trendline shown is a quadratic. Some variation in intensity might be expected because the scan command defaults to counting on frames* (as we were using) but that would not explain the observed _systematic_ decrease. That suggests a problem with the integration algorithm. Second, you can see that the uncertainties get steadily smaller. I assume this is because the way scan works is count-Pause-move-Resume, so the longer you scan for more data you have and the better the uncertainties become? In other words, only the uncertainties on the first point are actually representative (although clearly something odd happened with the third point).

*is it possible to scan with uamp-hours? (I couldn't find any documentation)

Next, consider these scans which were trying to locate the flat top of a sample (I've omitted the uncertainties for clarity):

![scanning-top-of-pipe-5x2mm-aperture-monitor5](https://user-images.githubusercontent.com/10938679/69058151-0ac7b680-0a0b-11ea-9037-54a9a8a0590e.png)

Small values of loZ are in air (ie, above the pipe); larger values of loZ are in the pipe. The astounding observation here is the hysteresis observed depending of whether the scan is performed air>pipe or pipe>air. I have no rational explanation for these data!

We did, however, observe that there is some interplay between the measurement_duration and the position_step. This, in turn, would seem to suggest that there are issues with the speed and signalling (for lack of a better description) between the ICP/Python side of Ibex and the motion control/EPICS side of Ibex. Is it possible the scripting gets out of step with the motion, or vice versa?

Lest anyone be thinking this was an issue confined to the loZ axis, here is an example of the same behaviour scanning a different axis:

![scanning-edge-of-pipe-5x2mm-aperture-monitor5](https://user-images.githubusercontent.com/10938679/69060219-e8d03300-0a0e-11ea-85b5-404079059293.png)

These types of operation are becoming more common on SANS2D/ZOOM/LARMOR and so this observed behaviour is problematic. However, scanning is critical to the operation of the reflectometers. So we need to understand what is going here and find some resolutions.

**Comment by smk78** [comment] 2019-11-18 14:51
Here is the associated scan log for the first graph:

[zoom_scan_2019_11_17_12_9_51.txt](https://github.com/ISISComputingGroup/IBEX/files/3859123/zoom_scan_2019_11_17_12_9_51.txt)

Here are the associated scan logs for the second graph:

[zoom_scan_2019_11_17_11_12_3_Top_of_pipe8b.txt](https://github.com/ISISComputingGroup/IBEX/files/3859106/zoom_scan_2019_11_17_11_12_3_Top_of_pipe8b.txt)

[zoom_scan_2019_11_17_11_31_16_top_of_pipe8b.txt](https://github.com/ISISComputingGroup/IBEX/files/3859110/zoom_scan_2019_11_17_11_31_16_top_of_pipe8b.txt)

[zoom_scan_2019_11_17_11_42_14.txt](https://github.com/ISISComputingGroup/IBEX/files/3859116/zoom_scan_2019_11_17_11_42_14.txt)

[zoom_scan_2019_11_17_11_53_47.txt](https://github.com/ISISComputingGroup/IBEX/files/3859118/zoom_scan_2019_11_17_11_53_47.txt)

**Comment by John-Holt-Tessella** [comment] 2019-11-18 17:20
We should probably get together and discuss this, including Adam too. The data probably needs looking at more closely we should pull this out from the archive.

**Comment by rprospero** [comment] 2019-11-22 14:10
I can confirm that the behaviour seen in the included plot has NOT been observed on Larmor.  The data below was taken at the beginning of this cycle and so will be on the same code base as was used for the plot above.

![Larmor_Example](https://user-images.githubusercontent.com/1728853/69431407-9b660580-0d2f-11ea-8a59-b3b81c3a1ae7.png)

[larmor_scan_2019_11_12_10_39_54.txt](https://github.com/ISISComputingGroup/IBEX/files/3879788/larmor_scan_2019_11_12_10_39_54.txt)

As can be seen in the above plot, the error bars grow larger when the count rate grows larger, but then return to the original size when the count rate shrinks again.  The uncertainties are also roughly the square root of the intensities and not related to the number of points measured.

So, the good news is that the code isn't totally broken everywhere.  That bad news is that would be much easier to fix.

Looking at the two different instruments, there's only one change in the code paths.  Larmor has been configured to put the DAE in transmission mode during a scan.  Zoom, meanwhile, does not change the DAE mode.  I doubt that this is the source of the problem, but it's worth investigating.

The best diagnostic would be to run the scan again on Zoom with an additional keyword parameter `save=True`.  This will ensure that a full run number is assigned to the scan and that all of the spectra and metadata is available for inspection.  We'll probably need to look over that to see what is going on.

**Comment by John-Holt-Tessella** [comment] 2019-11-25 09:37
One of us should probably pull some data from the logs. I will see if I can get to this today.

**Comment by John-Holt-Tessella** [comment] 2019-11-25 17:41
Thoughts on code (I was looking at  `zoom_scan_2019_11_17_12_9_51.txt`):

The measurement is sum(spectra 1)/sum(spectra n) the errors are the `np.sqrt(self.total**2 / self.count**2 * (1 / self.total + 1 / self.count))` (total is spectra 1)

So the errors decrease if either count or total increases. Looking at the graph the smaller errors are for smaller values (/total) so it looks like there are more neutrons in spectra n to the right than the left. What is spectra n measuring is that effected by the movement of the components? I think spectra n is spectra 4

**Comment by John-Holt-Tessella** [comment] 2019-11-26 10:32
Set up of motors on the instrument:

- Encoder resolution: 0.001 - this is the closest we can get to any point
- Retry dead band: 0.1 - this is the threshold under which the motion will be retried

The data in the table below shows that the motor always got to within its retry deadband so the motion is correct. However you can see that points 1 and 3 have an error of 0.008 and 0.003 this moves them so the point which is low should be to the left and the gap left is because of the shift of the point to the left before the gap.

There seems to be no issues in the DAE logs that I can see so I think I believe the data we collected.

Date | Set point | Wait for frame | Diff in frames | Current recorded | Diff in current | SampleStack_loZ (mm) | Integrated Intensity | Uncertainty | Diff between SP and RBV
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
17/11/2019 12:10 | 10 | 200 | 200 | 0.227351 | 0.227351 | 10.008 | 5.870456 | 0.053551 | -0.008
17/11/2019 12:11 | 10.005 | 412 | 212 | 0.454661 | 0.22731 | 10.005 | 5.898455 | 0.038057 | 0
17/11/2019 12:11 | 10.01 | 617 | 205 | 0.681011 | 0.22635 | 10.007 | 5.889815 | 0.031028 | 0.003
17/11/2019 12:12 | 10.015 | 823 | 206 | 0.908369 | 0.227358 | 10.016 | 5.884828 | 0.026865 | -0.001
17/11/2019 12:12 | 10.02 | 1029 | 206 | 1.135734 | 0.227365 | 10.021 | 5.88404 | 0.02403 | -0.001
17/11/2019 12:13 | 10.025 | 1241 | 212 | 1.3696 | 0.233866 | 10.025 | 5.877519 | 0.021846 | 0
17/11/2019 12:13 | 10.03 | 1451 | 210 | 1.601435 | 0.231835 | 10.031 | 5.877525 | 0.020208 | -0.001
17/11/2019 12:13 | 10.035 | 1663 | 212 | 1.835238 | 0.233803 | 10.036 | 5.873167 | 0.018863 | -0.001
17/11/2019 12:14 | 10.04 | 1869 | 206 | 2.062512 | 0.227274 | 10.04 | 5.875443 | 0.017804 | 0
17/11/2019 12:15 | 10.045 | 2080 | 211 | 2.295029 | 0.232517 | 10.045 | 5.873435 | 0.01687 | 0
17/11/2019 12:15 | 10.05 | 2292 | 212 | 2.528867 | 0.233838 | 10.051 | 5.872311 | 0.016067 | -0.001
17/11/2019 12:15 | 10.055 | 2498 | 206 | 2.756266 | 0.227399 | 10.056 | 5.875325 | 0.0154 | -0.001
17/11/2019 12:16 | 10.06 | 2704 | 206 | 2.983611 | 0.227345 | 10.06 | 5.874014 | 0.014798 | 0
17/11/2019 12:16 | 10.065 | 2910 | 206 | 3.211073 | 0.227462 | 10.066 | 5.872275 | 0.014259 | -0.001
17/11/2019 12:17 | 10.07 | 3121 | 211 | 3.444 | 0.232927 | 10.071 | 5.871875 | 0.013766 | -0.001
17/11/2019 12:17 | 10.075 | 3327 | 206 | 3.671428 | 0.227428 | 10.075 | 5.872625 | 0.013334 | 0
17/11/2019 12:18 | 10.08 | 3533 | 206 | 3.898807 | 0.227379 | 10.081 | 5.871531 | 0.012937 | -0.001
17/11/2019 12:18 | 10.085 | 3744 | 211 | 4.131685 | 0.232878 | 10.086 | 5.867977 | 0.012554 | -0.001
17/11/2019 12:19 | 10.09 | 3956 | 212 | 4.365633 | 0.233948 | 10.09 | 5.868 | 0.012214 | 0
17/11/2019 12:19 | 10.095 | 4163 | 207 | 4.593874 | 0.228241 | 10.096 | 5.866384 | 0.011901 | -0.001

**Comment by smk78** [comment] 2019-11-26 11:03
> Thoughts on code (I was looking at `zoom_scan_2019_11_17_12_9_51.txt`):
> 
> The measurement is sum(spectra 1)/sum(spectra n) the errors are the `np.sqrt(self.total**2 / self.count**2 * (1 / self.total + 1 / self.count))` (total is spectra 1)
> 
> So the errors decrease if either count or total increases. Looking at the graph the smaller errors are for smaller values (/total) so it looks like there are more neutrons in spectra n to the right than the left. What is spectra n measuring is that effected by the movement of the components? I think spectra n is spectra 4

Spectra n was S5 (M5); we found we couldn't use S4 (M4).

**Comment by John-Holt-Tessella** [comment] 2019-11-29 11:48
Conclusion is that when data was collected IBEX could not set the number of periods to 20 because the DAE had not enough memory. Then when set period was called this was not acted on and all the data remained in the first period.
We need to issue an error in the scripting prompt to alert the user when the period count can not be changed and when the period can not be changed. (see 4992)

**Comment by smk78** [comment] 2019-11-29 11:54
Following a meeting this morning between @John-Holt-Tessella , @rprospero , @smk78 & DAV:

- behaviour observed in first graph is as expected; as the scan progresses more data is accumulated so the moving average settles down and the uncertainties reduce;
- however, scan() uses periods, and so if the DAE is not first configured for transmissions there is a real possibility (depending on the number of steps requested in the scan) that there will be insufficient memory. Due to a bug in the ZOOM scan configuration (and oversight by the Local Contact), scan() was _not_ being used in transmission mode;
- with hindsight it is highly likely that this contributed to the IBEX 'hang' reported in https://github.com/ISISComputingGroup/IBEX/issues/4961 

This analysis is supported by two scans (ZOOM run numbers 11080 and 11081) performed this morning by JD.

**Closed** 2020-01-08 17:29 UTC
Labels: 1, completed, fixed, support
