### ISSUE TITLE
GUI: Beam Status Graph display options

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#3765] opened 2018-11-14 16:29 UTC
As an INES scientist, I would like more control over how the Beam Status Graph is displayed in the client in order to get more detailed information on the beam current at a given time.
This includes for example the ability to rescale both axes, or to show/hide individual traces.

Since this is plotted via CSS it seems like this would be fairly easy to do. Is there a rationale for hiding these options in the first place?

**Comment by KathrynBaker** [comment] 2024-11-13 18:36
Almost a duplicate of #1715 
Adding the rescaling item to that ticket

**Closed by KathrynBaker** 2024-11-13 18:36 UTC
