### ISSUE TITLE
Discussion: PVSets define/fix or remove

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5236] opened 2020-02-20 10:34 UTC
The PVSets functionality does not work. The only IOCs to have this are Galils and these do not show up in the configuration screen. We should decide what this functionality should do and if needed we should finish it if not needed we should remove it.

#### Acceptance Criteria

Either:
- PV Sets functionality is clear
- There are tickets to implement functionality
Or:
- PV Sets functionality is not needed
- There are tickets to remove dead code

**Comment by KathrynBaker** [comment] 2020-02-20 10:35
Duplicate of #5221?

**Comment by Tom-Willemsen** [comment] 2024-11-04 16:24
I agree, duplicate of 5221.

**Closed by Tom-Willemsen** 2024-11-04 16:24 UTC
Labels: duplicate, fixed
