### ISSUE TITLE
Blockserver: Auto-restart IOC do not start on config change

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1788] opened 2016-11-08 14:18 UTC
If a configuration contains an IOC set to be auto-restart (only, i.e. not auto start) then the IOC is not started when the configuration is changed to. This is the opposite of the user manual which claim it will start (https://github.com/ISISComputingGroup/ibex_user_manual/wiki/CreateandManageConfigurations#iocs-tab)

```
... select the Auto-Start or Auto-Restart check-boxes (or select both). By selecting these check-boxes, IBEX will automatically start (or restart) to chosen IOCs each time your configuration is loaded into IBEX.
```

Determin the correct behaviour and then fix either the documentation and/or the blockserver.

**Comment by mattclarke** [comment] 2016-11-28 11:46
I think there is some confusion here due to bad naming.
I thought auto-start meant the blockserver starts the IOC (or restarts if it is already running) on loading the configuration.
auto-restart means the IOC is set to auto-restart, e.g. if the IOC crashes ProcServ will restart it. I don't think it defines anything to do with behaviour on configuration changes.
Of course I could be completely wrong in which case I am happy to merge the ticket

**Comment by FreddieAkeroyd** [comment] 2016-11-28 12:23
What Matt describe is my understanding too - "autorestart" just refers to setting the procServ autorestart flag for if an IOC crashes,  maybe the "auto start" column could just be called "start" and this refers to whether to start an IOC on config load.  When there is a config change, the behaviour should be to restart all IOCs unless you know you don't need to. A new config with the same IOC running may have different macros set, so you would need to that nothing under the hood had changed. There was a ticket to look at optimising this, can't remember where it is. If this optimisation was in place, we may still want to allow the special case of "reload current config" causes a restart of all IOCs as under the optimised scheme it would do nothing and there may be a case for doing this sometimes (I think MUONFE may use this)

**Comment by John-Holt-Tessella** [comment] 2016-11-28 12:32
What does it mean to have an IOC  which is auto-restart yes and then isn't started. Does this mean that once it is started it should restart itself on a crash and the user can only stop it through the IOC start/stop menu? When would we want not to restart an IOC on a crash?

**Comment by FreddieAkeroyd** [comment] 2016-11-28 14:20
If auto restart is enabled, then procserv will start the IOC whenever it is not running ... so autorestart=yes autostart=no is probably not possible with procserv. If we knew an IOC had issues like it would only crash if the equipment was turned off, and then auto-restart would leave it in a continuous restart loop creating errors; or when the ioc starts you need to do something special to the equipment so would rather know that it had crashed rather than it restarting silently, then you may want to leave autorestart off. Not common, but possible.

**Comment by AdrianPotter** [comment] 2016-11-30 13:28
Thanks for the feedback. In which case, I'd aim for this ticket to do a review of existing documentation and behaviour to sure it's in line with what's described above. This ticket stemmed from the manual system tests which suggest quite a different behaviour. To close this ticket I suggest updating:

- [ ] Manual system tests
- [ ] IOC documentation in the developer's manual
- [ ] IOC documentation in the user manual
- [ ] GUI javadoc comments
- [ ] Block server comments

I've closed the original pull request since evidently it would have changed expected behaviour

**Closed** 2017-01-10 17:14 UTC
Labels: 0, bug, completed, question
