### ISSUE TITLE
IMAT: sudden client memory increase leading to machine restart

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4513] opened 2019-07-09 21:33 UTC
At around 1800 on Tuesday the 9th July the ibex client memory started to increase at a rapid rate, this led to the NDXIMAT machine becoming unresponsive and dropping off the network around 20:00. When computing support logged into NDHIMAT it seemed that NDXIMAT VM had restarted itself, a brief look at NDXIMAT system logs hasn't shown anything but nagios shows the client memory increase from 18:00. 

This is the second time this cycle that NDXIMAT has seen this problem.

**Comment by John-Holt-Tessella** [comment] 2019-07-10 07:59
This is weird, this hasn't happened except on IMAT (that I know of), it is at a random time. All the other instruments are fine. We should check:

1. Hardware
1. Installed software (are there any drivers on here which are weird)
1. PC Changes
1. genie_python commands

can anyone think of anything else.

**Comment by Tom-Willemsen** [comment] 2019-07-10 08:16
Does this correlate with the footprints message at 17:49 yesterday? If so it may be due to the nicos disconnection/reconnection code.

**Comment by Tom-Willemsen** [comment] 2019-07-10 09:28
I will do some investigation to try and reproduce the problem.

**Comment by Tom-Willemsen** [comment] 2019-07-10 10:17
I have confirmed that if NICOS is disconnected, the client leaks both handles and (therefore?) memory.

To reproduce this relatively quickly on a dev machine:
- In `/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/Nicos.java` change `CONNECT_POLL_TIME` to 1 (ms)
- In `/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/comms/ZMQWrapper.java` change `RECEIVE_TIMEOUT` to 1 (ms)
- Open nicos scripting perspective
- Kill nicos by doing `console -M localhost NICOS`, turn off autorestart then kill the process.
- Look in task manager at "handles" and "private working set (bytes)" to see the leak.

I think we are not closing connections correctly - ZMQ has a `disconnect` API which I think we might not be calling in some cases, potentially we may also need to send a `quit` command to NICOS (as per https://github.com/ISISComputingGroup/IBEX/issues/4511 )

This is not a java leak, it is native, I suspect in the ZMQ library somewhere. See java usage and task manager:

![image](https://user-images.githubusercontent.com/24375813/60961506-425b7f00-a304-11e9-9831-e16966d16a61.png)


I will add this to the list of items we need to fix in https://github.com/ISISComputingGroup/IBEX/issues/4511

**Comment by Tom-Willemsen** [comment] 2019-07-10 10:43
I will entirely disable the GUI script generator on IMAT in the meantime.

To do this:
- Stop client on IMAT
- Copy jar in `\\isis\inst$\Kits$\CompGroup\ICP\Releases\client_5.4.0_disable_script_server_perspective` into `<imat client dir>/plugins`, overwriting the existing file
- Restart client on IMAT and check nicos scripting view does not appear in list of perspectives

**Comment by DominicOram** [comment] 2019-07-11 11:02
Confirmed that #4511 will fix issue and that the new hotfix has been made.

**Closed** 2019-07-18 07:33 UTC
Labels: 0.5, completed, fixed, support
