### ISSUE TITLE
IMAT: stress rig

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4724] opened 2019-09-11 13:45 UTC
IMAT are going to be using the stress rig from ENGIN-X sometime this year. The actual stress rig hardware is the one from ENGINX so the existing IOC will work, but there may also be a Beckhoff PLC to control the hydraulics. @DominicOram and @Simon-Cooper may be able to give more details on the Beckhoff side.

**Comment by Simon-Cooper** [comment] 2019-09-11 15:24
Hi @Tom-Willemsen , can you confirm that they are actually looking to use the rig **this** year? 
There are a lot of elements to this that still remain incomplete:
- PLC panels still to be installed in blockhouse and mezzanine (OMRON controllers now)
- Cabling installation between the manifold and control drop locations
- PLC software and HMI development
- Current stress rig frame incompatible with IMAT SPS
- User access control and fencing modifications to the hydraulics area on mezzanine
- User induction programme for hydraulic safety and safety related equipment (spill kits/handwashing stations)
- Hydraulic pump has still not been commissioned fully and operations team aren't willing to support until this is done

Unfortunately I've not had the resources to push this as much I would like to this year.

**Comment by Tom-Willemsen** [comment] 2019-09-11 16:05
We had a catch-up meeting with the scientists earlier, they told us that they were planning to use it sometime between now and december of this year. From what I've gathered, it would be comissioning type experiments as opposed to user experiments.

It is probably worth clarifying the plans directly with the scientists (Joe and Winfried), from our perspective it isn't a huge amount of work but it sounds like there would be significant effort required from other groups.

**Comment by DominicOram** [comment] 2021-01-28 11:25
Closing as duplicate of https://github.com/ISISComputingGroup/IBEX/issues/6102

**Closed by DominicOram** 2021-01-28 11:25 UTC
