### ISSUE TITLE
January training: Introduction to Python, introduction to IBEX, genie_python and IBEX

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2855] opened 2018-01-09 11:25 UTC
As a user, I would like another Introduction to IBEX and genie_python with IBEX training course so I can learn how to use the system.

The training courses are scheduled for the 23rd/24th January

## Acceptance criteria
- [x] Advertise training
- [x] Book venue
- [x] Assign trainers
    - @Tom-Willemsen  and @ThomasLohnert have volunteered to give the training
- [x] Review course materials
- [x] Send delegate list to CDF
- [x] Send joining instructions to delegates
- [x] Book tea, coffee and lunch as necessary
- [x] Set up machines
- [x] Deliver training
- [x] Apply retrospective changes to process/wiki/slides

Additional instructions for setting up training can be found here:

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Training-Instrument-Scientists-in-IBEX

**Comment by Tom-Willemsen** [comment] 2018-01-24 17:10
Training delivered. Final turnouts were 6 for Introduction to python, 9 for IBEX and 8 for genie_python. Feedback for the courses was mostly 3's out of 3 for all the courses. However it might be appropriate to send out an email asking for more feedback (probably anonymously).

@ThomasLohnert and I will write up some retrospective notes and apply the changes to the slides in the next few days.

**Comment by ThomasLohnert** [comment] 2018-01-26 11:24
Implemented the following changes to materials:

## [Training Instrument Scientists Wiki entry:](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Training-Instrument-Scientists-in-IBEX)
* Edited note on reference cards to hand out to include additional reference cards.
* Added a note for creating desktop shortcuts for IBEX server and client
* Moved note about changing the resolution of CDF machines to the section for changes to individual workstations

## [IBEX training slides](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Forms/AllItems.aspx?RootFolder=%2Fisis%2Fcomputing%2FICPdiscussions%2FTraining&FolderCTID=0x01200027AD8F05966A2748B3B04C98BB5B442B&View=%7BF2C33C51-70E6-4343-B937-2C59A2568306%7D)
* Slide 3: Added note about slide availability
* Slide 4: Removed Matt Clarke from IBEX Team
* Slide 20: Added speaker note about pointing out "Current Config" label
* Slide 27: Added speaker note about non-instrument machine prefixes
* Slide 28: Corrected PV prefix in exercise instructions from IN to TE
* Slides 45-47 (was 42-44): Moved slides about adding PVs to synoptic components to the end of the presentation (after OPI target has been configured) so attendees can see them work in exercises
* Slide 51: Added GUI reference card to hand out
* Slide 52: Added file location memo sheet to hand out

## [Genie_python training slides](https://github.com/ISISComputingGroup/ibex_user_manual/wiki/genie_python_and_ibex/genie_python_and_ibex.pptx)
* All genie_python commands now consistently marked as such throughout presentation (e.g. `waitfor_move` -> `g.waitfor_move()`). Some attendees successfully entered `begin()` as previously written on the slides, which set false expectations about other genie_python commands.
* Italicized paths and file names throughout presentation to help set them apart in text
* Slide 3: Added note about slide availability
* Slide 10: After discussion with Freddie: removed references to legacy `update` and `store` commands and expanded description of `updatestore` command
* Slide 11: Changed `do_experimental_stuff()` to `print("Doing experimental stuff")` in example code as dummy method caused confusion
* Slide 19: Changed markup of line "from genie_python import genie as g" to python code as used throughout presentation
* Slide 34: Changed speaker notes in conversion exercise to address (deliberate) possible optimizations in code
* Worked example for common commands (slide 17, was 13) is very long to be done entirely on command line. Re-organised the slides so they now follow the sequence:
    * Common commands
    * User scripts introduction 
    * Worked Example: Common commands/user scripts
    * Exercise: Common commands/user scripts
    * Instrument scripts introduction
    * Exercise: Setting up instrument script
    * Exercise: Functions
    * Rest as it was
* Specific changes to scripting slides content:
    * Split content for user and instrument scripts into separate slides as they are now introduced one at a time.
    * Added written instructions on worked example slide (slide 17)
    * Added note on worked example slide to address error caused by not using function definitions in script (slide 17)
    * Changed exercise on Instrument scripts: instead of creating empty files, participants are now asked to create a script with a single genie python command and try loading it with and without the import (slide 19)
    * Added a recap slide for the differences between instrument and user scripts before final section on importing modules. (slide 24)

## Opened Issues:
* https://github.com/ISISComputingGroup/IBEX/issues/2907
* https://github.com/ISISComputingGroup/IBEX/issues/2908
* https://github.com/ISISComputingGroup/IBEX/issues/2909

## Changes to code:
* [Improved error message on load_script](https://github.com/ISISComputingGroup/genie_python/pull/109)

**Closed** 2018-02-15 08:27 UTC
Labels: 2, fixed
