### ISSUE TITLE
IOC Log: do not forward incorrect format putlog messages

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2610] opened 2017-09-17 18:26 UTC
The is related to #2609 - if a putlog message in the incorrect format arrives, an exception is thrown as shown in #2609 but the message is still forwarded on and stored in the database. Though incorrect formatted messages shouldn't arrive, the current issue on ENGINX would be averted if they were not forwarded.

Acceptance criteria:

incorrectly formatted putlog messages are discarded by the iocLogServer

**Comment by DominicOram** [comment] 2019-01-25 14:23
I couldn't reproduce the error of incorrectly formatted messages being put into the database whilst testing #3240. I tried:
* Sending a partial xml that has been completed next message
* Sending multiple xml messages in a single buffer
* Sending malformed xml

These cases produced some errors, which I've addressed in the above ticket but did not actually write anything to the DB. As such I'm closing this. If it happens again additional info on the exact message will be needed to reproduce.

**Closed by DominicOram** 2019-01-25 14:23 UTC
