### ISSUE TITLE
Muon instruments: Discuss simplified commands

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3952] opened 2019-01-24 13:12 UTC
As an instrument scientist on the muon instruments, I do not want to type `g.begin()` at a command line as I feel this is too complicated to explain over the phone to a non-native speaker.

The muon group have suggested that they would like simplified commands such as `begin` and `end` rather than `g.begin()` and `g.end()`. However, these commands are incompatible with python syntax, so we may need to find a different solution.

This ticket needs to have a meeting to discuss & clarify the use cases and possible solutions. It is not necessarily clear why the users need to type in `begin`/`end` commands rather than using the buttons in the DAE screen, for example.

### Acceptance

-- Tickets created that summarise the outcomes

**Comment by kjwoodsISIS** [comment] 2019-10-31 11:32
@FreddieAkeroyd - did you ever speak to the muons group about simplified `begin` and `end` commands?

**Comment by DominicOram** [comment] 2020-01-06 18:40
We didn't discuss this in planning today, is it still required for EMU?

**Comment by kjwoodsISIS** [comment] 2020-01-07 08:17
Yes, this is still required.  Later today I am meeting the Muons group to discuss further.

**Comment by kjwoodsISIS** [comment] 2020-01-07 15:35
Here are the notes I took during our meeting (10:30-11:00, 07-Jan-2019):

#### Root problem
We believe the root problem is that it can be difficult to explain the syntax of a command to users over the phone, especially when English is not the first language of the user.  When the instrument scientist can log-in via VNC, the problem is much reduced, because the instrument scientists can take over or demonstrate to the user.  The new genie_python syntax might seem a bit strange to experienced users (at least until they get used to it), especially having to explain which type of brackets to use when entering commands.  We agreed that the two key objectives are:
   1. to make it as easy as possible for the user to execute the simple, most frequently used commands and 
   1. to make it as easy as possible for the instrument scientist to provide remote support if/when the user needs help.

#### Ideas We Came Up With
We explored a number of ideas aimed at making it easier for users to help themselves and to make it easier for instrument scientists to provide remote support.  
   1. We could import all the genie_python commands into a single global namespace.  This would eliminate the need to prefix commands with a `g.`, but it would create the risk of having multiple commands with the same name (which could be a problem if importing 3rd party python packages).  It would also make it impossible to provide a namespace that supported a reduced command set (see 5. below).  We believe there are better solutions than a single global namespace.
   1. Some users will not be used to typing brackets.  Others (perhaps those already used to Python and similar languages) may not find it a problem.  It may be that users will adapt very quickly – we don’t know until IBEX goes live on muon instruments.  See also 5.a) and 5.b) below.
   1. It might be possible to add a small number of buttons to the script console (e.g. to the toolbar).  These would have fixed functionality – for example, they might inject a fixed command at the console prompt which the user can execute by pressing Enter (or the command could just execute immediately).  We would need to agree on precisely what these commands are.
      1. One variant of this idea is to create a Help button that provided textual help on a few key commands.
      1. The help button could remind users to “check the brackets!”
   1. The Muons group already provides users with a reduced command set, which are documented in the instrument manuals in the cabins.  We could create a laminated card (to be pinned up in the cabin) listing the same commands (in genie_python syntax).  
      1. The reduced set of commands is listed in section 7.1.3 of the the [EMU Manual](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/EMU/emu_manual_20190401.pdf).
      1. The most commonly used reduced set commands are: `begin`, `end`, `settemp`, `setmag`, `slits`, `tf20`, `lf0`, `f0`.  the others are used much less frequently.
      1. The laminated card could also remind users to “check the brackets!”
   1. The script console in IBEX supports automated command completion (i.e. you start typing the command and the system displays commands that match what you have typed, along with a full list of command arguments).  This saves users from having to remember the full syntax of every command.  We could create a new namespace containing just the reduced set of genie_python commands recommended by the Muons group – for example, `m.command(…)` or `r.command(…)` ( `m.` for muons or `r.` for reduced).  Command completion inserts the selected command at the console prompt.  Command completion would also work with the reduced command set.
      1. There is a risk that, if users didn’t want all the command arguments, they might accidentally delete the brackets (especially the closing bracket).  This could be mitigated by reminders to users to “check the brackets!” (see 3.b) and 4.c) above).
      1. Of course, many users will be familiar with languages that use brackets (such as C, C++, FORTRAN, MATLAB, R.  Indeed, they might use Python in other contexts – e.g. Mantid analysis), so remembering & checking the brackets might not be such a big leap for many users.
   1. Python supports the concept of custom help for individual commands.  If desired, the IBEX team could create help stubs for these commands, which the Muons group could expand with custom text explaining how to use each command (for the reduced command set, not the whole of genie_python).
   1. We could also create a single help page, which explained the basics of the new command syntax.  It would also be possible to support versions of this help page translated into different languages (e.g. Japanese for RIKEN users) – although we’d need a native speaker to actually do the translation.
   1. To help users use the new IBEX GUI, we could identify the key features and provide a laminated card which translated these into selected user languages.
   1. IBEX, of course, has a user guide (on the web).  It is possible to create sections customised specifically for the Muon group.
   1. The combination of on-line help and printed documentation (e.g. instrument manual & laminated cards) should make it easier for instrument scientists to provide remote support (especially if some of the on-line help could be provided in a user’s native language).

**Comment by kjwoodsISIS** [comment] 2020-01-07 15:43
We don't have to implement all of these ideas and certainly not all of them before EMU goes live with IBEX.  It is likely that we will implement some of them initially and gradually add others (and perhaps discard some of the initial ideas) in the light of experience.

Initially, the promising and practical ideas appear to be 3., 4., 5. (and 7. for the RIKEN instruments (ARGUS, CHRONUS)).

**Comment by davidkeymer** [comment] 2020-01-13 10:46
The following additional tickets resulting from this discussion have been created:
[Point 5 above - "Namespace for reduced set of commands"](https://github.com/ISISComputingGroup/IBEX/issues/5066)
[Point 6 above - "Muon-specific help() command"](https://github.com/ISISComputingGroup/IBEX/issues/5067)

Muon group specific changes that didn't need a discussion are covered in these tickets:
["waitfor_events"](https://github.com/ISISComputingGroup/IBEX/issues/4914)
["Muon-specific BEGIN and END commands"](https://github.com/ISISComputingGroup/IBEX/issues/4913)

**Closed** 2020-02-06 08:14 UTC
Labels: 1, completed, fixed
