### ISSUE TITLE
SUPPORT: ZOOM EXTGW crashing

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5189] opened 2020-02-10 11:01 UTC
The external gateway on ZOOM is crashing at random, but I am unsure why. This will limit client access  from external machines.

Log shows:

```
Feb 10 11:00:05 PV Gateway Aborting (SIGSEGV)
```

### Acceptance Criteria

- The gateway no longer crashes

**Comment by John-Holt-Tessella** [comment] 2020-02-10 11:02
Will check the firewall I guess and run it manually on the system after getting instrument scientist permission

**Comment by DominicOram** [comment] 2020-04-08 17:10
Duplicate of https://github.com/ISISComputingGroup/IBEX/issues/5204, where more discussion has been had so closing this one.

**Closed by DominicOram** 2020-04-08 17:10 UTC
Labels: support
