### ISSUE TITLE
GUI: ability to reload current config

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1497] opened 2016-08-18 09:16 UTC
Following on from ISISComputingGroup/IBEX#1209, it may be useful to have a way to reload the current config from the GUI

**Comment by DominicOram** [comment] 2017-11-14 15:54
Duplicate of https://github.com/ISISComputingGroup/IBEX/issues/2782

**Closed by DominicOram** 2017-11-14 15:54 UTC
