### ISSUE TITLE
POLREF: More Testing

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5652] opened 2020-08-24 16:32 UTC
More testing on Polref

#### Unit Tests
- [X] Check in and out positions on monitor 3 
- [X] Check current sheet as dual position style from SECI (make notes on wiki)
    - see https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrating-Galil-motors-from-SECI-to-IBEX#dual-position-stage-axis
- [X] Test bench movement with angle limit
- [X] Get correct spectrum integration limits and numbers for scan
- The following are defined in the config:
    - [X] current sheet position and out of beam position, rough number
    - [X] Analyser Flipper position on bench, rough number
    - [X] Slit 3 position on bench, rough number
    - [X] Analyser mirror 1 position on bench, rough number
    - [X] Analyser mirror 2 position on bench, rough number
    - [X] S4 position on bench, rough number
    - [X] point detector on bench and out of beam position, rough number
    - [X] bender offspec analyser on bench and out of beam position, rough number
    - [X] multi detector position on bench, rough number
- [X]  Offsets for on bench components look like 0 is out of beam set so this is not true
    - Set MOT:MTR0606 offset to 160 so 0 is in beam and -160 is out of beam
    - Set MOT:MTR0702 offset to -242.5
    - Set MOT:MTR0706 offset to -242.5
- Not done left with scientist: S2 engineering correction is approved
- [X] Danfysik - test polarity had troubles elsewhere
    - doesn't work in ticket #5296 
-  [X] Test Little Blue Cryostat

#### System tests
-  [X] Run flipper calibration
-  [X] Test flipping ratio
-  [X] Run PA measurement
-  [X] Test vertical config (minimal testing but ran out of time)

**Comment by ThomasLohnert** [comment] 2020-10-06 11:16
Snag List:
#### Motors:
- [ ] Inappropriate retry deadband set from migration
- [ ] Set offset on flipper position (motor is zeroed on reflected beam in SECI)
- [ ] S2 North blade had issues reaching setpoint (e.g. oscillating around 0.5). Possibly encoder issue 

#### Reflectometry Server:
- [ ] Parameter RBVs lagging behind motor RBVs (fixed, see #5742, #5744)
- [ ] Some components need to have their axes parked in a specific sequence to avoid clashes
- [ ] Slit centre slipped after driving blades to their limits with a large gap. Reapply VC / HC?
- [ ] Sometimes big delays seen on POLREF between clicking move and motors starting to move
- [ ] Scientists want to be able to apply set of default parameter values (on move / separate button?)

#### Devices:
- [ ] Mezei Flipper 
    - Need to adjust min/max amplitude. currently at -3/3, Flipper on POLREF usually operating at 3.5. Currently the only V1 flipper in use at ISIS, maybe we can just update the hardcoded values in `.db`
    - Increase precision on Amp, Constant, Compensation and DT values
- [ ] Danfysik setting polarity (#5296)
- [ ] Overview with all relevant SP/RBVs on Mercury OPI would be useful

#### UI:
- [ ] Spectra on detector diagnostics limited to show 256 at a time - scientists would like more (ideally, all of them but this is limited by data rate in the ICP)
- [ ] Flickering moving state caused by fluctuation position reported by encoder
- [ ] Theta should be highlighted as primary parameter on front panel
- [ ] Reflectometry OPI can be quite slow (May be solved by POLREF PC upgrade)
- [ ] PV Connection Layer on OPI seen to have crashed overnight on a couple of occasions (only affected UI, not scripting / reflectometry server). Resolved by IBEX client restart

**Comment by John-Holt-Tessella** [comment] 2020-10-09 11:11
All non important tickets referenced by #5802

**Comment by DominicOram** [comment] 2020-10-12 11:34
@John-Holt-Tessella and @ThomasLohnert, would you like this reviewed by someone not focused on reflectometry?

**Comment by John-Holt-Tessella** [comment] 2020-10-12 16:31
Probably not, @ThomasLohnert has already looked at this mostly and so it should be easy for him to get it across the line.

**Closed** 2020-10-15 07:39 UTC
Labels: 20, completed, fixed
