### ISSUE TITLE
EMU: Web Dashboard displays Phantom Alarms

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5973] opened 2020-12-11 12:23 UTC
It appears that the EMU web dashboard displays alarms that are not present in the IBEX Alarm view.  The "phantom" alarms seem to relate to beam parameters that are of interest to neutron instruments but of no interest to muon instruments. It would be helpful to eliminate these "phantom" alarms, because they are confusing to users.

#### Acceptance Criteria
1. Muon web dashboards only display alarms relevant to muon instruments

#### Notes
1. None.

**Comment by DominicOram** [comment] 2020-12-16 21:47
Duplicate of https://github.com/ISISComputingGroup/IBEX/issues/5765 but that ticket provides slightly more detail so closing this one

**Closed by DominicOram** 2020-12-16 21:47 UTC
Labels: bug, proposal
