### ISSUE TITLE
LINMOT: Driver taking 3-4 secs per serial write

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2998] opened 2018-02-26 15:03 UTC
As an instrument scientist on Engin-X, I want the motor to start moving as soon as possible after I send the move command.

Originally sent via footprints:

> Entered on 26/02/2018 at 11:42:56 GMT (GMT+0000) by ISIS Computing Support:
> All motion control that is on the Linmot is responding extremely slowly. These 
> include all three jaws on ENGINX. After the command is issued, it takes a 
> minute or so for the motors to move(used to be immediate). IBEX shows the 
> motors are moving status during this time. We have restarted the controllers. 
> 
> Reported by: Saurabh Kabra (mailto:saurabh.kabra@stfc.ac.uk)

The linmot driver is currently spending 3-4 seconds doing a "flush" before each write

The following is a log from Engin-X with `asynSetTraceMask("serial03", -1, 0x11)` enabled. Notice that the driver spends several seconds doing a serial flush before it succeeds in doing a write. The following is the log for a single "move" command.

```
[2018-02-26 14:36:55] epics> 2018/02/26 14:36:58.687 serial03 asynManager::queueLockPort locking port

[2018-02-26 14:36:58] 2018/02/26 14:36:58.687 serial03 asynManager::queueLockPort taking mutex 00000000026E7FA0

[2018-02-26 14:36:58] 2018/02/26 14:36:58.687 serial03 asynManager::queueLockPort queueing request

[2018-02-26 14:36:58] 2018/02/26 14:36:58.687 serial03 addr -1 queueRequest priority 0 not lockHolder

[2018-02-26 14:36:58] 2018/02/26 14:36:58.687 serial03 schedule queueRequest timeout

[2018-02-26 14:36:58] 2018/02/26 14:36:58.687 serial03 asynManager::queueLockPort waiting for event

[2018-02-26 14:36:58] 2018/02/26 14:36:58.687 asynManager::portThread port=serial03 callback

[2018-02-26 14:36:58] 2018/02/26 14:36:58.688 serial03 asynManager::queueLockPortCallback signaling begin event

[2018-02-26 14:36:58] 2018/02/26 14:36:58.688 serial03 asynManager::queueLockPortCallback waiting for mutex from queueUnlockPort

[2018-02-26 14:36:58] 2018/02/26 14:36:58.688 serial03 asynManager::queueLockPort got event from callback

[2018-02-26 14:36:58] 2018/02/26 14:36:58.688 serial03 flush

[2018-02-26 14:36:58] 2018/02/26 14:36:58.688 \\.\COM6 flush

[2018-02-26 14:37:02] 2018/02/26 14:37:02.305 \\.\COM6 write.

[2018-02-26 14:37:02] 2018/02/26 14:37:02.305 wrote 9 to \\.\COM6, return asynSuccess

[2018-02-26 14:37:02] 2018/02/26 14:37:02.306 \\.\COM6 read.

[2018-02-26 14:37:02] 2018/02/26 14:37:02.348 \\.\COM6 read 2, return 0

[2018-02-26 14:37:02] 2018/02/26 14:37:02.348 serial03 queueUnlockPort

[2018-02-26 14:37:02] 2018/02/26 14:37:02.348 serial03 asynManager::queueUnlockPort waiting for event

[2018-02-26 14:37:02] 2018/02/26 14:37:02.349 serial03 queueUnlockPort unlock mutex 00000000026E7FA0 complete.

[2018-02-26 14:37:02] 2018/02/26 14:37:02.349 serial03 asynManager::queueLockPort locking port

[2018-02-26 14:37:02] 2018/02/26 14:37:02.349 serial03 asynManager::queueLockPort taking mutex 00000000026E7FA0

[2018-02-26 14:37:02] 2018/02/26 14:37:02.349 serial03 asynManager::queueLockPort queueing request

[2018-02-26 14:37:02] 2018/02/26 14:37:02.349 serial03 addr -1 queueRequest priority 0 not lockHolder

[2018-02-26 14:37:02] 2018/02/26 14:37:02.349 serial03 schedule queueRequest timeout

[2018-02-26 14:37:02] 2018/02/26 14:37:02.349 serial03 asynManager::queueLockPort waiting for event

[2018-02-26 14:37:02] 2018/02/26 14:37:02.349 asynManager::portThread port=serial03 callback

[2018-02-26 14:37:02] 2018/02/26 14:37:02.349 serial03 asynManager::queueLockPortCallback signaling begin event

[2018-02-26 14:37:02] 2018/02/26 14:37:02.349 serial03 asynManager::queueLockPortCallback waiting for mutex from queueUnlockPort

[2018-02-26 14:37:02] 2018/02/26 14:37:02.350 serial03 asynManager::queueLockPort got event from callback

[2018-02-26 14:37:02] 2018/02/26 14:37:02.350 serial03 flush

[2018-02-26 14:37:02] 2018/02/26 14:37:02.350 \\.\COM6 flush

[2018-02-26 14:37:05] 2018/02/26 14:37:05.967 \\.\COM6 write.

[2018-02-26 14:37:05] 2018/02/26 14:37:05.967 wrote 8 to \\.\COM6, return asynSuccess

[2018-02-26 14:37:05] 2018/02/26 14:37:05.967 \\.\COM6 read.

[2018-02-26 14:37:05] 2018/02/26 14:37:06.010 \\.\COM6 read 2, return 0

[2018-02-26 14:37:05] 2018/02/26 14:37:06.010 serial03 queueUnlockPort

[2018-02-26 14:37:05] 2018/02/26 14:37:06.010 serial03 asynManager::queueUnlockPort waiting for event

[2018-02-26 14:37:05] 2018/02/26 14:37:06.010 serial03 queueUnlockPort unlock mutex 00000000026E7FA0 complete.

[2018-02-26 14:37:05] 2018/02/26 14:37:06.010 serial03 asynManager::queueLockPort locking port

[2018-02-26 14:37:05] 2018/02/26 14:37:06.011 serial03 asynManager::queueLockPort taking mutex 00000000026E7FA0

[2018-02-26 14:37:05] 2018/02/26 14:37:06.011 serial03 asynManager::queueLockPort queueing request

[2018-02-26 14:37:05] 2018/02/26 14:37:06.011 serial03 addr -1 queueRequest priority 0 not lockHolder

[2018-02-26 14:37:05] 2018/02/26 14:37:06.011 serial03 schedule queueRequest timeout

[2018-02-26 14:37:05] 2018/02/26 14:37:06.011 serial03 asynManager::queueLockPort waiting for event

[2018-02-26 14:37:05] 2018/02/26 14:37:06.011 asynManager::portThread port=serial03 callback

[2018-02-26 14:37:05] 2018/02/26 14:37:06.011 serial03 asynManager::queueLockPortCallback signaling begin event

[2018-02-26 14:37:05] 2018/02/26 14:37:06.011 serial03 asynManager::queueLockPortCallback waiting for mutex from queueUnlockPort

[2018-02-26 14:37:05] 2018/02/26 14:37:06.011 serial03 asynManager::queueLockPort got event from callback

[2018-02-26 14:37:05] 2018/02/26 14:37:06.012 serial03 flush

[2018-02-26 14:37:05] 2018/02/26 14:37:06.012 \\.\COM6 flush

[2018-02-26 14:37:09] 2018/02/26 14:37:09.628 \\.\COM6 write.

[2018-02-26 14:37:09] 2018/02/26 14:37:09.628 wrote 10 to \\.\COM6, return asynSuccess

[2018-02-26 14:37:09] 2018/02/26 14:37:09.628 \\.\COM6 read.

[2018-02-26 14:37:09] 2018/02/26 14:37:09.671 \\.\COM6 read 2, return 0

[2018-02-26 14:37:09] 2018/02/26 14:37:09.671 serial03 queueUnlockPort

[2018-02-26 14:37:09] 2018/02/26 14:37:09.671 serial03 asynManager::queueUnlockPort waiting for event

[2018-02-26 14:37:09] 2018/02/26 14:37:09.671 serial03 queueUnlockPort unlock mutex 00000000026E7FA0 complete.

[2018-02-26 14:37:09] 2018/02/26 14:37:09.671 serial03 asynManager::queueLockPort locking port

[2018-02-26 14:37:09] 2018/02/26 14:37:09.671 serial03 asynManager::queueLockPort taking mutex 00000000026E7FA0

[2018-02-26 14:37:09] 2018/02/26 14:37:09.671 serial03 asynManager::queueLockPort queueing request

[2018-02-26 14:37:09] 2018/02/26 14:37:09.671 serial03 addr -1 queueRequest priority 0 not lockHolder

[2018-02-26 14:37:09] 2018/02/26 14:37:09.671 serial03 schedule queueRequest timeout

[2018-02-26 14:37:09] 2018/02/26 14:37:09.672 serial03 asynManager::queueLockPort waiting for event

[2018-02-26 14:37:09] 2018/02/26 14:37:09.672 asynManager::portThread port=serial03 callback

[2018-02-26 14:37:09] 2018/02/26 14:37:09.672 serial03 asynManager::queueLockPortCallback signaling begin event

[2018-02-26 14:37:09] 2018/02/26 14:37:09.672 serial03 asynManager::queueLockPortCallback waiting for mutex from queueUnlockPort

[2018-02-26 14:37:09] 2018/02/26 14:37:09.672 serial03 asynManager::queueLockPort got event from callback

[2018-02-26 14:37:09] 2018/02/26 14:37:09.672 serial03 flush

[2018-02-26 14:37:09] 2018/02/26 14:37:09.673 \\.\COM6 flush

[2018-02-26 14:37:13] 2018/02/26 14:37:13.293 \\.\COM6 write.

[2018-02-26 14:37:13] 2018/02/26 14:37:13.293 wrote 6 to \\.\COM6, return asynSuccess

[2018-02-26 14:37:13] 2018/02/26 14:37:13.293 \\.\COM6 read.

[2018-02-26 14:37:13] 2018/02/26 14:37:13.335 \\.\COM6 read 5, return 0

[2018-02-26 14:37:13] 2018/02/26 14:37:13.336 serial03 queueUnlockPort

[2018-02-26 14:37:13] 2018/02/26 14:37:13.336 serial03 asynManager::queueUnlockPort waiting for event

[2018-02-26 14:37:13] 2018/02/26 14:37:13.336 serial03 queueUnlockPort unlock mutex 00000000026E7FA0 complete.

[2018-02-26 14:37:13] 2018/02/26 14:37:13.336 serial03 asynManager::queueLockPort locking port

[2018-02-26 14:37:13] 2018/02/26 14:37:13.336 serial03 asynManager::queueLockPort taking mutex 00000000026E7FA0

[2018-02-26 14:37:13] 2018/02/26 14:37:13.336 serial03 asynManager::queueLockPort queueing request

[2018-02-26 14:37:13] 2018/02/26 14:37:13.336 serial03 addr -1 queueRequest priority 0 not lockHolder

[2018-02-26 14:37:13] 2018/02/26 14:37:13.336 serial03 schedule queueRequest timeout

[2018-02-26 14:37:13] 2018/02/26 14:37:13.336 serial03 asynManager::queueLockPort waiting for event

[2018-02-26 14:37:13] 2018/02/26 14:37:13.337 asynManager::portThread port=serial03 callback

[2018-02-26 14:37:13] 2018/02/26 14:37:13.337 serial03 asynManager::queueLockPortCallback signaling begin event

[2018-02-26 14:37:13] 2018/02/26 14:37:13.337 serial03 asynManager::queueLockPortCallback waiting for mutex from queueUnlockPort

[2018-02-26 14:37:13] 2018/02/26 14:37:13.337 serial03 asynManager::queueLockPort got event from callback

[2018-02-26 14:37:13] 2018/02/26 14:37:13.337 serial03 flush

[2018-02-26 14:37:13] 2018/02/26 14:37:13.337 \\.\COM6 flush

[2018-02-26 14:37:16] 2018/02/26 14:37:16.954 \\.\COM6 write.

[2018-02-26 14:37:16] 2018/02/26 14:37:16.954 wrote 6 to \\.\COM6, return asynSuccess

[2018-02-26 14:37:16] 2018/02/26 14:37:16.954 \\.\COM6 read.

[2018-02-26 14:37:16] 2018/02/26 14:37:16.986 \\.\COM6 read 3, return 0

[2018-02-26 14:37:16] 2018/02/26 14:37:16.987 serial03 queueUnlockPort

[2018-02-26 14:37:16] 2018/02/26 14:37:16.987 serial03 asynManager::queueUnlockPort waiting for event

[2018-02-26 14:37:16] 2018/02/26 14:37:16.987 serial03 queueUnlockPort unlock mutex 00000000026E7FA0 complete.

[2018-02-26 14:37:16] 2018/02/26 14:37:16.987 serial03 asynManager::queueLockPort locking port

[2018-02-26 14:37:16] 2018/02/26 14:37:16.987 serial03 asynManager::queueLockPort taking mutex 00000000026E7FA0

[2018-02-26 14:37:16] 2018/02/26 14:37:16.987 serial03 asynManager::queueLockPort queueing request

[2018-02-26 14:37:16] 2018/02/26 14:37:16.987 serial03 addr -1 queueRequest priority 0 not lockHolder

[2018-02-26 14:37:16] 2018/02/26 14:37:16.987 serial03 schedule queueRequest timeout

[2018-02-26 14:37:16] 2018/02/26 14:37:16.987 serial03 asynManager::queueLockPort waiting for event

[2018-02-26 14:37:16] 2018/02/26 14:37:16.987 asynManager::portThread port=serial03 callback

[2018-02-26 14:37:16] 2018/02/26 14:37:16.988 serial03 asynManager::queueLockPortCallback signaling begin event

[2018-02-26 14:37:16] 2018/02/26 14:37:16.988 serial03 asynManager::queueLockPortCallback waiting for mutex from queueUnlockPort

[2018-02-26 14:37:16] 2018/02/26 14:37:16.988 serial03 asynManager::queueLockPort got event from callback

[2018-02-26 14:37:16] 2018/02/26 14:37:16.988 serial03 flush

[2018-02-26 14:37:16] 2018/02/26 14:37:16.988 \\.\COM6 flush

[2018-02-26 14:37:20] 2018/02/26 14:37:20.604 \\.\COM6 write.

[2018-02-26 14:37:20] 2018/02/26 14:37:20.604 wrote 6 to \\.\COM6, return asynSuccess

[2018-02-26 14:37:20] 2018/02/26 14:37:20.604 \\.\COM6 read.

[2018-02-26 14:37:20] 2018/02/26 14:37:20.647 \\.\COM6 read 6, return 0

[2018-02-26 14:37:20] 2018/02/26 14:37:20.647 serial03 queueUnlockPort

[2018-02-26 14:37:20] 2018/02/26 14:37:20.647 serial03 asynManager::queueUnlockPort waiting for event

[2018-02-26 14:37:20] 2018/02/26 14:37:20.647 serial03 queueUnlockPort unlock mutex 00000000026E7FA0 complete.

[2018-02-26 14:38:50] 
[2018-02-26 14:38:50] epics> 
```

**Comment by kjwoodsISIS** [comment] 2018-02-27 09:06
Is this behaviour unique to the Linmots on ENGIN-X, or does it also happen with Linmots on other instruments? (e.g. HRPD, GEM).

**Comment by Tom-Willemsen** [comment] 2018-03-05 09:30
Let Matt North know cause and resolution when this ticket is complete

**Comment by ThomasLohnert** [comment] 2018-03-06 09:40
I have been unable to reproduce this behaviour on the office Linmot. Might have to wait until shutdown and investigate the behaviour directly on ENGIN-X

**Comment by kjwoodsISIS** [comment] 2018-03-06 09:44
Has the effect been observed on other LINMOTs (on other instruments - e.g. HRPD, GEM)?  Can we check the logs on other instruments?

**Comment by Tom-Willemsen** [comment] 2018-03-06 09:52
You'd only be able to tell after setting `asynSetTraceMask("serial03", -1, 0x11)` in the console (which gives very verbose debug logs, so we wouldn't want to leave this on all the time). 

It may be worth going down to HRPD/GEM after cycle and seeing if we can reproduce it there but I don't think we can check it on those instruments at the moment. The best we could do is to email the HRPD scientists and check if they've noticed abnormally slow moves on their linmots?

**Comment by kjwoodsISIS** [comment] 2018-03-06 09:57
OK.  In that case, leave it until the cycle is finished.

**Comment by DominicOram** [comment] 2018-03-15 13:36
Issue is now also occurring on GEM's beamscrapers

**Comment by kjwoodsISIS** [comment] 2018-03-15 13:39
Do we need to resolve this before the end of cycle?  If so, can we get some time on GEM to diagnose the problem?

**Comment by DominicOram** [comment] 2018-03-15 17:18
They're OK with it at the moment. I've told them to let us know if they have a couple of hours for us to look at it. I'm also going to set up the linmot in the office so that it is talking to DEMO. We think having the device continually connected for a few days might make it reproducible.

**Comment by FreddieAkeroyd** [comment] 2018-03-15 23:47
Between printed "flush" and "write", the only driver asyn win32 driver command executed would be:
 
    ret = PurgeComm(tty->commHandle, PURGE_RXCLEAR);

I don't know if something is timing out at a higher level?

**Comment by DominicOram** [comment] 2018-03-19 11:17
Leaving the linmot connected to NDXDEMO over the weekend reproduced the issue. Changing to software/hardware flow control didn't fix it. Resetting the MOXA did.

**Comment by FreddieAkeroyd** [comment] 2018-03-19 12:16
Would be interesting to know if restarting the moxa nport software on ndxdemo (or rebooting ndxdemo itself) would also fix it.

**Comment by ChrisM-S** [comment] 2018-03-19 12:23
Is the delay progressive? - i.e. possibly some list of unclosed connection handles is growing somewhere

could check paged and non-paged pool too on the NDX just in case the MOXA driver is allocating private driver storage.
```
powershell PS C:\> Get-Counter -Counter "\Memory\Pool Nonpaged Bytes"
powershell PS C:\> Get-Counter -Counter "\Memory\Pool Paged Bytes"

```

**Comment by FreddieAkeroyd** [comment] 2018-03-19 13:15
I believe it is the same delay, around 3-4 seconds. Also a linmot does not poll, so no bytes should have been travelling down the line over the weekend when it got into the funny state which was noticed on Monday.

**Comment by DominicOram** [comment] 2018-03-26 10:35
After removing the flow control the LINMOT in the office has been running for about a week quite happily. I think we should hotfix to remove the LINMOT flow control on:
- [ ] ENGINX
- [ ] GEM
- [ ] HRPD

Then see if the problem reoccurs over cycle. If it does, re-evaluate this ticket. Otherwise pull the hotfix into master.

**Comment by FreddieAkeroyd** [comment] 2018-03-26 11:28
Given we don't believe LINMOTS need flow control as per the manual/LabVIEW, should we just pull the fix into master immediately?

**Comment by DominicOram** [comment] 2018-03-26 11:32
Yes, let's do that. We'll close the ticket when merged and reopen if needs be.

**Closed** 2018-04-12 12:13 UTC
Labels: 2, completed, urgent
