### ISSUE TITLE
GUI: Validate non-numeric DAE data

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2167] opened 2017-03-08 14:22 UTC
In the DAE perspective -> Experiment setup -> Data Acquisition, you can enter non-numeric data in various boxes. Can we verify this is handled sensibly?

- What values are set when non-numeric data is sent
- How are comma-separated numbers interpreted. For example, is the default value in the timing box "5,000" interpreted correctly?

**Comment by KathrynBaker** [comment] 2022-02-01 17:39
Duplicate of #1616

**Closed by KathrynBaker** 2022-02-01 17:39 UTC
Labels: 0
