### ISSUE TITLE
genie: Odd responses for change_users()

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1340] opened 2016-06-29 14:20 UTC
I tried running the following commands from genie_python on NDXDEMO:

change_users("Adrian Potter")
change_users("adrian")

The responses were:

Odd-length string
Non-hexadecimal digit found

respectively. That isn't helpful. The documentation for change_users is:

```
"""Changes the users of the DAE

Args:
    users: a string containing the user name(s)
"""
```

so I expect the above to work, or at least receive a useful response as to why it failed.

**Comment by John-Holt-Tessella** [comment] 2017-06-01 13:47
Duplicate of #2265

**Closed** 2017-06-01 13:48 UTC
Labels: bug, duplicate
