### ISSUE TITLE
GUI: Component features not added to configuration

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2380] opened 2017-05-31 16:32 UTC
If you are creating/editing a configuration and add/remove a component, the changes are not propagated to the blocks/IOC/groups tab.

For instance, if I assign a component to a config containing NEW_BLOCK, then the block won't appear (albeit greyed out) in the blocks tab. If I save the config and revisit it, then it will appear.

**Comment by ThomasLohnert** [comment] 2017-09-21 10:50
Duplicate of https://github.com/ISISComputingGroup/IBEX/issues/1357

**Closed** 2018-01-18 08:27 UTC
Labels: bug, completed, duplicate, standdown, wontfix
