### ISSUE TITLE
GUI: IOC configuration redesign

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1804] opened 2016-11-14 15:02 UTC
I think it would be less confusing for the users if they could click "Add" to add an IOC rather than the magic incantation of ticking auto-start and auto-restart.
Also, it may be that someone wants an IOC in a configuration, but not set to auto-start (they do this sometimes with SECI).

Clicking "Add" could pop up a dialog equivalent to the blocks one that lets them choose auto-start, auto-restart, sim levels, macros, values and pv sets for that IOC. The existing way of setting IOC macros and PV sets is a bit long winded and not intuitive.

Note: would also require an "Edit" button and a "Delete" button.

The main edit/view configuration GUI could then only show the IOCs that are part of the configuration and components* rather than the whole list.

Note: I guess the component IOCs will need to be read-only in the same way as blocks are?

**Comment by KathrynBaker** [comment] 2016-11-14 15:36
Is this a duplicate of #1116?

**Comment by mattclarke** [comment] 2016-11-14 15:41
Yeah, but it is better defined

**Comment by DominicOram** [comment] 2016-11-24 09:45
Is it worth doing this before https://github.com/ISISComputingGroup/IBEX/issues/1397 or will the V3 ticket solve some of these niggles?

**Comment by John-Holt-Tessella** [comment] 2016-12-01 13:44
Do a paper prototype of this and get someone to do tasks to see if it works.

**Comment by ThomasLohnert** [comment] 2017-01-13 14:39
I have created an interactive HTML prototype, currently looking to get some user feedback on it.
If any of you want to have a look and comment on it in the meantime, you are more than welcome:
[IOC_html_mockup.zip](https://github.com/ISISComputingGroup/IBEX/files/704522/IOC_html_mockup.zip)
(Open home.html and click through. The prototype allows you to add, edit and delete a single IOC.)

**Comment by ThomasLohnert** [comment] 2017-01-30 11:08
https://github.com/ISISComputingGroup/ibex_gui/pull/426

**Closed** 2017-02-13 15:13 UTC
Labels: 2, completed, rework
