### ISSUE TITLE
IMAT: SKF G5 Chopper OPI Improvement

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2757] opened 2017-11-08 10:35 UTC
As a scientist working on IMAT, when I click on a chopper icon on the synoptic view, I would like it to open the corresponding tab on the SKF G5 Chopper OPI.

The SKF G5 Chopper can support 5 controllers.  The OPI has 5 tabs,each corresponding to a different controller.  When the scientist clicks on a chopper icon, the OPI is always opened at the first tab - meaning that scientist then has to select the appropriate tab.  It would be better if the OPI opened the tab corresponding to the chopper icon that the scientist clicked.

#### Acceptance Criteria
1. On clicking a chopper icon on the synoptic display, the SKF G5 Chopper OPI is opened at the corresponding tab .

#### Notes
1. See also #1907.

**Comment by davidkeymer** [comment] 2018-01-24 17:12
As mentioned, this is a duplicate of https://github.com/ISISComputingGroup/IBEX/issues/1907 which has now been merged.  Therefore closing this ticket.

**Closed by davidkeymer** 2018-01-24 17:12 UTC
Labels: duplicate
