### ISSUE TITLE
Easy way to see MOXA port numbers

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5367] opened 2020-03-30 14:50 UTC
As a support person I would like an easy way to see which devices are on what MOXA port. It was originally suggested that these be on the OPI for the device but this will likely confuse users.

**Comment by John-Holt-Tessella** [comment] 2020-03-31 08:40
I think we need to flesh this out a bit. Did they want any or all of the following answered:

- Which ports have had traffic in the last 5 minutes?
    - which direction and how much was the traffic (see useful moxa page)?
- What devices in the current config have a port configured?
- What devices in any config have a port configured?
- Which ports are connected to which moxa?
- Where are the moxa's located?
- A summary of connection details for a running IOC (serial/ip/none, port, baud rate, parity, etc)

**Comment by ChrisM-S** [comment] 2020-03-31 10:59
We could potentially enumerate the IO connection macros (IP address,ports)/IOCs in a dropdown.

Maybe in the Start/Stop IOC dialogue as an extra column?  (The mapping of COM/MOXA ports is more physical but usually comes down to seeing in which group of 16 the COM port is allocated to which box and subtracting 4).  To be honest, it would usually be clear which MOXA and range by the connections of other devices if they could be seen together in one table.

**Comment by FreddieAkeroyd** [comment] 2020-04-23 12:23
@ChrisM-S do you know where a moxa stores its COM mappings?

**Comment by ChrisM-S** [comment] 2020-04-23 17:29
Hi @FreddieAkeroyd, I think they were in the registry, I did investigate quite a while back because it will be useful to store and recover them (after a system re-clone for example).  It might be worth another probe though as the packaging has changed a bit with the most recent Nport suite.  I think I found settings in two places and also thought that there might be some driver reload/install step needed to activate changes (as well as changing the entries).

For getting information though, I think location would be enough.  One thing to note though, things like the baud rate may default to settings on the device if they are not explicitly controlled (hopefully asyn does this always) and RS232/423 modes are also configured on the device so may not be visible another way.

(Best thing to use to find out the registry locations is Sysinternals `procmon.exe`)

**Comment by John-Holt-Tessella** [comment] 2020-04-24 08:36
Before we create a solution I think we should decide what we want this ticket to do. It might be we want to look through all configs and get all assigned com ports. This would include devices which are not in the current config

**Comment by DominicOram** [comment] 2020-04-24 08:38
I agree with @John-Holt-Tessella. We need a meeting with those who requested this to get nail down the requirement

**Comment by KathrynBaker** [comment] 2020-04-24 08:56
I’m not sure we will get much more from those who requested it, as I’m not sure they actually know what they want. The same group of users (support people) have in the past asked us to hide things like setting COM Ports more thoroughly, but they still want to be able to see them easily.

We need to get agreement and buy in from the scientists as well as the support people depending on the solution.

#3874 might also provide some insight into this discussion, or this might be a duplicate of that ticket.

Implementing #3671 could also be helpful. Especially if some of the information in PComm proves useful. I had a look at it when I wrote the ticket to know that the ticket was worthwhile, I can’t remember it by now. In fact 3671 is top of my personal Friday ticket list, if I ever get as far as having a system that I can build with and actually take part in a Friday.

**Comment by DominicOram** [comment] 2020-04-24 09:02
> I’m not sure we will get much more from those who requested it, as I’m not sure they actually know what they want. The same group of users (support people) have in the past asked us to hide things like setting COM Ports more thoroughly, but they still want to be able to see them easily.

I don't think this is fair. There is clearly a process which they are trying to do which they are finding hard in the current system. We can at least document what the process is and what part is tripping them up. This may lead to one of the solutions discussed here or some entirely different solution.

**Comment by KathrynBaker** [comment] 2020-04-24 09:32
But there is more information in one of the other tickets I mentioned, and I can guarantee we have opposing views for this, which is why I say that I’m not sure they actually know what they want – when someone doing an experiment makes a mistake we are asked to lock things down, but then we are asked to open them up for flexibility at the same time. I’d also like to check who is asking for this, for me the list of stakeholders is all of the sample environment teams, plus the instrument scientists, plus us. It might be a small item from their point of view, it is not technically easy, and there are other ways to achieve the information they want than technical ones. Experience tell me that what they want is the shortcut to get from “I’ve plugged in to this socket, what setting do I need”, and the reciprocal of “I want to plug this in, where should it go”. We can achieve the former by writing down what the first COM reference is on that MOXA, the latter is harder to provide. These are not new use cases, these are not new requests, so I’m not sure what more we will get from them in this situation. This is not a trivial requirements gathering exercise, this is a balancing act between people who have very different ideas and needs.

**Comment by rerpha** [comment] 2023-05-04 10:37
duplicated by #7720

**Closed by rerpha** 2023-05-04 10:37 UTC
