### ISSUE TITLE
GUI: DAE tables race condition

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#1493] opened 2016-08-16 15:48 UTC
Drop down menus for selecting tables may wrongly be blank after instrument switch. This is because the GUI populates the combo boxes from 
1) the list of available tables as found in the relevant folder on the instrument, and 2) the table currently set in the DAE settings.

If the GUI reads 1 then 2, everything is fine as the combobox is filled with available files, then sets the current one as selection

If the GUI reads 2 then 1, it attempts to set the current file which is not in the (still empty) list resulting in the combobox selection being blank.

This bug probably also affects the time channel file and period file combo boxes.

It also would make sense to add some kind of check that the currently set table actually still exists (and provide feedback if it does not) as part of this ticket.

**Comment by kjwoodsISIS** [comment] 2016-08-16 15:50
Is this a duplicate of #1464?

**Comment by ThomasLohnert** [comment] 2016-08-16 15:55
No, separate issue discovered while doing that ticket

**Comment by ThomasLohnert** [comment] 2016-09-02 14:32
https://github.com/ISISComputingGroup/ibex_gui/pull/317

**Comment by IsabellaRey** [comment] 2016-09-05 16:18
Functionality all good from review. Please see minor things in pull request

**Closed** 2016-09-07 16:07 UTC
Labels: 1, bug, fixed
