### ISSUE TITLE
GUI: Add PV to Existing Log Plotter Graph

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2178] opened 2017-03-10 16:12 UTC
Label plots in log plotter graph1, graph2 etc. Then add option is right click plot log history on blocks and opis so that you can add a PV to an old graph. If CS Studio does not support this do not spend time on it.

**Comment by DominicOram** [comment] 2017-06-27 12:57
Duplicate of https://github.com/ISISComputingGroup/IBEX/issues/2261

**Closed** 2017-06-27 12:57 UTC
Labels: duplicate
