### ISSUE TITLE
Reflectometry: A1 scans are corrected

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5746] opened 2020-09-21 13:47 UTC
Analyser scans for theta and height were not correct there is something wrong with the values. Possibly it is an offset somewhere in SECI. Look at the beamline and try to figure out what is wrong. May have to use SECI and IBEX and compare positions under the two circumstances to find out what was wrong.

### Acceptance Criteria

- Understand problem with positions

**Comment by John-Holt-Tessella** [comment] 2020-10-08 09:32
Scientist is happy

**Comment by ThomasLohnert** [comment] 2020-10-12 15:24
This could use a bit more detail - I believe the cause for the discrepancy was the deadband for the mirror position being to large, which mean it ended up in slightly the wrong place, which meant the tracked beam as a result of which the beam was slightly offset. Resolved by adjusting the deadband on the mirror to be more sensible.

@John-Holt-Tessella please correct me if I have confused this with a different issue. Otherwise I think this can go to completed

**Comment by John-Holt-Tessella** [comment] 2020-10-13 07:58
I think this was #5745

**Comment by ThomasLohnert** [comment] 2020-10-13 09:46
Ok I can't remember exactly what this one was about, I think this might also be related to the deadband. Either way the issue has gone away since and the results from system tests involving the analyser look correct. Closing this ticket.

**Closed by ThomasLohnert** 2020-10-13 09:46 UTC
Labels: 3, review, under review
