### ISSUE TITLE
GUI: Create OPI for the FMR Equipment

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5552] opened 2020-07-20 08:10 UTC
As an experiment scientist I need an OPI to control the FMR equipment; there is already an IOC that was written for use under SECI. See #5270 

### Acceptance Criteria

- OPI exists for the FMR IOC

**Comment by rerpha** [comment] 2022-06-08 14:48
Duplicate of #6003

**Closed by rerpha** 2022-06-08 14:48 UTC
Labels: training
