### ISSUE TITLE
get_sample_pars is not working

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1396] opened 2016-07-11 14:00 UTC
On LARMOR this gives:

 a1=get_sample_pars()
ERROR: 'NoneType' object has no attribute 'groups'

**Comment by kjwoodsISIS** [comment] 2016-07-11 14:08
This is a duplicate of #1341

**Comment by kjwoodsISIS** [comment] 2016-07-11 14:10
#1341 has been closed.  Fix the problem under this issue.

**Comment by John-Holt-Tessella** [comment] 2016-07-14 12:41
There is an underlying problem here that some of the PVs seemed to have been wrongly categorised. The sample parameters are reported from the PV as:

```
caget -S -t %MYPVPREFIX%CS:BLOCKSERVER:SAMPLE_PARS|uzhex
[
  "PARS:BL:BEAMSTOP:POS", 
  "PARS:BL:JOURNAL:BLOCKS", 
  "PARS:SAMPLE:AOI", 
  "PARS:SAMLE:GEOMETRY", 
  "PARS:SAMPLE:HEIGHT", 
  "PARS:SAMPLE:NAME", 
  "PARS:SAMPLE:PHI", 
  "PAR:SAMPLE:THICK", 
  "PARS:SAMPLE:TYPE", 
  "PARS:SAMPLE:WIDTH", 
  "PARS:SCRIPT:NAME"]
```

and similarly for beamline parameters:

```
C:\Instrument\Apps\EPICS>caget -S -t %MYPVPREFIX%CS:BLOCKSERVER:BEAMLINE_PARS|uzhex
[ "PARS:BL:A1", 
  "PARS:BL:A2", 
  "PARS:BL:A3", 
  "PARS:BL:BCX", 
  "PARS:BL:BCY", 
  "PARS:BL:CHOPEN:ANG", 
  "PARS:BL:FOEMIRROR", 
  "PARS:BL:L1", 
  "PARS:BL:SDD"]
```

You can see things in the sample parameters without the SAMPLE prefix and things which look like they should be in the beamline parameters in the wrong place.

So is the desired behaviour to show all those in the sample category regardless of their name prefix or is it that this is an error and gennie should warn the user of this and we also need to recategorise  the parameters?

NB Some of the values that need recategorising are in `EPICS\ioc\master\INSTETC\db\inst_string_parameters.db`

**Comment by FreddieAkeroyd** [comment] 2016-07-14 13:48
Hi John, I noticed this too a while back, but was not sure what would break if I recategorised them. I guess the gui sample/beamline tables might need updating (or does it just reformat the list and not work about the PV names? I hadn't looked into if genie python or anything Rob might have done would need updating, hopefully the PV names are just internal to genie_python if at all. SCRIPT:NAME is a bit of a funny, it has traditionally been a sample parameter so I guess should really be PARS:SAMPLE:SCRIPT:NAME

**Comment by AdrianPotter** [comment] 2016-07-21 09:14
Sounds like there's no concrete reason it shouldn't be changed. Is it worth checking with Rob first though? Anything else specific we need to check in genie_python?

**Comment by AdrianPotter** [comment] 2016-07-21 09:20
Still to do:
1. Check the answers to the above questions with @FreddieAkeroyd 
1. Change the categories as described by @John-Holt-Tessella 
1. Test nothing is broken in genie_python
1. Add some more unit tests for any functionality touched by this change

**Comment by AdrianPotter** [comment] 2016-07-22 13:48
https://github.com/ISISComputingGroup/genie_python/pull/40
https://github.com/ISISComputingGroup/EPICS-ioc/pull/52

**Closed** 2016-08-11 08:54 UTC
Labels: bug, completed, fixed, rework
