### ISSUE TITLE
Log plotting of OPIs does not show history

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2107] opened 2017-02-22 23:11 UTC
If you right click on e.g. larmor jaws HGAP and plot in log plotter you will get no history. This is because the history is created as HGAP.VAL and the plot is of HGAP. If you manually add the same PV but with .VAL at the end, you see the history. The block history works OK as the archive config file is created without .VAL and the "block history" doesn't add a .VAL    For items that come from DB records you need to specify the list of field names in the info record so these currently always get a .VAL added.

It would be possible to strip .VAL in the script that parses the db info records and generates the archive configuration, but I wonder if we instead should be more consistent in always explicitly specifying .VAL ? 
We may be able to fix graph right click to add .VAL if no field is present in the PV.

**Comment by DominicOram** [comment] 2017-03-31 13:16
This is a duplicate of https://github.com/ISISComputingGroup/IBEX/issues/2177. I'm going to keep the other as there is a little more discussion of a possible solution on it.

**Closed** 2017-03-31 13:16 UTC
Labels: duplicate
