### ISSUE TITLE
PEARL: OPI for PEARL Beam Dimensions

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6046] opened 2021-01-08 15:57 UTC
As a PEARL scientist I want to be able to control the jaws on PEARL, so that I can shape the beam.

#### Acceptance Criteria
1. Using the IBEX client, I can control the PEARL Jaws
1. Using genie_python, I can control the PEARL Jaws

#### Notes
1. Check the [PEARL Instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/PEARL-Instrument-Details).
1. The PEARL Beam Dimensions VI is related to the PEARL Jaws VI.
1. The OPI must offer functionality equivalent to the existing VI (located here: `C:\LabVIEW Modules\Instruments\PEARL\PEARL Jaws` - specifically in the `Screens` sub-directory).

**Comment by davidkeymer** [comment] 2023-08-02 16:02
Duplicate of https://github.com/ISISComputingGroup/IBEX/issues/6045

**Closed by davidkeymer** 2023-08-02 16:02 UTC
Labels: duplicate, wontfix, Good First Issue
