### ISSUE TITLE
MERLIN : Oscillating Collimator

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#3611] opened 2018-09-26 15:23 UTC
MERLIN Oscillating Collimator had a motor that broke, it is believed as a result of a failed mechanical coupling. Issues to consider for Merlin oscillating collimator :
1) MERLIN Oscillating Collimator Galil code has been altered on ndxmerlin to try and time-out the homing sequence. There is no encoder or limit switches. As a result, the jogs used in the homing have been replaced with relative moves. This then stops the motor from running forever if the homing signal fails or there is a mechanical failure.
2) Display homing flag (TTL input 6)
3) Home flag indicator for successful home.
4) On Galil IOC restart, for oscillations to start when requested, you must enter the desired oscillating angle or operating frequency again for the system to operate. I do not think this should be necessary.
5) I believe that if STOP is pressed, it kills all the threads in the Galil - not just the oscillating collimator thread.

**Comment by kjwoodsISIS** [comment] 2018-09-26 16:14
This ticket relates to #3607.

**Comment by GDH-ISIS** [comment] 2018-10-05 16:19
The electronic home flag is indicated on the following PVs - the two inputs are the inverse of eachother.
IN:MERLIN:MOT:DMC01:Galil0Bi5_STATUS
IN:MERLIN:MOT:DMC01:Galil0Bi6_STATUS

**Comment by Tom-Willemsen** [comment] 2019-03-12 09:25
Re-requested LET (In particular point 4 above).

**Comment by DominicOram** [comment] 2019-03-14 10:36
Do in conjunction with #4027

**Comment by kjwoodsISIS** [comment] 2019-04-18 13:10
Believed to be a duplicate of #4027

**Closed** 2019-04-18 13:51 UTC
Labels: duplicate, in progress, re-requested
