### ISSUE TITLE
genie_python: hide CA messages

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1188] opened 2016-05-11 13:31 UTC
Sometimes genie_python will start printing messages from the underlying CA layer to the console.

Everything still works fine, but it is worrying for the user to see these messages.

Do we need to build a version of CA with the dump to std_out etc. disabled?

Rob says it is needed for the next cycle!

**Comment by FreddieAkeroyd** [comment] 2016-05-11 13:51
Ideally I guess they would go to genie_python's logfile, but that might be a bit awkward to coordinate. Either a separate log file or ignore would be doable.

**Comment by FreddieAkeroyd** [comment] 2016-05-11 13:55
@mattclarke  could you please add a sample error message(s), as the IOCs use the CA library as well we just need to be a bit careful about what we might ignore, so we may have to do a separate build.

**Comment by FreddieAkeroyd** [comment] 2016-05-11 16:27
Looks like CA library uses printf, fprintf(stderr) and errlogPrintf at various points, so best solution will depend on error message. Intercepting errlogPrintf is probably the easiest thing to handle if it turns out errors go that way.

**Comment by FreddieAkeroyd** [comment] 2016-05-12 15:14
Waiting for 10 uamps
** Ending Run 00009604 at 14:45:50 11/05/16
CA.Client.Diagnostic.................................
    Warning: "Virtual circuit unresponsive"
Source File: ..\tcpiiu.cpp Line Number: 945
.....................................................
dosans_normal

**Comment by FreddieAkeroyd** [comment] 2016-05-12 15:16
Thickness=1.0
** Beginning Run 00009602 at 14:01:11 11/05/16
*  Proposal Number:
*  Experiment Team: LarmorTeam
CA.Client.Diagnostic.................................
    Warning: "Virtual circuit unresponsive"
Source File: ..\tcpiiu.cpp Line Number: 945
.....................................................
Restarting archiver
Waiting for 10 uamps
** Ending Run 00009602 at 14:16:21 11/05/16
CA.Client.Diagnostic.................................
    Warning: "Virtual circuit unresponsive"
Source File: ..\tcpiiu.cpp Line Number: 945
.....................................................
dosans_normal
setup larmor normal
Setting TCB range 5.0 to 100000.0 step 100.0 (LINEAR binning)
Setting TCB range 0.0 to 0.0 step 0.0 (LINEAR binning)
Using the following Sample Parameters

**Comment by FreddieAkeroyd** [comment] 2016-05-12 15:39
looks like ca_client_context.cpp line 324 may be the area, if this is right then it seems a ca_exception_func may have been installed?

**Comment by FreddieAkeroyd** [comment] 2016-05-12 16:02
The python caChannel package installs its own exception handler (exceptionCallback in _ca314.cpp), which does use errlogPrintf. So we may just be able to replace errlogPrintf, but looking at the caChannel code it seems to swallow the PV name in most cases so I think we should change it to make a better error message.

**Comment by kjwoodsISIS** [comment] 2016-05-19 09:20
Need to find the root cause (may be caused by a PV disconnecting).

**Comment by kjwoodsISIS** [comment] 2016-06-16 12:53
We will investigate this during System testing prior to Cycle 16/02 (starting 28th June).

**Comment by kjwoodsISIS** [comment] 2016-11-03 10:14
Check with Rob whether this is still an issue.

**Comment by ThomasLohnert** [comment] 2018-03-21 09:41
+1 from Merlin. It's not causing functional issues but causing concern and confusion to the users, who the scientists then have to assuage etc.

**Comment by FreddieAkeroyd** [comment] 2018-04-05 17:41
The original messsage was a CA.Client.Diagnostic and this can be removed by registering a printf handler via  ca_replace_printf_handler in CaChannel. However if i start an IOC, do a get_pv and then stop the IOC i get a  CA.Client.Exception  instead that is not caught by this. 

In [2]: Unexpected problem with CA circuit to server "NDW1548.isis.cclrc.ac.uk:5
064" was "An existing connection was forcibly closed by the remote host. " - dis
connecting
CA.Client.Exception...............................................
    Warning: "Virtual circuit disconnect"
    Context: "NDW1548.isis.cclrc.ac.uk:5064"
    Source File: ..\cac.cpp line 1223
    Current Time: Thu Apr 05 2018 18:23:37.812785824
..................................................................

If i register an exception event callback (partly exposed via CaChannel) i can reduce this to

Unexpected problem with CA circuit to server "NDW1548.isis.cclrc.ac.uk:
5064" was "An existing connection was forcibly closed by the remote host. " - di
sconnecting

This remaining message is printed via a errlogPrintf() in the EPICS CA library. I think we can remove it by calling      eltc(0)       which removes error logging to the console (which is the default). Ideally we might  call       errlogSetConsole()   to redirect it to separate file, but this is a 3.15 function and CaChannel looks to be built against 3.14     however eltc will still redirect messages to the epics errorlog process and if its raising an exception anyway it may be OK to ignore them.

At the moment it looks like building CaChannel ourselves is the only way to definitely remove the messages, I'll send an email to the CaChannel author to see how he feels about adding an eltc() option and also about my additions to add an exception callback

**Comment by FreddieAkeroyd** [comment] 2018-05-18 18:33
Able to call eltc via ctypes, so just need our own version of CaChannel.py for the moment that exposes the additional functions

**Comment by FreddieAkeroyd** [comment] 2018-05-21 09:08
Errors are now logged to ususal geneie python log file.

* start ioc
* use   get_pv   from genie_python
* shudown IOC
* use   get_pv again from genie_python

previously you would get an exception printed, now it should generate an entry in the genie_python log file instead and not on screen e.g.

2018-05-21T10:07:13	(CA)	(20564)	ERROR: CAException: type=-1 state=192 op=5 file=..\cac.cpp lineNo=1223
2018-05-21T10:07:13	(CA)	(20564)	ERROR: CAException: type=6 state=192 op=0 file=..\getCopy.cpp lineNo=92

**Closed** 2018-06-06 16:02 UTC
Labels: 2, completed, fixed, for release, re-requested, urgent
