### ISSUE TITLE
Eurotherm sends setpoint of 0

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1630] opened 2016-09-19 16:35 UTC
Ian has reported that when the eurotherm starts it sends a setpoint of 0 to the hardware, sending any setpoint on startup is undesirable. I think this may be due to the calibration code that was added?

**Comment by IsabellaRey** [comment] 2016-09-21 15:57
Root cause of this described in ISISComputingGroup/IBEX#1646

For IRIS a temporary safe fix is to comment out the SCAN field of OUT_SP in devEurotherm.db

This stops the setpoint from being sent at startup, but it also means that ramping doesn't work (this should be fine, Freddie says they're not using ramping on IRIS). The setpoint can still be sent from the PV connected to the OPI, as there already is a FLNK between the two.

**Comment by IsabellaRey** [comment] 2016-09-21 15:58
I have asked Ian when it's best to put the temporary fix in

**Comment by IsabellaRey** [comment] 2016-09-21 15:59
I'm moving this ticket to impeded until we actually deploy the fix

**Closed** 2016-10-05 15:28 UTC
Labels: urgent
