### ISSUE TITLE
EMU: python console terminating 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5137] opened 2020-01-31 13:34 UTC
A script was Ctrl-Ced on EMU, and then r.end() was typed - the end() seemed to terminate the underlying python 

```
    g.waitfor_mevents(mevents)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 596, in waitfor_mevents
    __api.waitfor.start_waiting(mevents=mevents)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_waitfor.py", line 353, in start_waiting
    sleep(DELAY_IN_WAIT_FOR_SLEEP_LOOP)
KeyboardInterrupt
r.end()
Run information:

Sample = dummy_test
Orientation = plate
Temp = 10
Field = 0
Geometry = L
RB Number = -1000
Experimental Team = RAL
Comment = long stats with dummy signal over weekend with ZF measurement
Run title = dummy_test_T=10_F=0
Is the run information correct (y/n)?y
** Ending Run 00101523 at 13:17:54 31/01/20 

Console already exited with value: 1 while waiting for an answer.


Console already exited with value: 1 while waiting for an answer.

Console already exited with value: 1 while waiting for an answer.

Console already exited with value: 1 while waiting for an answer.


Console already exited with value: 1 while waiting for an answer.

Console already exited with value: 1 while waiting for an answer.
```

**Comment by John-Holt-Tessella** [comment] 2020-02-03 09:11
@Tom-Willemsen This may be caused by not passing the keyboard exception back to main thread from graphing loop. We should look at this.

**Comment by Tom-Willemsen** [comment] 2020-02-03 11:05
I've added a committed to the end of [this pr](https://github.com/ISISNeutronMuon/InstrumentScripts/pull/50) which reraises keyboard interrupts on the main thread. I've checked doing various combinations of ctrl-c during begin and end and as far as I can tell it no longer causes the issue seen above.

**Comment by JamesKingWork** [comment] 2020-02-04 09:45
Does this need to be reviewed as part of https://github.com/ISISComputingGroup/IBEX/issues/5015 ?

**Comment by Tom-Willemsen** [comment] 2020-02-04 09:48
It would make sense for this to be reviewed either with or after https://github.com/ISISComputingGroup/IBEX/issues/5015 , yes.

**Comment by John-Holt-Tessella** [comment] 2020-02-13 15:36
This is now going to be done as a sepaate process so is no longer needed.

**Comment by kjwoodsISIS** [comment] 2020-05-14 13:27
Issue will be fixed via a separate ticket.  Close.

**Closed by kjwoodsISIS** 2020-05-14 13:27 UTC
Labels: 1, wontfix
