### ISSUE TITLE
GUI DAE Perspective: Scrollbars needed

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2443] opened 2017-06-20 09:31 UTC
If you look at the DAE with a smaller or odd resolution, you lose access to parts of it - is there a reason not to allow it to have scrollbars? If not, we should add them.

**Comment by AdrianPotter** [comment] 2017-06-26 08:57
I'm sure there was a duplicate of this somewhere but darned if I can find it. At our introduction to Ibex training, it was observed that several controls were inaccessible on smaller displays. We should check all perspectives for similar issues.

**Comment by Tom-Willemsen** [comment] 2017-06-26 09:14
https://github.com/ISISComputingGroup/IBEX/issues/2047?

**Comment by AdrianPotter** [comment] 2017-06-26 09:23
That's the one, thanks :)

**Comment by ChrisM-S** [comment] 2017-06-26 10:02
Yes, it would be good also to be able to shrink the view vertically to allow just the top dashboard area to show,  SECI does it with a button but just allowing scroll bars rather than blocking window size changes would probably be sufficient.

**Comment by AdrianPotter** [comment] 2017-08-24 14:27
Doing now. Otherwise it'll cause a merge conflict when I do exactly the same thing as part of the E4 migration

**Comment by Tom-Willemsen** [comment] 2017-08-25 15:24
Merging this, but I'll leave #2047 open as that has a wider scope (whole GUI vs just DAE perspective)

**Closed** 2017-09-21 10:37 UTC
Labels: 0.5, bug, completed, fixed
