### ISSUE TITLE
GUI/blockserver:Blocks in a config can not be added to a group in a component

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2033] opened 2017-02-07 15:04 UTC
If a group is defined within a component a block within a config that uses that component can not place the block within the group. Although from the GUI it appears you can when you save the changes are ignored.

**Comment by Tom-Willemsen** [comment] 2018-01-15 13:54
Cannot reproduce. Can anyone else?

**Comment by KathrynBaker** [comment] 2022-02-01 16:52
Cannot reproduce, closing issue - we can create a new one if we find that this is the case

**Closed by KathrynBaker** 2022-02-01 16:52 UTC
Labels: bug
