### ISSUE TITLE
BlockServer: Error saving new config causes list of configs not to be updated (caused by unmovable git lock)

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1769] opened 2016-11-02 10:45 UTC
Reproduce:

1. Start instrument
1. Create a lock file in `C:\Instrument\Settings\config\NDW1407\.git\index.lock`
1. Open file in notepad so it can not be removed; this is an optional step for the bug but the ticket should address with and without this
1. Add a new configuration and save
1. Open edit list to reedit (it is not on list)

What is the desired behaviour here? Should it wait for a lock and retry. Should it give up and issue a MINOR/MAJOR warning?

**Comment by John-Holt-Tessella** [comment] 2016-11-02 10:46
This is related to #1673 but is not part of the ticket because we wanted to push this one through.

**Comment by ThomasLohnert** [comment] 2018-01-15 09:10
Cannot reproduce bug, presumably fixed with https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/139

**Closed** 2018-01-15 09:11 UTC
Labels: bug, wontfix
