### ISSUE TITLE
Dataweb: Access from ridgeway

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2201] opened 2017-03-24 10:11 UTC
User has reported that he could not see the dataweb from ridgeway. Attached is the screen shot.

Reported by Vicky Garcia.

**Comment by John-Holt-Tessella** [comment] 2017-03-24 10:12
![screen shot 2017-03-22 at 20 41 07](https://cloud.githubusercontent.com/assets/7570055/24289713/5bec74b6-107a-11e7-87e3-eb76411f31a8.png)

**Comment by DominicOram** [comment] 2017-03-24 10:16
From the logs it appears that 130.246.53.220 was happily connected all of the 22nd. At 20:41:07 there was no noticeable connection from another IP but at 20:46:45 130.246.37.228 successfully connected.

**Comment by DominicOram** [comment] 2017-03-24 10:17
See the attached log if you think there's something I have forgotten.
[JSON_bourne.log.2017-03-22.txt](https://github.com/ISISComputingGroup/IBEX/files/867508/JSON_bourne.log.2017-03-22.txt)

**Comment by Tom-Willemsen** [comment] 2017-03-24 10:19
When I did the ticket about displaying a page on error I had to choose a timeout. Maybe that timeout is just too short and the connection from the ridgeway is slower than that? https://github.com/ISISComputingGroup/IBEX/issues/1872

**Comment by DominicOram** [comment] 2017-03-24 10:21
Could be, a 1 second timeout should be enough though. I think this would be another useful reason to do https://github.com/ISISComputingGroup/IBEX/issues/2159

**Comment by John-Holt-Tessella** [comment] 2017-03-24 10:44
It might be a javascript origin policy problem. You might not be able to turn this off in Safari (the browser they are using) see http://stackoverflow.com/questions/4556429/disabling-same-origin-policy-in-safari. Making it a static site might be best.

**Comment by John-Holt-Tessella** [comment] 2017-03-24 10:48
I have sent the following:

```
Would it be possible for your user to try this on his mac not in ridgeway house when someone else can access the site. Also does he have a different browser he could try it in and if so can he try that instead. We suspect that the error may have to do with an incompatibility between our site and his browser, but we are not sure; by trying a different browser and different location we can rule out a number of things.
```

**Comment by DominicOram** [comment] 2017-05-04 13:24
@samueljackson92 tried this on a mac whilst at RAL, seemed to work fine

**Comment by kjwoodsISIS** [comment] 2017-05-04 13:34
OK.  What can we conclude from this?  What should we check next? (if anything).

**Comment by DominicOram** [comment] 2017-05-04 13:37
I think we should go ahead and do #2159, it will generally make the site faster/more accessible. I see no way of further testing this ticket, we should close it.

**Comment by AdrianPotter** [comment] 2017-05-16 09:17
If this issue is to do with cross-browser compatibility then fixing the markup issues as suggested by @FreddieAkeroyd on #2159 would be a good start

**Comment by KathrynBaker** [comment] 2017-05-17 11:58
I just tested this using Safari on an iPad via eduroam, and it worked with no problems (LARMOR rather than IRIS) - just to be nosy. I'm not about to walk over to Ridgeway to test this from there given the rain, but I thought it was worth noting another working situation.

**Comment by Tom-Willemsen** [comment] 2017-05-18 18:23
Does anyone recognise the browser extensions in the top right of the screenshot at the top of this ticket? I can see gmail and adblock, but don't recognise the others.

Notably the browser extension which displays as a green circle is displaying a "notification" which often means an extension has done "something" to the web page. If it's a javascript blocker or something similar, that would explain the observed behaviour.

Also tried reproducing on various browser/OS combinations at home, without success.

**Comment by kjwoodsISIS** [comment] 2017-05-19 07:49
I think we have tested this sufficiently.  We seem to have no evidence that there is a genuine problem.  We can't reproduce it, so there is little prospect of being able to solve it.  Anything else is speculation.  We should close this ticket.

**Comment by John-Holt-Tessella** [comment] 2017-05-19 08:32
Yes have we let Vicky know that we can't reproduce this?

**Comment by kjwoodsISIS** [comment] 2017-05-19 09:19
No, not yet.  I think Vicky reported the issue to you - could you let her know.

**Comment by John-Holt-Tessella** [comment] 2017-05-19 09:53
Email sent to Vicky.

**Closed** 2017-06-01 12:28 UTC
Labels: 0.5, bug, completed, wontfix
