### ISSUE TITLE
Blockserver: Put all files in configuration under git

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2134] opened 2017-02-28 11:04 UTC
All files within settings/configurations should be under version control and regularly add/remove and committed to the repo.
At the moment only configurations, synoptics etc folder are added. We should add all folders but the rules are that they should just be pushed as are never recovered (unlike synoptics etc).
If possible the file watcher is used and will add files after they have not changed for a quiet period (probably of 10 minutes)

**Comment by DominicOram** [comment] 2017-03-01 10:43
Is this a  duplicate of #2035?

**Comment by KathrynBaker** [comment] 2017-03-01 11:04
Actually I think it answers that ticket, which just asks if we should do this…

**Comment by AdrianPotter** [comment] 2017-04-06 13:29
Note that new files will behave slightly differently from existing files. The filewatcher in the block server doesn't currently let you change a file it's tracking manually, it has to be done via Ibex. That makes sense for configurations but not for other files like globals.txt and Python scripts. Make sure changes to these files are commited rather than being reverted by the filewatcher. Make sure that the existing behaviour on configuration files is unchanged.

**Closed** 2017-06-29 12:29 UTC
Labels: 1, completed, fixed, rework
