### ISSUE TITLE
Hackathon: No error on no opi

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1748] opened 2016-10-27 09:35 UTC
There is a bug if a device screen does not have an opi defined and it is opened.

**Comment by mattclarke** [comment] 2016-10-27 09:41
I think this needs to be done asap, if we intend to make device screens available.

**Comment by AdrianPotter** [comment] 2016-12-23 13:56
Duplicate of #1878

**Closed** 2016-12-23 13:57 UTC
Labels: bug, duplicate
