### ISSUE TITLE
Blockserver: does not always start all correct IOCs on server start

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4660] opened 2019-08-19 17:12 UTC
It appears that sometimes the blockserver fails to start certain IOCs, even though they are in the config. Reloading the current config via `g.reload_current_config()` usually brings the required IOC back.

I am not sure whether this bug is general or whether it only applies to the first config load after a deployment.

Spotted when deploying on GEM/MUONFE/LOQ by @JamesKingWork and I

**Comment by Tom-Willemsen** [comment] 2019-08-20 10:42
Not easily reproducible by switching configs (tested on both my machine and DEMO). Suggest keeping an eye on this when deploying on the instruments - we may need to do a hotfix if it turns up on any more instruments

**Comment by Tom-Willemsen** [comment] 2019-08-20 10:58
Problem is reproducible on MFE by repeatedly running `start_ibex_server.bat` - probably do need to find a fix for this. I will work on it.

**Comment by kjwoodsISIS** [comment] 2019-08-20 11:06
This problem looks like a regression.  It would be valuable to understand if a code change has caused it, ideally, so that we can learn to avoid such mistakes in future and, at least, so that we have appropriate regression tests in place.

**Comment by DominicOram** [comment] 2019-08-22 17:40
Moving to complete as reviewed by @Alistair-McGann-Tessella

**Closed** 2019-09-12 07:22 UTC
Labels: 1, For mid-August release, bug, fixed
