### ISSUE TITLE
IEG: If pressure calibration returns number less than zero, display as zero.

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2758] opened 2017-11-08 13:57 UTC
As per title. See email from Matt North below. Requested for cycle.

> Hi Tom,
> 
> The IRIS team will be using the IEG in the next cycle.
> 
> Is it possible for the OPI to not display –ve numbers associated with the IN:IRIS:IEG_01:PRESSURE:GUI.OSV PV?
> 
> After very extended periods of pumping the calibration returns a negative number, it would be ideal if the OPI displayed this as zero in these cases.
> 
> Thanks,
> Matt

**Comment by AdrianPotter** [comment] 2017-11-08 17:39
Emailed Matt with the following, awaiting feedback:

Hi Matt,

I’ve just picked up on the issue raised about the IEG reporting negative pressures. Our ticket for the issue is here:

https://github.com/ISISComputingGroup/IBEX/issues/2758

> Having discussed with Tom, I had a number of follow up questions that effect the implementation of the > solution:
>
> - How does the displaying of negative pressure affect the ability to run the IEG?
>
> The IEG currently has an actual pressure reading, and the value displayed in the OPI. The displayed value > changes to “…> 350 mbar” for large pressures. The underlying pressure reading can go negative (and > >350) but has a major alarm associated with it which will be alerted in the GUI in the alarms perspective >and on any associated blocks.
>
> - Do you use the actual pressure value for experiments? Is it an issue if that goes negative?
> - Would a message similar to the high pressure message be suitable for interpolated pressures <0?
>
>The initial proposed solution was to simply output 0 to the GUI, but it raised the following questions
>
> - Does having the underlying pressure value negative affect your ability to do analysis on the data?
> - Would masking the negative pressure prevent you from seeing errors in the underlying calibration file?
>
>Please let me know your thoughts. We can certainly fix the issue, but to do it right we need a slightly >better understanding of your workflow and what you need the solution to achieve.
>
>All the best,
>Adrian

**Comment by AdrianPotter** [comment] 2017-11-09 08:58
From Ian:

>Hi Adrian,
>
>To answer your questions from my point of view:
>                
>Displaying a negative pressure does not affect the running of the IEG, but does not have any real meaning.
>
>I can not foresee ever using the pressure for experiments, but it can be useful to plot the data for diagnostic purposes.                
>
>A message would be ok, but a numerical value would be better so that graphing of the data works (where the program expects numerical data)
>
>Having the value negative would not seriously impact on our ability to do analysis.
>
>Indicating the pressure as negative is an error in the calibration file – the lowest possible value is 0, so any negative value is an error. If you can modify the calibration to reflect this, that would be ideal.
>
>Thanks,
>
>Ian
>

From Matt

>Morning Adrian,
>
>Regarding the transducer field I have nothing to add from Ian’s reponse.
>
>However, as I was writing the user manual it made sense for some of the labels I had specified for the GUI to change, namely:
>
>“Status:” to be renamed “Error:”
>
>“Mode:” to be renamed ‘’ Operating State:”
>
>“Sample Pressure:” to be renamed “IVC Pressure:”
>
>Ian.
>
>Are you happy for the “Sample bin pressure” field to be removed? This is left over from the days when we didn’t have a hard vac interlock and the VI provided logic to inhibit some processes.
>
>Thanks,
>Matt
>

Suggested work:

- Have a `PRESSURE:RAW` PV with the true calculated value
- `PRESSURE` to be limited to 0-350 mbar with suitable alarms
- `PRESSURE` GUI to have a similar message to "> 350mbar" message

I think correcting calibration files is outside of the scope of IBEX.

**Comment by AdrianPotter** [comment] 2017-11-09 09:13
Let Ian and Matt know when the work is done. The IOC changes are to be hotfixed to Iris. The GUI changes will be deployed at the next release.

**Comment by AdrianPotter** [comment] 2017-11-10 15:04
- [ ] **Once merged**: Apply IOC hotfix to IRIS and report to Ian/Matt. Let them know that GUI changes will follow at the next deploy

**Comment by Tom-Willemsen** [comment] 2017-11-13 11:03
Hotfixed onto IRIS.

**Closed** 2017-11-16 14:33 UTC
Labels: 0.5, completed, fixed, urgent
