### ISSUE TITLE
NIMROD: Support for a MKS PR4000B

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4056] opened 2019-02-28 09:56 UTC
As a NIMROD scientist, I want to acquire pressure readings from the new gas panel device, so that I can monitor & log pressure values during my experiments.  The new gas panel will provide up to 4 separate pressure readings.

#### Acceptance Criteria
1. I can see, from the UI, whether the gas panel device is connected (i.e. a comms OK light).
1. I can view up to 4 pressure readings in the UI.
1. I can obtain any of the 4 pressure readings via a genie_python script.

#### Notes
1. The new gas panel will use a [MKS PR4000B](https://www.mksinst.com/product/Product.aspx?ProductID=831) pressure controller.
1. There is an existing [EPICS driver](https://epics.anl.gov/modules/manufacturer.php#MKS%20Instruments) for the MKS PR4000B.
1. The MKS PR4000B manual is here: `\\isis\shares\ISIS_Experimental_Controls\Manuals\MKS_PR4000B_Controller`
1. See also the [NIMROD wiki](https://github.com/ISISComputingGroup/IBEX/wiki/NIMROD-Instrument-Details) page.
1. Original description: `As a NIMROD instrument scientist I would like to read from my new gas panel. The pressure readouts are done with a MKS PR4000B, details to follow...`

**Comment by KathrynBaker** [comment] 2019-02-28 12:05
There are VIs for the MKS PDR2000, it may provide useful information if the devices are similar enough.

**Comment by davidkeymer** [comment] 2019-04-29 13:48
The gas panel containing the two devices is complete and is currently undergoing leak tests in R55.  It is due to move to the NIMROD area on completion, at which point we should be able to connect it a MOXA for communications testing.
I shall try to find out when this is due to happen...

**Comment by davidkeymer** [comment] 2019-05-10 10:56
If this device is ready for the upcoming cycle (2019/01) (i.e. passes leak tests) then it will be used.  If not, then previously used panels (with existing VIs) will be.
I'm still trying to find out the status of the leak tests and the whereabouts of the new panel.

**Comment by davidkeymer** [comment] 2019-05-10 14:26
It's been confirmed that the panel is still undergoing another cycle of leak testing.  I will be told when the panel is ready to be connected at NIMROD and update this ticket accordingly.

**Comment by davidkeymer** [comment] 2019-06-17 12:31
The leak testing is complete, but the panel will not be moved and set up at NIMROD until the July/August shutdown.  I will be kept informed and pass on any further updates.

**Comment by kjwoodsISIS** [comment] 2019-06-17 12:41
But can we test our IOC against it _before_ it is moved to the instrument?

**Comment by FreddieAkeroyd** [comment] 2019-07-30 10:55
I have added diamond support module to out system

**Comment by kjwoodsISIS** [comment] 2019-07-30 12:13
This ticket is marked as "In Progress", but it has no assignee.  Who is progressing it?

**Comment by FreddieAkeroyd** [comment] 2019-07-30 21:48
I started it Friday and got the diamond stuff added, but then took my name off it as i had some other things to do. I also wasn't sure how extensive an IOC we needed. I've taken it out of in progress.

**Comment by Tom-Willemsen** [comment] 2019-08-05 16:25
Questions (some of these may require access to hardware to answer):
- [ ] The ticket says that NIMROD will be reading 4 pressure channels using this device, but the manual says that the device only has two channels. How many of these devices will NIMROD be using?
- [ ] What is the requirement for a "comms ok" light in the ticket above - would this not covered by our usual alarm mechanism (purple borders etc), or is there a special requirement to do something special for this gas panel in particular?

**Comment by kjwoodsISIS** [comment] 2019-08-06 07:21
The gas panel has two MKS PR4000B devices (2 devices x 2 channels each = 4 channels).
The scientists want a clear, explicit indication that IBEX is communicating with the gas panel.  They don't want to have to infer it from something else (e.g. purple borders).

**Comment by Tom-Willemsen** [comment] 2019-08-08 09:58
PRs:
- https://github.com/ISISComputingGroup/EPICS-pr4000/pull/2
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/407
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/218
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/44
- https://github.com/ISISComputingGroup/ibex_gui/pull/936

**Comment by kjwoodsISIS** [comment] 2019-08-12 11:16
Now that ticket is in review, it can be removed from the bucket.

**Closed** 2019-08-14 16:32 UTC
Labels: 2, For NIMROD migration, completed, fixed, rework
