### ISSUE TITLE
MUONFE: crash and Magnet power supplies UQ1/2 trip

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#5216] opened 2020-02-12 15:57 UTC
As a scientist, I am concerned that after an unexpected hardware crash the front end system came up and set the magnet power supplies to zero somehow.  As this affects all three instruments this is a worry.  I would like this to be investigated in case it happens again at a more critical moment and more beamtime is lost.

Details of the approximate timings are as below assembled by JL.

> Nagios “host down” report 11:24:42
Stopped updating log values (EPICS link broken), kept exact old values from between 11:18 and 11:26
Nagios “up” report 12:05:26
Slack “rebooted” report at 12:19:21, uptime was 00:14:45 so rebooted at 12:04:36
Count rate drops to very low at 12:10
Last “stale” log point of usual current from UQ1,2 at 12:10
Logged nearly zero on UQ1,2 from 12:12 (actual values UQ1=0.14A and UQ2=0.016A, varying a bit) – consistent with power being off or setpoint of zero sent
Count rate and UQ1/2 recover at 12:20

#### Acceptance Criteria
1.We have a 'post mortem' report of what happened when MUONFE went down on the 12th February 2020
1. We  **_document_**  what should happen in such an event.
   * this might require a conversation with the instrument scientists to ensure we fully understand what should happen.
1. IBEX is modified to implement the documented behaviour.
1. Tests are created to prove that IBEX behaves as documented.

#### Notes
1) Power supply to the server was lost due to another hardware failure which tripped a breaker, this was fixed and the system re-powered from a crash.
2) This may have something to do with autosave values?

**Comment by kjwoodsISIS** [comment] 2020-02-13 10:31
"Scientist are happy with the situation if the behaviour is reasonable or a ticket to produce a different behaviour is created." is not a good acceptance criterion.  It is too subjective.

The acceptance criteria need to be something that is testable - a proof that IBEX behaves in the desired (and defined) manner.  I have updated the acceptance criteria, but they are not yet ideal.  When we understand what the desired behaviour is, the acceptance criteria can be updated to something more definite.

**Comment by KathrynBaker** [comment] 2020-02-13 10:45
#1209 and the following tickets describe the desired behaviour and initial criteria, this was originally achieved by relying on autosave - covered by this ticket.
A more generic solution was suggested in #1449 when this work was first done (August 2016)

I would suggest (but have not altered) the following criteria to be achievable and suitable:
1. We have a 'post mortem' report of what happened when MUONFE went down on the 12th of February 2020

That post mortem will tell us first and foremost if we can write tests for this specific scenario, if there are any tests for the existing system, and should hopefully then highlight if the system does function as required, or if we need to reconsider and reprioritise the generic solution in #1449

We could check if the criteria have changed or not from #1209, but as is correct in the project management methodology we are employing, we have the requirements in our closed tickets.

**Comment by ChrisM-S** [comment] 2020-02-13 18:07
Some further information from JL as the hardware on these PSUs is subtly different and this may have some bearing on what happened.

> These two Danfysik 8800 supplies (unlike our other Danfysik models) have a “feature” where if the interlocks actually trip, in addition to turning the output power off it also sets the setpoint to a very small value (not quite zero). It’s possible that sending some commands such as “reset interlocks” would have the same effect, or would have the side effect of turning the power off (usually it’s already off as a result of the interlock). Could “autosave” on a PV such as IN:MUONFE:DFKPS_03:RESET, which might have been used at some point in the past when the interlocks really were off, make IBEX re-send something unfortunate?

>An “action” PV such as RESET should not really need re-sending on power up. If things are re-sent, does the IOC know to do them in a specific order so as not to confuse the hardware, and to get the desired result?

**Comment by KathrynBaker** [comment] 2020-04-30 13:18
Just to add a comment here as there was a sense of this being a daunting ticket, the post mortem needs to look at the saved records of what was sent, and check what autosave thought, and what we think happened when the system came back online - this will only ever be a best guess, but it's the kind of thing that can be done on the fly when dealing with a support query. If we know what went wrong we can write the tests (e.g. to make sure that commands get sent in the correct order - there is no point sending a setpoint to a device that is not accepting remote setpoints and then putting it into remote mode). If the issue is knowing how to check what was sent when and how, then that is a different problem, and whoever picks it up should be able to highlight the missing processes (and yes, I do still have the "introduction to performing support as part of the Experiment Controls group" on my list of tasks).

The requirements were documented in the tickets mentioned, so there may be a conversation with the ISs to make sure they haven't changed their minds. These requirements will also influence some useful tests that may not be in place and will guarantee the expected behaviour.

**Comment by DominicOram** [comment] 2020-05-01 17:41
UQ1 and UQ2 are controlled by danfysik 3 and 4 respectively. Some potentially relevant logs are, the IOC log at the time:
[DFKPS_04-20200212.log](https://github.com/ISISComputingGroup/IBEX/files/4565485/DFKPS_04-20200212.log)
[DFKPS_03-20200212.log](https://github.com/ISISComputingGroup/IBEX/files/4565486/DFKPS_03-20200212.log)

The autosave values:
[muonfe crash.zip](https://github.com/ISISComputingGroup/IBEX/files/4565500/muonfe.crash.zip)

**Comment by Tom-Willemsen** [comment] 2020-05-06 14:50
### Diagnosis
- Autosave log files from the time of the issue indicate that `AUTOONOFF` was switched **on** at the time.
- This problem is (sometimes) reproducible against the emulator with an IOC from before https://github.com/ISISComputingGroup/EPICS-ioc/pull/478 was merged if `AUTOONOFF` is enabled. I believe the issue may be a race condition between autosave reapplying saved values and the autoonoff logic in that version of the IOC.
  * Autosave logs from the time of the issue indicate that several other danfysiks were set up in a very similar way, with `AUTOONOFF` enabled, and did *not* suffer from this issue, This supports the idea of a race condition which hit some danfysiks and not others.
- The issue is no longer reproducible as far as I can tell on `master` - I believe the PR linked above has fixed the issue.

### Suggested resolution
- Add additional tests for the danfysiks explicitly testing the initialization logic as it is complicated.
  * I think this is out of scope for this ticket as it's currently very tricky to test initialization logic with the ioc test framework. I did have a look at this for a couple of hours but it is not immediately obvious. Added https://github.com/ISISComputingGroup/IBEX/issues/5412
- Add additional archiving to the danfysik which will help to diagnose these types of issue faster in future (at the moment it archives very little which makes it more difficult to diagnose these types of issues) https://github.com/ISISComputingGroup/EPICS-ioc/pull/505
- Document expected behaviour - I think this is the same as any other IOC, restarting the IOC should not affect the state of the physical device. I have tried to make this as explicit as possible at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Danfysik#initialization and linked it back to https://github.com/ISISComputingGroup/IBEX/issues/1209

Given that as far as I can tell the issue is already solved on master, I don't think anything else is required.

**Comment by KathrynBaker** [comment] 2020-05-07 10:45
AUTOONOFF certainly sounds like a good candidate from what you have said, and that behaviours are now well and truly suitable documented and highlighted.

So long as the PR is acceptable (I’ll leave that to someone who can actually build it), I’d say the business side is complete. Hopefully that feedback will allow someone unsure about the business side to be able to review the technical side and get the ticket through to complete.

**Closed** 2020-05-28 07:09 UTC
Labels: 5, completed, fixed, support
