### ISSUE TITLE
Reflectometry: Theta Invalid alarm

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#6455] opened 2021-04-29 12:02 UTC
As a reflectometry scientist, I would like alarms on beamline parameters in the reflectometry server to reflect reality. At the moment there is a bug where alarms from axes from which Theta is derived do not propagate to the Theta parameter, so it stays at INVALID on init. We should fix this as it causes concern and confusion to users.

#### Acceptance Criteria
- Theta parameter is initialised to alarm state of defining motor axis

**Comment by DominicOram** [comment] 2021-05-04 21:19
How do I reproduce this? Starting the IOC tests for the refl server do not give an invalid theta on startup

**Comment by ThomasLohnert** [comment] 2021-05-06 10:16
I see it when starting the server normally. Not sure what is different in the IOC tests

**Comment by ThomasLohnert** [comment] 2021-05-06 10:19
I have temporarily fixed this on INTER by defaulting to no alarm instead of invalid. This is pretty hacky and could technically lead to underlying errors being missed but I think in practice this case is very unlikely. I have explained this to INTER and they are happy to run with the workaround for now so we might be able to drop this in priority.

**Comment by KathrynBaker** [comment] 2021-05-20 17:03
Added support label as PR not needed for this work I'd say, although they might be handy in this case...

**Comment by DominicOram** [comment] 2021-05-21 09:11
I made a release notes PR for it, see above. If the checks are complaining it's probably because this was merged without the release notes PR being merged...

**Closed** 2021-05-26 17:10 UTC
Labels: 3, bug, completed, support
