### ISSUE TITLE
GEM: Problem with setting  LINMOT motor HGAP and VGAP

### ISSUE THREAD

**Issue by Rory-Potter-Tessella** [ISISComputingGroup/IBEX#3307] opened 2018-07-03 08:33 UTC
Arose from reviewing Ticket [#3018](https://github.com/ISISComputingGroup/IBEX/issues/3018).

I encountered a problem with trying to set the LINMOT JAWS6 motor horizontal and vertical gap. With camonitors on JAWS6:HGAP:SP and  JAWS6:VGAP:SP I observed extra values being sent to the PV and the incorrect value being set. I've attached a screenshot below. Weird behaviour highlighted in red.

![limnot_jaw_problem_anotated](https://user-images.githubusercontent.com/39518146/42208378-f927a230-7ea3-11e8-9fde-b1de480be863.png)

I could not get a consistent failure but I can make it fail given time. Both Dom and John observed me setting the JAWS through IBEX and extra values being sent to the relevant PVs. I could even make it fail after Dom removed the quadratic soft record layer, though it did fail more regularly with the quadratic layer.

I had JAWS6 set up on my own machine with relevant st.cmd files from GEM config in a single device screen in the IBEX gui. The IBEX gui was started in dev mode from Eclipse. The motors were run in RECSIM mode.

Also, changing the set points too quickly ended in crashing my machine several times and maxing out the CPU.

Both John and Dom are unclear about what caused this issue and more investigation is required.

**Comment by John-Holt-Tessella** [comment] 2018-07-05 09:21
Check that this doesn't happen on Galil too.

**Comment by kjwoodsISIS** [comment] 2018-07-05 09:23
Also, check if this issue is unique to Rory's PC.

**Comment by DominicOram** [comment] 2018-07-16 16:46
I checked this using the following python script:
```import random
import time
while(True):
	go_to = random.uniform(2,5)
	g.set_pv("TE:NDLT702:MOT:JAWS6:HGAP:SP", go_to)
	print("Going to {}, correct: {}".format(go_to, g.get_pv("TE:NDLT702:MOT:JAWS6:HGAP:SP") - go_to < 0.01))
	time.sleep(0.5)
```
I couldn't reproduce the issue and Rory cannot reproduce on his new machine. @Rory-Potter-Tessella is going to try it again on his old machine if he has time but as we haven't seen it on any instruments I'm inclined to put it down as a won't fix.

**Comment by Tom-Willemsen** [comment] 2018-07-19 08:34
I ran dom's script and couldn't reproduce the issue. If we see it again, we can open a new ticket.

**Closed** 2018-08-02 09:03 UTC
Labels: 1, completed, fixed
