### ISSUE TITLE
ZOOM: SPS Y axis stall detection

### ISSUE THREAD

**Issue by Steve-Cox-IDD-Motion** [ISISComputingGroup/IBEX#3276] opened 2018-06-19 12:20 UTC
**Problem**

A stall on this axis is not flagged and so it is not clear to the instrument scientist that something has gone wrong. The motor count position eventually drifts outside of the Galil soft limits (FL_ and BL_) and a move cannot be started until the motor count and encoder counts are aligned and zeroed at controller level. Could this be automatically reported if the scientist is running a script?

**Proposed solution**

- A message or alarm in IBEX if the the motor position value is above or bellow a certain number of counts from the encoder position value.

- As suggested previously by @FreddieAkeroyd - reset the motor step counter to match the encoder (via DP_) at the start of a move if it was out by more than a certain tolerance.

- A separate task to reduce the likelihood of a stall (IDD and IEO Motion team change hardware)

- Should the fix also be applied on other instruments?

**Comment by kjwoodsISIS** [comment] 2018-06-19 15:06
How does this ticket relate to #3164 and #2974?
Both #3164 and #2974 are marked as "impeded".  What needs to happen to get #3164 and #2974 unimpeded.

**Comment by FreddieAkeroyd** [comment] 2018-06-19 22:53
#2947 and #3164 are likely caused by the same thing, we have no encoder in the office so are unable to test a fix there. I have the changes on a branch and tried to test them in shutdown using the new small stage that Genoveva is going to use, but what I observed was not what I expected. I hope to get down there tomorrow for another go.

**Comment by Steve-Cox-IDD-Motion** [comment] 2018-06-20 10:11
We have two or three motor test boxes in the R78 lab. These units have a stepper motor, incremental encoder and three push button switches. They plug in directly to the axis connections on the front of the Galil control racks and could simulate a typical stage setup.

**Comment by KathrynBaker** [comment] 2024-12-13 13:55
Potnetially not, but the various SPSes of that nature are all in need of various bits of TLC by now. Probably worth closing this specific one.

**Closed by KathrynBaker** 2024-12-13 13:55 UTC
