### ISSUE TITLE
Log Plotter: Display full history

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4790] opened 2019-09-30 08:42 UTC
As a scientist, I want the log plotter to display the full history of a PV, so that I can understand how the value of the PV has changed over time.

#### Acceptance Criterion
1. Log plot displays full history of a PV

#### Notes
1.  This issue has been reported by several instruments.  Initially, we thought it might be related to daylight savings time, but this appears not to be the case - the problem has now been reported on OSIRIS.
2. Here is the report from OSIRIS (from Ian Silverwood):

> Hi Kevin/Freddie,
> 
> At the last IBEX SAG meeting I mentioned that occasionally the log plotter did not display 
> all the historic information. Freddie suggested this might be due to a daylight savings time 
> issue that was now sorted.
> 
> I’ve discovered it happening again on OSIRIS, and have attached a picture to show this. 
> The historic point at which the data stops does not hold any special significance that I 
> am aware of.
> 
> It’s not a huge deal, but this is useful for diagnostics and should work more reliably.
> 
> Thanks,
> 
> Ian

**Comment by kjwoodsISIS** [comment] 2019-09-30 08:43
A screenshot of the issues is attached: 
![OSIRIS_GraphStartLoss](https://user-images.githubusercontent.com/7249337/65862727-c6069400-e366-11e9-897c-13e6d1fc2c8d.png)

**Comment by Tom-Willemsen** [comment] 2019-09-30 11:52
Duplicate of https://github.com/ISISComputingGroup/IBEX/issues/4722

**Closed by Tom-Willemsen** 2019-09-30 11:52 UTC
Labels: bug, proposal
