### ISSUE TITLE
MUONS: CAEN V895 Discriminator

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4915] opened 2019-10-31 13:00 UTC
As a muon scientist, I want IBEX to support the CAEN V895 Discriminator card, so that I can use it my experiments.

#### Acceptance Criteria
1. I can set up and control the CAEN V895 Discriminator card via the IBEX GUI
1. I can set up and control the CAEN V895 Discriminator card via genie_python
1. I can load CAEN V895 Discriminator settings from file 
1. I can save CAEN V895 Discriminator settings to file 
1. I can enable/disable Test Mode
1. IBEX provides the same level of functionality as the SECI CAEN 895 VI.

#### Notes
1. The SECI CAEN 895 VI is located here: `C:\LabVIEW Modules\CAEN v895`
1. You will need to inspect the CAEN 895 VI to determine its behaviour and replicate this in an IOC & OPI.
1. The CAEN V895 appears to support up to 7 cards, each with 16 channels (that's 112 channels to read/set).
1. The source code for caentalk.exe is located [here](https://github.com/ISISNeutronMuon/ISISICP/tree/master/labview%20modules/CAEN%20v895/CaenTalk)

**Comment by KathrynBaker** [comment] 2019-10-31 13:47
Please note – the CAEN v895 is not a standard LabVIEW driver. A quick look shows that the control of the discriminator is via command prompts to Caen Talk.exe.

**Comment by kjwoodsISIS** [comment] 2019-11-05 12:13
@FreddieAkeroyd  - we spoke with the EMU scientists this morning.  They said that you knew something about the `caentalk.exe` and non-standard LabVIEW driver  - "_...something Freddie did ages ago..._".   Do you know anything about it?

**Comment by FreddieAkeroyd** [comment] 2019-11-06 10:23
The discriminators are on USB VXI connection and need to communicate via a NI DLL. The caentalk program is one i wrote that lets you set parameters via the command, the labview VI manages the parameters to set (saved as XML) and then just spawns canetalk.exe to do the actual setting. The riken instruments don't use the VI, they had so many detectors I wrote a python script that just calls caentalk.exe 

So:
* caentalk.exe could be turned into an asyn driver IOC to expose PVs to allow configuring the discriminators
* autosave could be used to record and restore values. The current vi allows them to save and restore from different settings files, this could be achieved by e.g. the configMenu option in autosave
* we need an OPI for the user to specify values

**Comment by kjwoodsISIS** [comment] 2019-11-06 11:44
Why not continue to use the same mechanism (adapted for IBEX) as used in SECI?

**Comment by FreddieAkeroyd** [comment] 2019-11-28 11:32
I don't like spawning processes if you don't need to, it also makes getting return status and values back harder as you have to process output strings etc. The XML was labview specific so that needs changing. I would propose:
* turn CaenTalk.exe into a library, with functions equivalent to the command line options current in its main()
* incorporate library into new asyn driver

I was thinking of doing this as a worked asyn driver example for anybody interested in watching

**Comment by Tom-Willemsen** [comment] 2020-01-03 11:47
Caentalk source code is available at `<private share>\data for tickets\Ticket4915\isisicp_master\labview modules\CAEN v895\CaenTalk` (for the benefit of those who can't see private repos in IsisNeutronMuon github)

**Comment by DominicOram** [comment] 2020-04-30 11:14
@ChrisColeExpControl can we have the next code chat on this? The ticket should be finished and documented before the code chat. Doing the code chat is not part of this ticket

**Comment by FreddieAkeroyd** [comment] 2020-06-24 23:07
Docs started at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/CAEN-v895

**Comment by DominicOram** [comment] 2020-07-30 16:17
I may be misunderstanding the problem here but can't we push from the blockserver using PV values? We could change the blockserver to always resend PV values on config change or make it optional in the config. It just seems odd to have a device monitor the blockserver as control everywhere else is always the other way around

**Comment by Tom-Willemsen** [comment] 2020-07-30 16:20
Yes, if we modify the blockserver to always send pv values on any config change, regardless of whether the ioc restarts or not. However I thought PV values were implemented via `dbpf` at ioc startup, so I'm not sure how easy it will be to decouple the two.

**Comment by DominicOram** [comment] 2020-07-30 16:28
From memory I think PV values try a number of methods to actually do the setting. We could probably come up with a mechanism for using `caput` when you're not restarting the IOC or even we put a flag in the config to say specific IOCs should always be restarted on config change? It also feels like this functionality should be a separate ticket given that this ticket has already taken 6 months...

**Comment by KathrynBaker** [comment] 2020-07-30 16:46
I agree that this is a new ticket, there may also be other devices that would want to resend values in certain situations so a generic solution would be a better option

**Comment by FreddieAkeroyd** [comment] 2020-07-30 17:06
PV values tried 2 mechanisms, but i think they are both IOC only. Always restarting the ioc on config change, or being able to add an external pvvalue done by blockserver on config change, would cover this situation.  I didn't like the idea of the ioc monitoring the blockserver, but it looked the most likely that could be done in time for cycle

**Comment by DominicOram** [comment] 2020-07-30 17:14
I've added https://github.com/ISISComputingGroup/IBEX/issues/5590, shall we have a quick meeting after standup tomorrow to discuss which solutions we think could be done in time?

**Comment by kjwoodsISIS** [comment] 2020-10-08 11:23
This ticket appears to have made no progress since 30 July.  How do we move it forward?

**Comment by JamesKingWork** [comment] 2020-10-15 08:59
@DominicOram did we still want a code chat on this, or was it done?

**Comment by DominicOram** [comment] 2020-10-15 11:04
I think leaving it as "a potential thing to have a code chat about" is fine. It shouldn't hold up the ticket in any way

**Comment by FreddieAkeroyd** [comment] 2020-10-16 15:36
Some PRs in #5624 That may be relevant

**Comment by JamesKingWork** [comment] 2020-10-21 08:50
Review notes:

- vmeConfigMenu:status shows failure after load even if values appear correctly in opi
- Would be best if we can have a macro to set in config.xml rather than having to declare CAENVMESIM in globals.txt (or just setting it into devsim or recsim sets the CAENVMESIM macro)
- Testing (this is scope creep so can be spun into a different ticket if we think so)
  - The C code has some logic to it we should test it with googletest
  - It would be good to have an emulator and ioctests for the device

**Comment by FreddieAkeroyd** [comment] 2020-10-22 20:51
Hmm ... the `status`  seems to be OK on EMU itself, must be an emulator issue?
```
C:\Instrument\Apps\EPICS2>caget IN:EMU:AS:CAENV895_01:vmeconfigMenu:status
IN:EMU:AS:CAENV895_01:vmeconfigMenu:status Success
```

**Comment by FreddieAkeroyd** [comment] 2020-10-22 21:06
"It would be good to have an emulator" - CAENVMESIM  is an emulator, I think it is just missing a backdoor call to check reads as part of an ioc test?

**Comment by DominicOram** [comment] 2020-11-18 15:44
Has this left https://github.com/ISISComputingGroup/EPICS-CAENV895/tree/master redundant? Can we remove the repo if so?

**Comment by FreddieAkeroyd** [comment] 2020-12-16 09:48
The existing  emulator already has a backdoor, there were just no PVs defined for reading as the hardware does not support reading. PVs now added in db that is only loaded when running in DEVSIM. 

Unable to reproduce mentioned issue with `vmeConfigMenu:status` - seems to work on my computer and EMU. The value is now checked in the IOC test.

CAENVMESIM macro is now removed and standard DEVSIM used instead

googletest code added

**Comment by FreddieAkeroyd** [comment] 2020-12-16 11:47
Just small GUI edits left (in PR buried in the `39 hidden items` above), but my CSStudio is not currently working...

**Comment by John-Holt-Tessella** [comment] 2021-01-05 12:21
... done OPI edits my CSS is working

**Comment by FreddieAkeroyd** [comment] 2021-01-06 22:49
Thank you @John-Holt-Tessella

**Closed** 2021-02-04 14:05 UTC
Labels: 1, completed, fixed, rework
