### ISSUE TITLE
NICOS: Nicos script server not working with python 3.8

### ISSUE THREAD

**Issue by RaiBishal** [ISISComputingGroup/IBEX#5351] opened 2020-03-27 09:04 UTC
After migrating from python 3.7 to python 3.8, upon sending valid python commands to Nicos script server it sends back an error `TypeError - required field "type_ignores" missing from Module`.

**Acceptance criteria:**
- [ ] Nico's server works fine with Python 3.8

**Comment by Tom-Willemsen** [comment] 2020-03-27 19:40
The following patch to NICOS code fixes this problem (probably needs wrapping in a python version check before submitting back to them):

```
--- a/nicos/services/daemon/utils.py
+++ b/nicos/services/daemon/utils.py
@@ -115,7 +115,7 @@ def splitBlocks(text):
     assert isinstance(mod, ast.Module)
     # construct an individual compilable unit for each block
     for toplevel in mod.body:
-        new_mod = ast.Module()
+        new_mod = ast.Module(type_ignores=[])
         new_mod.body = [toplevel]
         # do not change the name (2nd parameter); the controller
         # depends on that

```

Note: to reproduce the original issue you must submit a multi-line script; I was initially trying with a script like `import sys; print(sys.version)` and was confused why I couldn't reproduce this...

**Comment by FreddieAkeroyd** [comment] 2020-04-23 12:14
What is the status of this?

**Comment by Tom-Willemsen** [comment] 2020-04-23 12:21
It needs the patch above applying to NICOS. However I think only certain people have the access rights to be able to create a PR for it as it's on NICOS' gerrit, not github.

**Comment by DominicOram** [comment] 2020-04-23 14:37
I'll chase it with the NICOS team

**Comment by jkrueger1** [comment] 2020-04-23 15:27
Hi, please generate a pull request on nicos http://github.com/mlz-ictrl/nicos/. It should be transferred to the NICOS gerrit system (we hope so ;-) ).

**Comment by DominicOram** [comment] 2020-04-24 17:02
NICOS are in the process of merging this. If it's still not merged by the time we do #5389 we should point at our fork at https://github.com/ISISComputingGroup/nicos otherwise we can delete the fork.

**Comment by DominicOram** [comment] 2020-04-24 17:05
See https://forge.frm2.tum.de/review/c/frm2/nicos/nicos/+/22993 for NICOS merging this. They're happy to do the review comments themselves.

**Comment by DominicOram** [comment] 2020-04-29 07:47
https://github.com/mlz-ictrl/nicos/pull/4#issuecomment-620984471

**Comment by mr-field** [comment] 2020-04-29 13:37
I confirm that the NICOS patch has solved the problem.

The NICOS repo URL seems to have changed, so I've [updated](https://github.com/ISISComputingGroup/EPICS/commit/7604a7b95f25ae634e1a0f0a1765a84a244c7784) the submodule URL as well as its version.

**Comment by Tom-Willemsen** [comment] 2020-04-29 13:59
I'm not sure that update of submodule URL is correct, I think the github mlz-ictrl link is a mirror of the gerrit repository, and I think we should be pointing at the upstream if possible?

**Comment by DominicOram** [comment] 2020-04-29 14:30
It's a mirror that is automatically updated by the NICOS team and kept in sync. I just didn't want to touch gerrit with a barge pole

**Comment by Tom-Willemsen** [comment] 2020-04-29 14:58
Ah ok, if it automatically updates that's fine :)

**Closed** 2020-04-30 07:34 UTC
Labels: 2, completed, fixed
