### ISSUE TITLE
GUI: Script Generator Hotkey

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2012] opened 2017-02-02 15:48 UTC
The script generator hot key does not appear to work. alt + shift + g does not switch to that perspective.

**Comment by DominicOram** [comment] 2017-02-10 16:56
I cannot reproduce this bug. Can you retest?

**Comment by Tom-Willemsen** [comment] 2018-01-15 13:46
I also cannot reproduce. Closing.

**Closed by Tom-Willemsen** 2018-01-15 13:46 UTC
Labels: bug
