### ISSUE TITLE
CAEN Users: Understand how IOC seems to lose comms and fix it

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4073] opened 2019-03-05 13:37 UTC
As a CAEN user I sometimes see (especially on the mini insts using the IOC) a comms loss that requires an IOC reconnect (ctrl-x via procserv) - this can lead to data that feels out of date, and missing commands that are sent to the IOC.

**Acceptance Criteria**
1. We know why the comms losses occur
1. We have a way to resolve it that doesn't involve restarting the IOC

**Notes**
1. This has been seen on SANS2D and MUSR
1. It may be possible if the detector teams have a spare one to borrow a CAEN to try and resolve this issue
1. #3644 may be related to this
1. There is no indication that the comms has been lost - it is an awareness that values are not changing and that using the reset comms button (write ctrl-x to the procserv port) resolves the issue

**Comment by KathrynBaker** [comment] 2019-03-06 11:13
Having checked with the Detector Group, there are spare crates, and we can get in touch when we are ready to do the work and we can get one set up to test with.

**Comment by FreddieAkeroyd** [comment] 2019-03-06 17:47
I have added a   $(P):EVNTO_T1:COUNT   PV as a heartbeat, it should always be increasing. Also fixed a few places that may hang the scanner, but not sure. We can get more diagnostics by typing at the IOC console

 HVCAENx527Debug 10

**Comment by KathrynBaker** [comment] 2019-03-08 15:28
As a crate has been made available @FreddieAkeroyd and @KathrynBaker are running IOCs (the one which has been altered, and one close to what should be on the instruments respectively), and @KathrynBaker is running the MUSR VI setup to read the test crate that is available, to see if we lose the comms and if we do to see if we can find any indication as to the fault.

As the crate was made available, we decided to make use of the opportunity - so will move this ticket into in progress, pointing it at 3.

**Comment by FreddieAkeroyd** [comment] 2019-03-10 14:54
Main changes:
* PV   EVNTO_T1:UPDATING   to show poling loop still active
* better locking of access to crate structures
* reconnect on all crate errors not just timeout
* now raises alarms on read or write error
* simulation mode will now randomly disconnect and reconnect, so allowing checking of alarms

**Comment by KathrynBaker** [comment] 2019-03-25 17:53
Was unable to reproduce the loss of comms when running for a week.
If this is an error relating to running a mini-inst rather than a full server, the recent changes to raise alarms and to automatically restart the IOC when the LabVIEW wrapper is started (so every config change/start of SECI) may be enough to ensure adequate running.
Whilst work has been undertaken, can the acceptance criteria be fulfilled, as so far the error cannot be reproduced?

**Comment by FreddieAkeroyd** [comment] 2019-03-25 19:06
The IOC has been running on MUSR since 13/3, it should log any issue and nothing has been reported for nearly 2 weeks. Is this something they turn off once cycle ends or can we leave it running into shutdown? Is the VI on MUSR still working OK?

**Comment by KathrynBaker** [comment] 2019-03-27 10:51
The VI on MUSR is currently working fine

**Comment by FreddieAkeroyd** [comment] 2019-03-27 13:06
So does this mean the issue is/was likely in labview/caLab then?

**Comment by KathrynBaker** [comment] 2019-03-27 14:49
My instinct is that it may well have been, or that the specific crate is odd. The DETMON work is likely to help answer that.

**Comment by FreddieAkeroyd** [comment] 2019-03-27 21:32
The HVCAEN IOC hasn't been restarted since 13th March, however it did log a message this morning

[2019-03-27 11:07:49] Lost connection to hv0@130.246.52.115: Operating System Error: 10054 (3)
[2019-03-27 11:08:05] Regained connection to hv0@130.246.52.115

I think the original IOC code only expected and handled timeout errors, so such an error could have been enough to stop the original IOC from working. Are you aware of anything on MUSR happening at that time?

**Comment by KathrynBaker** [comment] 2019-03-28 13:42
I'm not aware of anything at that time, it's a little before I called them I think to check on the VI. So I think that was a random instance, and that it was enough to keep the system running. Whilst this doesn't fulfil the acceptance criteria, we still do not know the cause, reconnection no longer requires manual intervention which is an improvement.

**Comment by FreddieAkeroyd** [comment] 2019-03-29 10:59
Winsock error code 10054 is "connection reset" so i think "operating system error" must mean an error returned by the windows operating system rather than e.g. linux on the CAEN. So it would look like a break in network connection either at the caen end itself or due to something inbetween. The only way we could try and reproduce it would be to get Davide to temporarily pull out a network cable to his test crate and see if that caused the old IOC code an issue. Or we could pull the cable out of the MUSR one ourselves during shutdown.

**Comment by FreddieAkeroyd** [comment] 2019-07-05 15:04
Looks to be running OK so closing this

**Closed by FreddieAkeroyd** 2019-07-05 15:04 UTC
Labels: 0.5, ready, rework, support
