### ISSUE TITLE
Blockserver: Commit other files to repo

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2035] opened 2017-02-07 15:07 UTC
At the moment the repository for settings does not include code or motor settings, etc. Should it contain this and when should it be updated? Once known implement this.

**Comment by AdrianPotter** [comment] 2017-03-30 09:20
Duplicate of #2134

**Comment by AdrianPotter** [comment] 2017-03-30 09:22
We may finish this ticket as part of the backlog preparation. This ticket asks should we do it, #2134 is the implementation ticket. If we decide to include #2134 in the sprint then the work of this ticket is done.

**Comment by AdrianPotter** [comment] 2017-03-31 14:09
Decided to do #2134. Closing ticket

**Closed** 2017-04-06 10:44 UTC
Labels: 0, completed
