### ISSUE TITLE
Web: Make sure instrument pages are corect

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2688] opened 2017-10-16 09:54 UTC
As an instrument scientist, I would like the link to the web dashboard on my instrument page to point to the correct page if I have switched to IBEX so that users visiting my webpage can navigate to the correct page of the web dashboard.

**Comment by DominicOram** [comment] 2018-07-18 08:57
Duplicate of #3048

**Closed by DominicOram** 2018-07-18 08:57 UTC
Labels: duplicate
