### ISSUE TITLE
Jaws OPI: Lag when changing vgap [time box 1d]

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#3764] opened 2018-11-14 16:18 UTC
When changing the value for vertical gap in the Jaws OPI, it starts to lag (redraws every few seconds instead of milliseconds). Other open OPIs seem to start to lag too. Initially reported by INES, and I have also observed this on CRISP and dev machines.

The motors still move correctly, but this makes the OPI frustrating to use.

**Comment by kjwoodsISIS** [comment] 2018-11-14 16:34
Is this related to either #3463 or #3656?

**Comment by DominicOram** [comment] 2019-02-04 12:04
Can you add some more instructions on how to reproduce? I've tried using a standard jawset on top of a simulated galil on both my dev machine and demo, both seem fine.

**Comment by John-Holt-Tessella** [comment] 2019-02-04 16:20
Hmmm, on crisp they were not. You may need to move the jaws. @ThomasLohnert seem to know. Maybe look at CRISP.

**Comment by aaron-long** [comment] 2019-02-11 12:03
I was unable to reproduce this on my dev machine too. Will have to test on CRISP as per John's instructions.

**Comment by John-Holt-Tessella** [comment] 2019-02-28 16:20
Can't reproduce won't fix (at sprint review)

**Comment by DominicOram** [comment] 2019-03-08 15:25
I reproduced this when reviewing https://github.com/ISISComputingGroup/IBEX/issues/4081. It seems that the load of having both a jaws OPI and reflectometry OPI open killed the performance of the GUI. Hopefully fixed now.

**Comment by aaron-long** [comment] 2019-03-11 11:49
Issue resolved: https://github.com/ISISComputingGroup/ibex_gui/pull/866

**Closed** 2019-03-28 13:34 UTC
Labels: 1, bug, completed, fixed
