### ISSUE TITLE
GUI: Log plotter to show archived values when added from OPI

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2177] opened 2017-03-10 15:34 UTC
As a scientist using the GUI from my office I want to be able to view archived log plotter data after right clicking on an OPI. This doesn't work because the archived data is stored under `<PVName>.VAL`. The solution is to append `.VAL` on right click add to log plotter; if a field is not already specified. NB this is not the case for blocks which are archived without the `.VAL`.

**Comment by DominicOram** [comment] 2017-03-16 16:46
I suspect that the OpenLogPlotterPopup.java class is hooked into the right-click menu of an OPI so that we switch perspective when we plot a PV. At this point we should also try and change the PV to add the VAL

**Comment by DominicOram** [comment] 2017-05-04 17:41
Duplicate of #2261

**Comment by John-Holt-Tessella** [comment] 2018-04-20 13:05
+1 Electronics

**Comment by DominicOram** [comment] 2021-02-15 11:25
Added as changes in https://github.com/ISISComputingGroup/IBEX/issues/6233 made this trivial

**Closed** 2021-03-04 08:57 UTC
Labels: 1, added during sprint, completed, fixed
