### ISSUE TITLE
Run control icon remains visible

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5563] opened 2020-07-21 11:41 UTC
During the system testing it was found that when run control was enabled/disabled on blocks the icon in the GUI remained visible even if it was disabled. @JamesKingWork to look into and provide more info

**Comment by JamesKingWork** [comment] 2020-07-21 12:47
Closing as cannot reproduce

**Closed by JamesKingWork** 2020-07-21 12:47 UTC
Labels: for release, in progress
