### ISSUE TITLE
CLIENT: Diagnose cause of runaway handle leak on Java VM

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#4472] opened 2019-06-28 13:27 UTC
As a _developer_ I would like to know why the IBEX Client (an .exe JVM) might have requested an excessive number of Windows "Handles" (resulting in memory exhaustion on the host system) during two short periods this cycle.  This behaviour resulted in complete loss of the control computer.  As a _scientist_ I would like to ensure that this behaviour cannot happen again as the remedy (having to reset the VM) resulted in disk corruption and (possibly?) loss of significant beam time for the experiment.

### Acceptance Criteria
   1) It is possible to identify what part of the Java code went "wild" and why.
   2) It is also possible to detect in Nagios when this has happened to allow early remedial action to avoid loss of beam time.

### Notes
  1) The details of the incident are described in controls ticket [#626](https://github.com/ISISComputingGroup/ControlsWork/issues/626)
  2) Handles may be allocated in windows for several different types of object and it is not clear currently which type was being exhausted.
  3) Analysing the current handle types and numbers in a normally working IBEX client with Windbg might be a fruitful way to get an idea of how java objects map on to similar windows objects (useful information is available [here](https://blogs.technet.microsoft.com/yongrhee/2011/12/19/how-to-troubleshoot-a-handle-leak/)).
  4) It would be useful to engage any Java logging options which might spot what is found in (3)

**Comment by kjwoodsISIS** [comment] 2019-07-11 14:20
See NICOS tckets relating to IMAT

**Comment by Tom-Willemsen** [comment] 2019-07-18 08:35
I believe this ticket is essentially a duplicate of https://github.com/ISISComputingGroup/IBEX/issues/4513 and the underlying cause will be addressed in https://github.com/ISISComputingGroup/IBEX/issues/4511 . I do not think this ticket is necessary any more.

**Comment by kjwoodsISIS** [comment] 2019-07-18 09:57
Done in #4513.  Close this ticket.

**Closed** 2019-07-18 09:57 UTC
Labels: bug, wontfix
