### ISSUE TITLE
File Watcher error when deleting synoptic

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1518] opened 2016-08-26 13:28 UTC
When deleting a synoptic, the blockserver log has the following errors, even though the synoptic seems to be deleted correctly:

[Fri Aug 26 14:26:32 2016] MAJOR: File Watcher: [Errno 2] No such file or directory: u'C:\Instrument\Settings\config\NDW1298\configurations\synoptics\syno1.xml'
[Fri Aug 26 14:26:32 2016] MAJOR: File Watcher: Recovered C:\Instrument\Settings\config\NDW1298\configurations\synoptics\syno1.xml, please delete via client

These errors are displayed in the IOC log in the GUI, and may be confusing to the user if everything is actually fine

**Comment by kjwoodsISIS** [comment] 2016-09-01 16:02
See also #1500 (this might be the cause of the seemingly odd behaviour of the FileWatcher)

**Comment by AdrianPotter** [comment] 2016-10-17 14:36
Unfortunately not resolved by #1500

**Comment by AdrianPotter** [comment] 2016-10-18 15:41
Now fixed, but needs #1500 to be merged first

**Comment by AdrianPotter** [comment] 2016-10-27 15:14
https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/90

**Closed** 2016-11-02 17:24 UTC
Labels: 1, bug, completed, fixed, question, rework
