### ISSUE TITLE
RBNumber/Users: All users should be added when an RB Number is set

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2827] opened 2017-12-12 16:54 UTC
As an Merlin experimental scientist I have noticed that if I set an RB number not all users from that experiment are added to Users on the dashboard; they should be.
For Helen it added only the PI and the contact for me it only added the PI. I think it is probably missing the last person.

**Comment by AdrianPotter** [comment] 2018-01-02 13:44
Replicated locally. The default repo has two users, "Dr Test Testerson" and "Mrs localfirst Local" who are assigned to experiment 1234567. Settings this RB number results in the title "Testerson". Inspecting the PV `[PREFIX]:ED:SURNAME` directly yields `["Testerson"]` so it appears the experimental database is missing the 2nd user

**Comment by AdrianPotter** [comment] 2018-01-02 14:21
From `inst_servers\DatabaseServer\exp_data.py`:

```
if not role == "Contact":
    surnames.append(self._get_surname_from_fullname(fullname))
```

Contacts are explicitly excluded from the dashboard. Having spoken to @KathrynBaker, this was the expected behaviour originally defined by users. I will mark this as won't fix and inform Helen and Adroja

**Comment by AdrianPotter** [comment] 2018-01-02 14:24
I've updated the user manual with a note about the behaviour:

https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Dashboard

**Comment by AdrianPotter** [comment] 2018-01-02 14:32
Note from discussion that a person can have multiple roles in the `experimentteams` table of the db. The GUI only expects people to have one role each. A person (whether by design or accident) is given the highest role in the db (i.e. PI, user, contact in order of precedence)

**Comment by ChrisM-S** [comment] 2018-01-02 14:39
Just a comment but it seems slightly weird that the person you might need to contact about the experiment is not visible on the dashboard – if the cryostat is gushing clouds of liquid nitrogen and there is no one in the cabin who you gonna phone?

**Comment by AdrianPotter** [comment] 2018-01-02 14:39
The contact is listed on the experiment details page, just not on the main IBEX dashboard

**Comment by AdrianPotter** [comment] 2018-01-02 14:42
I've emailed Adroja and Helen explaining the findings. If they're happy with the explanation, I'll close the ticket. If not, I'll raise a follow up to investigate how the behaviour might be changed, given that it would be breaking explicitly requested functionality from someone else.

**Comment by KathrynBaker** [comment] 2018-01-02 14:43
This is also the list of surnames only, so would you care to guess which surname in a list is the contact? Please note, we can change the behaviour of the database to list all roles, but we were explicitly asked to list people according to the hierarchy specified, and to not include contacts in the surnames list (which is what is recorded in the nexus file via the ICP) as a contact is not necessarily part of an experiment team (the memory has provided more information as time passed….)

Regards,
Kathryn

**Comment by AdrianPotter** [comment] 2018-01-03 08:57
Adroja confirms they are happy with the existing behaviour

**Closed** 2018-01-18 08:26 UTC
Labels: bug, completed, wontfix
