### ISSUE TITLE
Move more build utilities to ICP_Binaries share

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5180] opened 2020-02-06 15:18 UTC
CMake has already been moved #5171 I believe there are other candidates that can be run from an unzipped central directory too: 

* maven
* perl
* wix
* OpenJDK

This would keep developers and build servers more in step

**Comment by DominicOram** [comment] 2020-02-10 11:18
Duplicate of #5177 but this one also has openJDK. Other ticket already has acceptance criteria so will add openJDK to other ticket and close this as duplicate.

**Closed** 2020-02-10 11:19 UTC
Labels: duplicate
