### ISSUE TITLE
LARMOR: Bench limits drift

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2184] opened 2017-03-15 15:21 UTC
We got this email from Rob:

>
> From: Dalgliesh, Robert (STFC,RAL,ISIS) 
> Sent: 14 March 2017 22:00
> To: Howells, Gareth (STFC,RAL,ISIS); Akeroyd, Freddie (STFC,RAL,ISIS); Woods, Kevin (Tessella,RAL,ISIS)
> Cc: Washington, Adam (STFC,RAL,ISIS); Nilsen, Goran (STFC,RAL,ISIS); Stewart, Ross (STFC,RAL,ISIS)
> Subject: Larmor bench limits
> 
> Hi,
> We have been seeing some very odd problems with the Larmor rotating bench over the past couple of days.
> 
> The limit of the bench seems to not be functioning properly and keeps changing.
> After determining a safe limit on Monday I set this in EPICS. However, once we tried to move back to the limit it turned out that we had to add 36deg. To this number to make it work.
> Again today we moved to this limit and found that we had to add a further r2 degrees to the limit.
> The bench itself seems to be moving reproducibly but this limit behaviour is both very odd and has wasted about 4 hours of beam time to date.
> 
> Gareth seems to think that it might be a similar problem to the ones seen on IMAT.
> 
> Rob
> 

Having investigated, it doesn't seem related to  #2180. I note that in the GALIL_07 logs there is the message:

>[2017-03-15 12:49:30] sevr=info Poll services: MOTOR HOMED C
>
>[2017-03-15 12:49:30] sevr=info Poll services: applying motor C raw home position 257003
>
>[2017-03-15 12:49:30] sevr=info Poll services: applying encoder C raw home position 321254
>
>[2017-03-15 12:49:32] Poll services: MOTOR OFF C

I wonder if the homing is causing the drift, though can offer no explanation as to why this might be occurring now and not previously.

@kjwoodsISIS  has asked for more information from Rob about the context under which this problem occurred.

**Comment by kjwoodsISIS** [comment] 2017-03-15 15:25
Rob first noticed the problem on Monday (13th March) and again on Tuesday (14th).  Is there anything in the logs on these days that might point to the problem?

**Comment by AdrianPotter** [comment] 2017-03-15 15:26
Do you know which Galil the problem is on?

**Comment by AdrianPotter** [comment] 2017-03-15 15:35
Rotating bench is `MOT:MTR0401`

**Comment by AdrianPotter** [comment] 2017-03-15 15:41
There a number of messages of the form

>[2017-03-15 11:08:25] GalilAxis::beginMotion:GalilController::writeReadController:BGA:2010 COMMAND ERROR.  Galil::command("BGA") got ? instead of : response.  TC1 returned "22 Begin not possible due to limit switch"
>
>[2017-03-15 11:08:25] sevr=major BGA: 22 Begin not possible due to limit switch

But that might be the Galil ignoring a request to move beyond its limit switch. I don't see any smoking guns, but I'm not so familiar with what constitutes 'normal' Galil output.

**Comment by AdrianPotter** [comment] 2017-03-15 15:48
The above message seems pretty common throughout the logs so is unlikely to be the culprit.

**Comment by AdrianPotter** [comment] 2017-03-15 15:51
Autosave files indicate only the high limit (MOT:MTR0401.DHLM) has been changed since 6th March so I don't see any problems there.

**Comment by AdrianPotter** [comment] 2017-03-15 15:52
This may need someone to go down to Larmor to examine the problem in person.

**Comment by GDH-ISIS** [comment] 2017-03-24 15:25
In relation to limits not being applied correctly, I do not believe the limits for a Galil motor are the problem. The issue is more refined - the Galil does not know where the motor is. I have confirmed this on ALF using LabVIEW as a diagnostic. If an encoder is defined and operational, the motor must be told where it is before the move is actioned. This is already done in the LabVIEW driver. This issue is amplified much more when an offset is present on an axis, particularly with an absolute encoder (as on IMAT and ZOOM).

**Comment by kjwoodsISIS** [comment] 2017-03-24 15:50
Bring this forward into Sprint 2017_03_09.
Whoever takes this ticket on needs to sit down with @GDH-ISIS and determine what the LabVIEW code (for Galils) is doing that IBEX is not.  The solution then needs to be documented in the Wiki, so that we don't fall foul of this issue in future.

**Comment by John-Holt-Tessella** [comment] 2017-06-23 08:34
@GDH-ISIS is going to try this on ALF to see if he can repoduce the issue

**Comment by John-Holt-Tessella** [comment] 2017-06-26 12:40
OK Rob is fairly definite on the cause of this. He says that if your axis has an offset and it is homed then the offset is reapplied every time it is homed. This makes it drift slowly.

**Comment by GDH-ISIS** [comment] 2017-06-26 23:52
Pretty sure this file has something to do with it all - roughly line 1350 : 
case MOTOR_HOMED://Retrieve needed params
..\EPICS\support\galil\master\GalilSup\src\GalilAxis.cpp
Need to work out what dirm refers to in particular.

**Comment by John-Holt-Tessella** [comment] 2017-06-27 08:08
Also see #2313 for dummy homing routine which may allow testing.

**Comment by FreddieAkeroyd** [comment] 2017-06-27 10:23
Ok, dirm should be synced to the value used in the motor record, it is done so via a separate closed_loop DB record

**Comment by FreddieAkeroyd** [comment] 2017-06-27 10:56
[home5.txt](https://github.com/ISISComputingGroup/IBEX/files/1105026/home5.txt)

Galil 5 homing over time, I note for example

GALIL_05-20161216.log:[2016-12-16 11:48:12] sevr=info Poll services: applying motor G raw home position -762000
GALIL_05-20161216.log:[2016-12-16 11:48:12] sevr=info Poll services: applying encoder G raw home position -190500
GALIL_05-20170331.log:[2017-03-31 10:51:24] sevr=info Poll services: applying motor G raw home position -766000
GALIL_05-20170331.log:[2017-03-31 10:51:24] sevr=info Poll services: applying encoder G raw home position -191500

So a difference of 4000 motor / 1000 encoder - homeval has remained unchanged according to autosave, the offset has changed from 8.5 in December to 9.5 in march which correlates with the 1000

**Comment by GDH-ISIS** [comment] 2017-06-27 11:40
Not sure on the calculation here - I can not quite make sense of it. Clearly I could be wrong of course, but at the risk of making myself look a fool ....
1) The Galil ioc has one home value and one homing routine (not sure about other facilities)
2) I think (1) would make the home value direction independent (if you were inverting the axis - that is different and needs a sign to be considered).
3) I would have thought homeval would include the offset. It does not make sense for it not to with a readback.
4) In calculating the encoder and motor values, there is an IF statement checking whether (homeval != 0.0000). I'm not sure I follow the reason why - the offset would still need to be considered when setting the motor and encoder values if the homeval was zero.
I would just remove dirm and the IF statement (4) - leave the calculation in place - and try again. An additional check probably needs to be included to see whether the axis has been inverted - which I think is held in the motor record.
Currently can not check as I think there is a problem communicating with the Galil.

**Comment by FreddieAkeroyd** [comment] 2017-06-27 15:11
The homeval looks to be applied in user coordinates, userVAL = raw * res * DIR + OFFset  with userVal being the homeval. If DIR is not the same in when the IOC defines position and when the motor record back calculates it, then I think you'd get a shift of twice the homeval in the readback? If homeval is zero it looks like this is treated as a special case, Rob has axes with both zero and non-zero homevals, he said he though all axes were drifting, but maybe that is not the case. I believe DIR is being propogated correctly though.

**Comment by FreddieAkeroyd** [comment] 2017-06-28 09:36
Currently homing with a  homeval != 0 will re-assert the homeval in user coordinates, so if homeval is 10 and Rob decides to apply an offset of .1 to make the readback 10.1, then next time he homes it will go back to 10 and he'll need to increase the offset of 0.2 to get 10.1 He said he was currently setting the offset back to 0 before he homed, which would be consistent with this behaviour. If homeval is zero the Galil driver ignores the offset when doing DP/DE, so the user offset is then what you want the home position to look like in user space. Maybe this is a better way to do home positions than using homeval? Or to make homeval in dial coordinates (i.e. minus any offset) so a user can apply an offset, though is this confusing that homeval isn't homeval? homeval will be 0.0 if unspecified, so i can see the reasoning for ignoring the offset in this case in the galil driver,

**Comment by FreddieAkeroyd** [comment] 2017-07-03 09:20
Rob has confirmed this series of events
--

Hi Rob,

Would this describe your situation:

Home bench – it stops at a position of 30.0 say.
This isn’t the appropriate value, so you add an offset of 0.1 so it now reads 30.1
Later you home bench again – it comes back at 30.0 despite  the offset of 0.1
To get 30.1 back you now need to increase the offset to 0.2
The only way to avoid an ever increasing offset is to set it to 0.0 before homing

The axes can have a “home value” (the 30.0) associated with them, it seems this is applied in user rather than dial coordinates and so will include/absorb any offset. However if the “home value” is 0 (unset) it is applied in raw/dial coordinates and so the offset is preserved and in fact the offset becomes the user readback at the home position
     
Regards,

Freddie

**Comment by John-Holt-Tessella** [comment] 2017-07-03 13:25
The behaviour has now be confirmed on Demo. Use the dummy homing routines;

 - Turn off Jog After Home (because it is confusing). `caput TE:NDW1798:MOT:MTR0101_JAHV_SP 0`
 - Set a `TE:NDW1798:MOT:MTR0101_HOMEVAL_SP` to a value, `x`. 
 - Home 
 - The value set is as above, `x`
 - Set an offset (value is now `x` + offset)
 - Home
 - Value is `x` but the offset is still set

Alternate behaviour:

 - Set a `TE:NDW1798:MOT:MTR0101_HOMEVAL_SP` to 0. 
 - Home 
 - The value set is 0
 - Set an offset (value is now offset)
 - Home
 - Value is offset

It is not clear what the correct behaviour is here. Should the homeval be the value when a home is done or should the offset (which is an EPICS thing) be included.

The options for resolving this ticket are:

 1. For ISIS offset is always 0 (this allow lab view and epics to show the same values)
 1. At ISIS homeval is always 0
 1. Allow the users to set both homeval and offset but show a Galil OPI so they can more easily see the interplay between homeval and offset
 1. Create a dhomeval (dial home value) this would be the home value without an offset
 1. When a offset is added the homeval is updated to include the offset. When homeval is set the offset is set to 0.
 1. Change the meaning of the current offset to be the same as DHomeVal

Discussion with users need to take place to verify what behaviour is needed.

**Comment by John-Holt-Tessella** [comment] 2017-07-03 13:26
Impeded while @FreddieAkeroyd discusses with Galil author.

NB this is not effected by update to Galil drivers.

**Comment by FreddieAkeroyd** [comment] 2017-07-10 14:16
Having exchanged a few emails with Mark Clift (Galil driver author), we are coming to the conclusion that dial coordinates for HOMEVAL is the best approach. This does mean that if an OFF is set then the readback at the home position will be "HOMEVAL  + OFF" rather than "HOMEVAL", but it does avoid the situation we currently have of an OFF being gobbled up by the homeval logic and so creating a perceived "drift". Are we happy with this?

**Comment by John-Holt-Tessella** [comment] 2017-07-11 12:22
OK final decision is to set HOMEVAL=0 for all cases and use the offset to mange differences between dial and user coordinates.
The acceptance criteria are:

 1. All homevals are set to 0 on all instruments. This means:
        1. Home val = 0
        1. Offset needs setting
        1. Limits need adjusting
1. A new OPI linked from out motor summary page which allows users to set the offset without all the extra detail.

**Comment by FreddieAkeroyd** [comment] 2017-07-11 12:31
This is consistent with HOMEVAL being in DIAL coordinates and a HOMEVAL of 0 currently has this behaviour with the existing driver

**Comment by John-Holt-Tessella** [comment] 2017-07-20 15:54
see #2471 is this now done?

**Comment by FreddieAkeroyd** [comment] 2017-07-21 13:15
I think homeval=0 solves the problem, moving to review

**Closed** 2017-07-27 08:03 UTC
Labels: 2, bug, fixed
