### ISSUE TITLE
Maclennan homing

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3076] opened 2018-03-29 10:57 UTC
Reported by IRIS: after homing, the McLennan does not set a home position and they have to define the current position to 0 manually. The homing.st needs to be updated to set a home position of 0

**Comment by AdrianPotter** [comment] 2018-05-03 08:30
This is a duplicate of #3077

**Closed** 2018-05-04 08:56 UTC
Labels: completed, duplicate, wontfix
