### ISSUE TITLE
GUI: Unexpectedly grey menu items

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#3001] opened 2018-02-28 17:23 UTC
When demoing to ZOOM some of the synoptic buttons were greyed out when they shouldn't be - e.g. the new synoptic button. Starting a new client allowed us to demo, but the situation was incorrect.

John did mention having seen something similar with the configuration menu items at some point.

We need to try and reproduce this, and then consider if a fix can be found.

**Comment by John-Holt-Tessella** [comment] 2018-03-09 16:43
See also Configurations Edit.. Current.. Configurations New.

It may effect all items that depend on PVs. Probably a sync bug between am I connected and can I write to it.

**Comment by KathrynBaker** [comment] 2018-03-09 16:48
This may also be related to an issue on IMAT where the motor table greyed out, possibly, I guess, depending on the root cause...

**Comment by Tom-Willemsen** [comment] 2018-03-15 11:53
See https://github.com/ISISComputingGroup/ibex_gui/pull/598/files for the fix of the DAE buttons being greyed out, which sounds quite similar to this issue.

**Comment by Tom-Willemsen** [comment] 2018-03-22 16:51
This does not appear to be a GUI synchronization bug this time, just slow PV reconnections.

There is a ladder of PV connection times described in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/PV-Connection-Layer , essentially this means that PVs may take up to 2 minutes to reconnect.

I did manage to reproduce this bug (in a non-persistent way) by doing the following:
- Open a GUI without blockserver running
- Leave the GUI for a few minutes
- Start the blockserver
- About 10% of the time, some menu items will come back before others (this is the bug described in the ticket)
- Eventually all PVs will reconnect and the state will be as expected.

We already have a ticket for slow PV connections ( https://github.com/ISISComputingGroup/IBEX/issues/2224 ) but we know that this is a hard issue so I won't do it as part of this ticket.

Because all items do eventually reach the correct state, I'm marking this as wontfix.

**Comment by Tom-Willemsen** [comment] 2018-03-23 11:36
After discussion with John and Kathryn, I have added some configurable logging to the GUI. We will try turning this on for one or two beamlines (ZOOM perhaps?) and see whether it tells us anything useful.

**Comment by KathrynBaker** [comment] 2018-03-23 14:52
Zoom have said yes to doing this logging for the cycle.

As discussed we should probably run the logging on a couple of other instruments as well, at least for short periods to get a cross section of behaviour, but with ZOOM we can get a long time example.

**Closed** 2018-04-12 10:48 UTC
Labels: 2, bug, completed, fixed
