### ISSUE TITLE
Synoptics: Custom OPI icons

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2591] opened 2017-09-13 10:31 UTC
Requested by James Lord

As a user, I would like to be able to add my own icons for synoptic components so that I can pick an icon most relevant to the purpose of the component.

The example given is that, say you have a PSU for a magnet. We could give the PSU a symbol for power (a lightning bolt I think?). However, it would be more instructive to users if the icon was for what the PSU actually controlled (e.g. a magnet). 

If we don't want users to have free reign on supplying icons, we could let them select from an icon library if they didn't like the default one assigned.

**Comment by KathrynBaker** [comment] 2017-09-13 10:56
Duplicate of #2445?

**Comment by DominicOram** [comment] 2017-09-13 16:44
Giving users complete free reign would mean that other clients could not understand your created synoptics as icons are saved client side.

**Comment by kjwoodsISIS** [comment] 2017-09-14 10:20
I am not entirely convinced by James's argument.  Magnets are not so much controlled as powered by PSUs.  The magnet itself is not directly under control.  It is the PSU that is under control.  What's more, PSUs can control more than just magnets.  And Eurotherms can control both cryostats & furnaces.

In my view, the icon should represent what the item under control actually does.  As a compromise, it might be worth having an icon with two symbols (e.g. a lightning bolt and a magnet).

I agree with Dom, we should not give users free rein to create their own icons (otherwise we'll have 30+ different sets of icons and no design consistency).  Instead, we should expand our library of designs.

**Comment by KathrynBaker** [comment] 2024-11-04 22:48
Closing as a duplicate of 2581

**Closed by KathrynBaker** 2024-11-04 22:48 UTC
