### ISSUE TITLE
IBEX: Start/stop IOC dialog inexplicably blank

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1346] opened 2016-06-30 08:14 UTC
When opening the start/stop IOC dialog in IBEX, the list of IOCs can remain blank for a good 20s whilst populating. This is very disconcerting for the user.

As as user, I would like an indicator that the list is waiting for members so that I'm reassured that something is happening in the background.

**Comment by AdrianPotter** [comment] 2016-06-30 08:23
Note that I just did this on NDXDEMO with Julabos 1 & 2 running and it took about 5 minutes to load the IOC list. To me this qualifies as a bug, rather than a usability enhancement.

**Comment by kjwoodsISIS** [comment] 2016-06-30 08:54
I think it would be good to understand why some IOCs are so slow to start up.  It may be that a change in a setting could significantly alter the performance.

**Comment by AdrianPotter** [comment] 2017-01-06 10:37
I have not seen this issue again for some time. We applied a lot of block server fixes since it was reported so I suspect it may have been fixed. If nobody else can reproduce it, then I think we can say it's fixed.

**Comment by Tom-Willemsen** [comment] 2017-01-10 08:48
Tested on DEMO and local instrument this morning, could not reproduce this issue, even with multple IOCs including Jubalos open. 

I haven't seen this issue recently either, so marking it as complete.

**Closed** 2017-01-11 16:22 UTC
Labels: bug, completed, fixed, story
