### ISSUE TITLE
ZOOM: Monitor Detector Temperatures

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1844] opened 2016-11-22 17:49 UTC
A request has come through, via the design teams, that the detector temperatures (in the air, inside the vacuum tank) be monitored and recorded for ZOOM, this should be separate to the main instrument system, but is not a critical system.

This is an overall task to cover two others, as they are distinct, but need to be considered together they are:
Creating a server for the monitoring (#1842) and creating the IOC for the monitoring (#1843)

**Comment by kjwoodsISIS** [comment] 2016-11-23 09:26
What temperatures are being measured here?  I interpret the description to mean that the temperature of each individual detector is being measured, with some detectors being in air , others being in the vacuum tank.  Is that correct?
How many detectors are there?  Is the number of detectors likely to change over time?  Will users want a graphical display of the temperatures?

**Comment by KathrynBaker** [comment] 2016-11-23 13:08
I’m not entirely sure. The detectors are actually in air, but it is a pocket within a vacuum system. There are a number of sensors shared by the detectors.

**Comment by ChrisM-S** [comment] 2016-11-23 16:21
Ah, I can see that if they are in an air pocket in a vacuum (possibly with limited cooling) they are going to be worried about the risk of overheating at worst and detector stability changes caused by warming at least.

**Comment by KathrynBaker** [comment] 2016-11-29 16:34
Have had a brief conversation with Liam and Nigel at a Zoom angineering meeting, and Nigel is certainly keen to get some information relating to these values, certainly when there is an extreme alteration in the temperature (and would appreciate similar readings for SANS2D). The option that had been mentioned for Nagios is a good one for providing warnings to the appropriate people, the alarm values may need to alter over time, once there is a better feel, but anything over 35 Celsius seemed to be a good starting point from the discussion I had. Nigel also implied that there may, in the future, be other values that need reading in a similar way for the detectors team relating to things such as fields, and that some discussion is already going with Tom. We may want to keep that in mind as we enact this solution, but so long as we can run the NanoDac IOC somewhere, then the Nagios monitoring is likely to be a good option for the monitoring and alarming. There is a blower on the detectors, but the amplifiers are likely to be unhappy if that fails.

**Comment by ChrisM-S** [comment] 2016-11-29 17:46
Interesting, it sounds a bit similar to the way we monitor our server temperatures with nagios.  I find the Nagios plots very useful over longer periods (e.g. yearly temperature variation).  I’m not sure how easy it is to extract the data from Nagios if you want to use it somewhere else – but I haven’t really had a need to yet.

Would the scientists be needing to look at Nagios if we did it this way, or do you think it is more for the instrumentation groups use?

**Comment by KathrynBaker** [comment] 2016-11-30 09:53
The server temperatures are also passed to detectors I believe, this was the example given by Nigel. This information is for the instrumentation groups, the scientists aren’t overly interested, if they are, then so long as we have PVs somewhere then they can always create a block to view it.

**Comment by DominicOram** [comment] 2017-06-27 12:58
@KathrynBaker is this a duplicate of https://github.com/ISISComputingGroup/IBEX/issues/1842?

**Comment by KathrynBaker** [comment] 2017-06-27 15:15
Nope, 1842 is an umbrella ticket, this is a portion of it, completing this will complete 1842 as well – but they are close enough that it could be closed.

**Comment by KathrynBaker** [comment] 2017-11-08 16:23
As 1842 is done, closing this as there is nothing else to capture from here

**Closed** 2017-11-08 16:23 UTC
