### ISSUE TITLE
Blockserver run control error

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1247] opened 2016-06-01 18:27 UTC
When starting the blockserver on LARMOR I see the following errors:

[Wed Jun  1 19:14:03 2016] CA exception in thread w/o CA ctx: status=User specified timeout on IO operation expired file=src/_ca314.cpp line=1612: 

[Wed Jun  1 19:14:03 2016] py_pend_ioUnable to find PV IN:LARMOR:CS:SB:SampleChi:RC:ENABLE
[Wed Jun  1 19:14:03 2016] INFO: Problem with setting runcontrol for SampleChi: Unable to find PV IN:LARMOR:CS:SB:SampleChi:RC:ENABLE
[Wed Jun  1 19:14:04 2016] CA exception in thread w/o CA ctx: status=User specified timeout on IO operation expired file=src/_ca314.cpp line=1612: 

[Wed Jun  1 19:14:04 2016] py_pend_ioUnable to find PV IN:LARMOR:CS:SB:SampleChi:RC:LOW
[Wed Jun  1 19:14:04 2016] INFO: Problem with setting runcontrol for SampleChi: Unable to find PV IN:LARMOR:CS:SB:SampleChi:RC:LOW
[Wed Jun  1 19:14:07 2016] CA exception in thread w/o CA ctx: status=User specified timeout on IO operation expired file=src/_ca314.cpp line=1612: 

[Wed Jun  1 19:14:07 2016] py_pend_ioUnable to find PV IN:LARMOR:CS:SB:XLoLim:RC:HIGH
[Wed Jun  1 19:14:07 2016] INFO: Problem with setting runcontrol for XLoLim: Unable to find PV IN:LARMOR:CS:SB:XLoLim:RC:HIGH

SampleChi is MOT:STACK:CHI:SP
XLoLim is   MOT:STACK:X:MTR.LLM 

I see that XLoLim points at a motor subfield which might be an issue, but so does XHiLim and that doesn't seem to generate an error.  The PVs seem to exist now, so maybe just a timeout needs increasing?

**Comment by John-Holt-Tessella** [comment] 2016-06-03 16:39
Try reproducing this on demo by restarting it

**Comment by John-Holt-Tessella** [comment] 2016-07-06 13:47
Could not reproduce.
Steps tried:

* 50+ blocks most disconnected
* Some motor blocks
* Chi block mentioned above
* Used configuration taken from larmor (larmor_base)

All with some items connected to run-control. Nothing seems to give me the same errors. This might be because I am working with a simulated Galil. 
Current plan, talk with Freddie then wait for LARMOR maintenance day to look.

**Comment by FreddieAkeroyd** [comment] 2016-07-06 18:20
The PVs concerned are created by the run control IOC, which is started by the blockserver. I didn't know whether after starting the run control IOC the blockserver wasn't allowing enough time for the PVs to "appear", but that was just a guess. Larmor had a lot of blocks so not waiting enough time made sense, but if it is showing OK in all your tests then maybe we have to leave it for now.

**Comment by AdrianPotter** [comment] 2016-07-21 09:15
Dormant for 2 weeks. Unable to reproduce. Moving to complete

**Closed** 2016-08-11 08:56 UTC
Labels: 3, bug, completed, fixed
