### ISSUE TITLE
SANS2D sample changer: auto-sync motor encoder position

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7105] opened 2022-03-28 10:25 UTC
As a scientist I would an axis to re-sync if an axis has drifted (I think this is encoder vs motor pulses?) past its drift tolerance - this is the `MTRXXXX_DRIFT_THRESHOLD_CHECK` PV 

### Acceptance Criteria
- [x] PV is set for resyncing the axis (height stage) 
- [x] Check that there is information about this on the WIKI and add if not. 

### Extra Information
SANS2D asked about this as their sample changer Y axis was moved physically, and it was confusing as to why it was never getting to position properly and prematurely hitting a soft limit. It was also driving in one direction which may be to do with a soft limit/ FL/BL number (which homing would solve) 

## How to Test
(**Add before making a PR**)_

**Comment by FreddieAkeroyd** [comment] 2022-03-28 21:42
Do we want to propagate the alert or just resync the motor/encoder positions? The term "drift" is probably not a good one, it suggests the axis may have lost accuracy which is not the case, what it really means is that the motor has lost steps getting to the correct position (as per encoder), which may indicate a known or unknown mechanical issue. I don't think rehoming will help the situation any better than just resyning motor/encoder steps automatically, all rehoming will do is force somebody to do something that reminds them there is a problem, but an automated alert would do the same and automating teh process would stop it not working in the middle of the night (how quickly does it drift - is that likely?)

**Comment by KathrynBaker** [comment] 2022-03-29 11:14
SANS2D were going to check, but I believe this has come out of not a natural drift, but a physical change on the encoder readback when the sample changer was put on (talking to the scientists it used to have the opposite problem under SECI and would drift when the sample changer was taken off).

**Comment by rerpha** [comment] 2022-03-29 12:14
yes, a user may put something heavy on it and it physically moved, but motor pulses stayed the same (while encoder pulses changed?)

**Comment by rerpha** [comment] 2022-03-29 13:03
resync would have to consider soft limits on that axis as they also couldn't move it upwards presumably because FL was hit prematurely

**Comment by FreddieAkeroyd** [comment] 2022-04-08 16:24
If FL was hit prematurely because the motor steps were of sync as opposed to the user soft limit being wrong WRT encoder readback, then an auto resync would fix that

**Comment by rerpha** [comment] 2022-04-21 09:49
notes on resyncing https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Galil#syncing-encoder-and-motor-steps

I might just email sarah and do this quickly

**Comment by rerpha** [comment] 2022-04-21 10:21
set on SANS2D, will test when i can

**Comment by rerpha** [comment] 2022-04-21 10:35
To review check that `IN:SANS2D:MOT:MTR0306_MOT_ENC_SYNC_TOL_SP` is not 0

**Comment by rerpha** [comment] 2022-04-21 16:15
we checked if this fixed it ~by jumping on the height stage~ with a heavy weight to see if the encoder steps change and they do - the resync seems to either occur before or after a move but soft limits can then be reached.

**Comment by JackEAllen** [comment] 2022-04-27 08:15
Marking this as complete as I can confirm that `IN:SANS2D:MOT:MTR0306_MOT_ENC_SYNC_TOL_SP` is set to 1 and not 0 on SANS2D.
Notes on Wiki about re-syncing also look good and are clear and concise about the issue.

**Closed by JackEAllen** 2022-04-27 08:15 UTC
Labels: 1, review, under review, no_release_notes
