### ISSUE TITLE
IOC: Eurotherm disaply error when out of calibration range

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3803] opened 2018-11-23 16:21 UTC
As an instrument scientist if my Eurotherm is using a calibration reading outside of my calibration curve I should get an error/message indicating this is the case. I must be allowed to continue taking readings though.

**Comment by Rory-Potter-Tessella** [comment] 2018-12-05 10:59
+1 VESUVIO from Instrument Demo (2018-11-22)

**Comment by Rory-Potter-Tessella** [comment] 2018-12-05 10:59
Is this a duplicate of #3770?

**Comment by John-Holt-Tessella** [comment] 2018-12-06 09:51
duplicate of #3770

**Comment by kjwoodsISIS** [comment] 2019-01-23 14:01
If this is fixed, it should be closed.

**Closed by kjwoodsISIS** 2019-01-23 14:01 UTC
Labels: duplicate, fixed
