### ISSUE TITLE
ZOOM: no longer creating putlogs

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3240] opened 2018-06-06 17:20 UTC
ZOOM is no longer logging channel access puts - it looks line this stopped yesterday lunchtime and coincides with the following in the ioclog server log

[Tue Jun  5 11:42:04 2018] IOC Client 127.0.0.1:52244 disconnected

[Tue Jun  5 11:42:23 2018] IOC Client 127.0.0.1:52260 connected

[Tue Jun  5 11:42:23 2018] [Fatal Error] :1:249: An invalid XML character (Unicode: 0x17) was found in the CDATA section.

[Tue Jun  5 11:42:23 2018] Could not parse XML formatted message.
[Tue Jun  5 11:42:23 2018] IOC Client 127.0.0.1:52260 disconnected
[Tue Jun  5 11:42:24 2018] Database error, error: 'Message Type "-" not recognised' Will retry.
[Tue Jun  5 11:42:25 2018] Database error, error: 'Message Type "-" not recognised' Will retry.
[Tue Jun  5 11:42:26 2018] Database error, error: 'Message Type "-" not recognised' Will retry.
[Tue Jun  5 11:42:27 2018] Database error, error: 'Message Type "-" not recognised' Will retry.
 
The final message continues to be repeated at regular intervals 

Added requirements: Reproduced locally by @aaron-long and @John-Holt-Tessella :

1. Start a new run to make putlog empty
1. Write the title `caput -S TE:NDLT1095:DAE:TITLE a`
1. Observe the putlog write
1. Run the log server writer:
    ```
    cd C:\Instrument\Apps\EPICS\ISIS\IocLogServer\master\dev-tools
    python ioc_message_simulator.py
    ```
1. Hold alt and on keypad type 0017 to produce the offending character
1. Write a new title
1. This does not appear in the put log

**Comment by KathrynBaker** [comment] 2018-12-18 14:39
This has happened again on ZOOM, whilst trying to figure out what went wrong for something else. The lack of these logs makes it harder to diagnose some types of support call. so this needs looking at and resolving. It may be a symptom of something else, or something else may be causing it, but these putlogs are very useful to some of us

**Comment by DominicOram** [comment] 2019-01-07 20:18
This also corresponded with the following on the BLOCKSVR logs:

> [Fri Dec  7 16:30:26 2018] [1544200226.57] MAJOR: Could not restart IOC ALARM: Could not get auto-restart property for IOC (IN:ZOOM:CS:PS:ALARM) got 'E'

The unicode characters here are not valid XML. I've modified inst_servers to ensure that it only gives valid XML at https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/183. I'm still investigating why procserver/alarmserver gave such an odd response in the first place.

**Comment by DominicOram** [comment] 2019-01-08 13:39
I got no further with the underlying problem other than the fact that getting the autorestart at this point is not required so I removed the unused code. ZOOM seems to be working fine now and I couldn't reproduce locally. Going to call this done as it will at least mitigate the problem if we see it in the future.

**Comment by DominicOram** [comment] 2019-01-25 16:53
Once fixed confirm that this will also fix https://github.com/ISISComputingGroup/IBEX/issues/2093 and close #2093 off.

**Comment by FreddieAkeroyd** [comment] 2019-01-26 20:00
@DominicOram Would it be possible for you to look at #2788 with your newly gained logserver knowledge?  The XML message format has an <eventTime> member and it looks like this is not being used by the log server to set the message time - in fact   ioc_message_simulator.py   doesn't even add such a field to its test messages.

**Comment by Kevin-Woods-Tessella** [comment] 2019-01-29 10:14
How many points was this?

**Closed** 2019-01-30 16:55 UTC
Labels: 1, bug, completed, for release, rework
