### ISSUE TITLE
OSIRIS: BE Filter movement

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4854] opened 2019-10-15 09:21 UTC
Instrument scientist called because they had attempted to drive the BE filter to its high position (131mm) but physically it was not at this position once the move had finished. Homing did not work.

It looks like it is most likely related to issue [#4392](https://github.com/ISISComputingGroup/IBEX/issues/4392)

The high limit was increased and the axis was driven to 136mm where the BE filter was in the correct physical location. Once completed the absolute position was set to 131mm and the high limit returned to 131.8mm

**Comment by aaron-long** [comment] 2019-10-15 09:27
@FreddieAkeroyd @John-Holt-Tessella @Tom-Willemsen @DominicOram @ChrisM-S 

Given the work completed in the related issue, and it's child issue, did we expect this to be fixed?

**Comment by Tom-Willemsen** [comment] 2019-10-15 16:56
No, but we expect to have a log of the encoder-motor difference so that we can tell when the drift occured (if it is the same issue as last time).

**Comment by DominicOram** [comment] 2019-10-15 18:40
> Homing did not work

We should chance this up, homing would have been the correct solution in this case. Do we not have a homing routine on the axis? Can we get access in shutdown to diagnose the issue?

**Comment by Tom-Willemsen** [comment] 2019-10-16 08:37
> Do we not have a homing routine on the axis?

That's correct. The relevant part of OSIRIS' `galil01.cmd` is:

```
## Homing routines removed at request of instrument scientist:

GalilStartController("Galil","$(GALIL)/gmc/galil_Default_Header.gmc;$(GALIL)/gmc/galil_Home_Dummy_Do_Nothing.gmc!$(GALIL)/gmc/galil_Home_Dummy_Do_Nothing.gmc!$(GALIL)/gmc/galil_Home_Dummy_Do_Nothing.gmc!$(GALIL)/gmc/galil_Home_Dummy_Do_Nothing.gmc!$(GALIL)/gmc/galil_Home_Dummy_Do_Nothing.gmc!$(GALIL)/gmc/galil_Home_Dummy_Do_Nothing.gmc!$(GALIL)/gmc/galil_Home_Dummy_Do_Nothing.gmc!$(GALIL)/gmc/galil_Home_Dummy_Do_Nothing.gmc;$(GALIL)/gmc/galil_Default_Footer.gmc",0,0,3)
```

**Comment by aaron-long** [comment] 2019-10-16 08:40
From speaking to David I believe they do not want the filter to move the full range of the axis. Does that imply that there's no home switch and instead it (previously) homed on limit switches? Maybe we need to have another discussion with them.

If it's a known axis that slips, surely we want something that will allow them to recover from these situations and mitigate the support call.

**Comment by aaron-long** [comment] 2019-10-16 09:29
That's what I would expect.

The IS manually moved it to that position and confirmed it was where they wanted it physically.

**Comment by John-Holt-Tessella** [comment] 2019-10-18 08:25
Did someone look at the difference between motor and encoder position? If not could someone do that. If the motor/encoder is slipping it should be reported to motion control I think because I believe that eventually the motor/encoder will fail and then they will not be able to use the axis at all potentially shutting down the beamline for repairs. Can someone good at motion confirm this please?

**Comment by Tom-Willemsen** [comment] 2019-10-18 09:18
Unfortunately the drift PV has not been archived on OSIRIS so we can't look back at it historically.

`SELECT * FROM archive.channel WHERE name LIKE "IN:OSIRIS:MOT:MTR01%";` does not contain the `MTRENC_DRIFT` pv. (this is slightly weird as it is marked as `info(archive, "VAL")` in the DB).

**Comment by aaron-long** [comment] 2019-10-21 09:24
After some discussion with @Tom-Willemsen & @John-Holt-Tessella 

You can query the pv `IN:OSIRIS:MOT:MTR010X_MTRENC_DRIFT` to confirm the record exists for each axis. But as Tom has see, the PV's have not been archived. In `EPICS\CSS\master\ArchiveEngine` you can run `python make_archive_xml.py --host ndxosiris` and see that the PV's are expected to be in the archive engine pv list. The believed issue is that the archive engine has started before the Galil IOC, which has been changed to have new archived values.

**Comment by davidkeymer** [comment] 2019-10-31 11:38
@aaron-long and I have confirmed that the new drift PVs _are_ now being archived.  Should the problem with the Beryllium Filter reoccur, then the drift information would be available for diagnostic purposes.  The intention was not to alert anyone to an increasing difference between motor and encoder, but this could be introduced via blocks/nagios should the need arise.

Ticket considered successfully reviewed.

**Comment by kjwoodsISIS** [comment] 2019-10-31 15:50
Points?

**Closed** 2019-11-07 08:42 UTC
Labels: 0.5, completed, fixed, support
