### ISSUE TITLE
GUI:Sort or filter IOC list

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1609] opened 2016-09-15 15:00 UTC
In the Start/Stop IOC dialog, it would be nice if there was a way of quickly see which IOCs are running without having to scroll down the table, e.g. by being able to sort the IOCs by status or have a filter on the status

**Comment by DominicOram** [comment] 2018-04-25 16:25
Closing as a duplicate of #1320

**Closed by DominicOram** 2018-04-25 16:25 UTC
