### ISSUE TITLE
Install Script: Install from Release Directory

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1637] opened 2016-09-20 14:52 UTC
The current IBEX Client & genie_python installation script, `install_client.bat`, does not appear to correctly install genie_python if the script is run from any location other than
`\\inst$\Kits$\CompGroup\ICP\Client\BUILDnnn`, where `nnn` is the build number.

The current user manual instructs the user to install the IBEX Client & genie_python from `\\isis\inst$\Kits$\CompGroup\ICP\Releases\N.M.O\Client\BUILDnnn`.  While the installation of the IBEX Client works correctly (i.e. it does not care where the `install_client.bat` is run from), the installation of genie_python appears to fail.

It may be possible to "fix" this issue either by modifying `install_client.bat` or by modifying the directory structure in the `\\isis\inst$\Kits$\CompGroup\ICP\Releases` directory to match the structure that `install_client.bat` expects.

**Comment by ChrisM-S** [comment] 2016-09-20 16:25
Hi Kevin,

Yes, it looks like it is also trying to install from a folder called “genie_python” instead of the folder which is actually there called “genie_python_release”.  It could be modified to look for this at a higher level, but it seems that it would be better if the compatible release of “genie_python” with the 2.1.0 tree was held within the 2.1.0 tree or there would be no way of re-tracing the installation version combination later on?  I’ve put a “fixed” copy of “install_client –v2 works for me” in there temporarily for testing.

For user or Facilities IT installations of a client (depending on desktop privileges and inclination of the user or visitor), it is usually easiest to simply point them at a URI to get them into the right folder and then ask them to double click on the installer “install_client.bat”.  There might  be some confusion caused by the presence of what clearly looks like an installer the
“ClientInstaller.exe” but which doesn’t quite work.  but something like


                The most recent client can be installed from

                                \\isis.cclrc.ac.uk\inst$\Kits$\CompGroup\ICP\Releases<file:///\\isis.cclrc.ac.uk\inst$\Kits$\CompGroup\ICP\Releases>

      (you may need to enter your federal id and password for access to this share).

Choose the highest numbered release and drill down to the BUILDnnn folder, double click on “install_client.bat” and wait until you see “Pause…” at this point the installation is complete.

Finally, you may wish to create a link to IBEX in the start menu.  Browse to “C:\Instrument\Apps\Client” and right click on “ibex-client.exe”, select “Pin to Taskbar” and/or “Pin to Start Menu” (see below)

[cid:image001.png@01D21361.0E0E9D80]


If your browser does not support links, copy and paste the above paths into the address bar of an explorer window.

Having tried this, it seems you do not need to create any folders before running the script as it makes them all anyway!

The comment about the FTP server was slightly premature as the install is still requiring access to a full file tree over the network.  The security and share paths above are unnecessarily complex as a result and if the “ClientInstaller.exe” was fully functional (it seems to be almost working to me) the obvious place to put it would be somewhere like

                ftp://ftp.nd.rl.ac.uk/scratch/IBEX

then there is no fiddling with security and the version in the folder can simply be labelled appropriately, e.g. ClientInstaller-2.1.0.exe etc.  People on and off site (i.e. not needing the VPN) can get at the FTP site without any need for domain authentication which is generally a lot easier for users with laptops (and also collaborators).

For me there are still some client issues after installation, but at least I can now build an automated installation of the client (once the file/path locations have settled down and are finally decided!).

Chris

**Comment by AdrianPotter** [comment] 2016-09-29 07:53
Note that this issue is partially covered by ticket #1586

**Comment by AdrianPotter** [comment] 2016-10-07 14:44
I've updated the build and documentation as of ticket #1586 and applied the install fixes retroactively to the previous versions which will now install as described in the user manual.

**Comment by mattclarke** [comment] 2016-10-27 15:09
Closed as part of reviewing #1586.

**Closed by mattclarke** 2016-10-27 15:09 UTC
Labels: bug, review, under review
