### ISSUE TITLE
IOC Beckhoff does not move less than 1 EGU

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3246] opened 2018-06-08 13:07 UTC
The beckhoff 4.3.1 IOC with the 4.4.0 release for everything else do not let the Beckhoff move less than 1 mm.

Reproduce:

1. Go to 0
1. Move to 0.5
1. Axis does not move

careful becaise

1. Goto -1
1. Goto 0.5
1. Axis *does* move

Acceptance Criteria

Above cases should both do move.

**Comment by John-Holt-Tessella** [comment] 2018-06-08 13:08
Discovered during #3245

**Comment by FreddieAkeroyd** [comment] 2018-06-10 16:05
What does

1. Goto 0
2. Request move to -0.6
3. Request move to  0.5

Do? It will not move in 2, but does it move in 3? The request is > 1 but the actual move distance is < 1

**Comment by FreddieAkeroyd** [comment] 2018-07-09 08:59
I have looked into this and can fix it in the simple case but there are potentially wider issues. The initial problem is setting “too_small” in doDVALchangedOrNOTdoneMoving() which is checking you should not move less than the retry deadband, and the retry deadband must be at least one motor pulse. So we are asking for a move of less than the resolution we have claimed, which has knock on effects for retry etc. If we allow moves of less than the resolution, what do we mean by “the resolution”? This question may best be passed back to the writer of the axis record for comment. However I now wonder if it is better to instead use the original motor record with a nominal (or real beckhoff) resolution? As well as solving #3246 this should also solve #3248 and #3181 at the same time and I think using a nominal resolution greater than the gravity correction variation will solve #3247 too.

**Comment by FreddieAkeroyd** [comment] 2018-07-09 17:11
Simulator available in #3162

**Comment by Rory-Potter-Tessella** [comment] 2018-07-10 15:19
The simulator works on Windows and the Beckhoff motor talks to it successfully.

However, it goes into an error status when you try to get a motor to move because the maximum velocity is set to 0. This may be caused by the axisRecord as it is unclear from the simulator code why the max velocity is 0.

On 2018-07-12, Freddie and I are planning to change the Beckhoff motor back to a motorRecord and implement the changes Freddie has suggested above. We can then test against the simulator to see if the problems still happen.

**Comment by FreddieAkeroyd** [comment] 2018-07-20 16:49
Merged code as needed for testing on IMAT on Monday

**Comment by John-Holt-Tessella** [comment] 2018-07-23 16:02
Looks good, I will assume if you find issues on the instrument you will create a new ticket

**Closed** 2018-08-02 09:03 UTC
Labels: 2, bug, completed, fixed
