### ISSUE TITLE
CHIPIR: IOC & OPI for Tektronix DMM 4050 Multimeter

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6212] opened 2021-02-10 17:50 UTC
As a CHIPIR scientist I want to be able to control a Tektronix DMM 4050 Multimeter in my experiments.

#### Acceptance Criteria
1. Using the IBEX client, I can control a Tektronix DMM 4050 Multimeter
1. Using genie_python, I can control a Tektronix DMM 4050 Multimeter

#### Notes
1. Check the [CHIPIR Instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/CHIPIR-Instrument-Details).
1. The manufacturer's web-site describes the [Tektronix DMM4050 and DMM4040 Digital Multimeters](https://uk.tek.com/datasheet/dmm4050-4040-digital-multimeter).
1. A copy of the Tektronix DMM 40x0 Multimeter manual is located here: `\\isis\shares\ISIS_Experiment_Controls\Manuals\Tektronix__DMM40x0_Digital_Multimeter`.
1. The IOC & OPI must offer functionality equivalent to the existing VI (located here: `C:\LabVIEW Modules\Drivers\Tektronix DMM 4050`).
1. We already have an IOC (albeit an old IOC) for the Tektronix DMM 4050 (see #121).

**Comment by rerpha** [comment] 2024-05-07 15:46
duplicate of #6211

**Closed by rerpha** 2024-05-07 15:46 UTC
