### ISSUE TITLE
SUPPORT: ISISDAE IOC Stopped updating dashbaord in GUI

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4430] opened 2019-06-17 12:58 UTC
See on LARMOR:

- Dashboard stopped updating with run number, good frames etc
- user could still begin end worked (from scripting)
- killing the GUI did nothing
- killing issidae IOC  made it work again

looks like the IOC is producing no logs for this time either, (even begin and end entries).

Restarted at 2019-06-15 16:04:49.

**Comment by FreddieAkeroyd** [comment] 2019-06-19 16:56
The only pathway I can see here is if the ISISDAE thinks it is in a transition state (e.g. ENDING, PAUSING) then it doesn't bother updating dashboard values. The fact that begins and ends worked indicate it is not a locking issue. I'm not sure how it would get stuck in thinking it was in a "transition state" as this is updated when a begin/end etc. is done.  It might be that improvements to the code in #4365 will stop this happening

**Comment by FreddieAkeroyd** [comment] 2019-08-12 15:56
Will assume it is a duplicate of #4365 unless it reoccurs

**Closed by FreddieAkeroyd** 2019-08-12 15:56 UTC
Labels: support
