### ISSUE TITLE
GUI: Duplicate block name in components causes client failure

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1884] opened 2016-12-05 12:00 UTC
Issue raised for Rob on Larmor. Let him know when it's fixed.

When triggered, the issue causes the GUI to become partially unresponsive:

- Unable to load configs
- Blocks disappear from dashboard
- Current configuration goes 'Unknown'

The issue arose when Rob added in a new component.

- The component contained a block 'm6trans'
- The component version of 'm6trans' was in a  group `GMWMagnet`
- The configuration contained another component 'Polariser' containing a block 'M6trans' (case may or may not be important)
- The 2nd block was in another group `Polariser`

My suspicion is that having 2 blocks with the same case-invariant names in 2 different groups causes the problem. Removing the 1st block from the GMW component solved the issue.

The client should handle duplicate block names better when they exist in different components.

**Comment by kjwoodsISIS** [comment] 2016-12-06 09:09
What should that "better handling" be?
Presumably the system should:
1. warn the user that he is attempting to load a component which duplicates an existing Block name
1. decline to load the component (to prevent the GUI from becoming unresponsive, etc.) or give the user the chance to correct the duplicate name.

Is there an existing check to make sure that the user does not create Blocks with duplicate names?

If we decline to load the component containing the Block with duplicate name, how would the user correct duplicate name?  Presumably they would have to load the offending component via another configuration, make the correction, save it, and then re-load the first configuration.  Some users might find that very irritating (although there might not be any other way).

**Comment by ThomasLohnert** [comment] 2017-03-07 15:04
https://github.com/ISISComputingGroup/ibex_gui/pull/462

**Comment by DominicOram** [comment] 2017-03-14 17:05
Note that case is actually very important in reproducing this error. If you have two blocks with the same name but different case then the blockserver will list them both under the groups but only give details on one. This was causing the GUI to get confused.

**Comment by ThomasLohnert** [comment] 2017-04-04 16:19
PR for properly updating component monitors in the Blockserver: 
https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/118
System Tests:
 https://github.com/ISISComputingGroup/ibex_system_tests/pull/42

**Comment by Tom-Willemsen** [comment] 2017-04-05 13:14
I've reviewed and merged this, but not moving into review_complete yet because we have sprint demo this afternoon. 

Can be moved once sprint demo is over.

**Closed** 2017-05-04 08:03 UTC
Labels: 1, bug, completed, fixed, rework
