### ISSUE TITLE
MERLIN: Migrate to IBEX

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2354] opened 2017-05-23 12:51 UTC
As an instrument scientist, I would like to migrate MERLIN to use the IBEX instrument control system.

#### Acceptance Criteria
1. IBEX is installed on MERLIN
1. Configuration files matching the current SECI config files are created
1. IBEX is configured for the devices on MERLIN.
1. MERLIN scripts are converted to genie_python
1. MERLIN scientists are trained in how to use IBEX
1. IBEX is tested on MERLIN

#### Notes
1. The devices on MERLIN are listed on the [MERLIN Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/MERLIN-Instrument-Details) list
1. The following tickets should be implemented prior to deploying IBEX on MERLIN
   - [x] #2347
   - [x] #2355
   - [x] #2357
   - [x] #2358
   - [x] #2360 
   - [x] #2361
   - [x] #2362
   - [ ] <del>#2507</del>
   - [x] #2529
1. Use the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page to guide you through the migration process. The following activities need to be completed as part of the migration process:
   - [x] Ask Facilities IT (Anthony Shuttle) to create a private network for MERLIN.  This is required so that we can use TCP/IP to communicate with the Galils. Facilities IT will need notice of about 4-6 weeks.
      - 27/07/2017: Confirmed by Anthony; scheduled to happen mid-August.
   - [x] Check that NDXMERLIN has sufficient disk space to install IBEX
      - C: drive - Total: 126.00 GB, Free: 89.9 GB on 26/07/2017.
      - Fresh install of IBEX requires 16.0GB + 20GB growth room.  89.9GB free is sufficient space.
   - [x] Check whether MERLIN uses 5- or 8- digit run-numbers
      - [ ] MERLIN uses 5-digit run-numbers; upgrade the ICP program (to permit 8-digit run-numbers)
   - [ ] Create a virtual instrument for testing purposes
      - [ ] Set up a test system, say, NDXMERLINTEST.
      - [ ] create IBEX configurations to correspond to their SECI equivalents
      - [ ] create genie-python scripts to correspond to their Open-Genie equivalents
      - [ ] test these configurations & scripts
      - [ ] check that all the devices previously supported by SECI (on MERLIN) are supported by IBEX
   - [ ] arrange one or more training sessions with the scientists to help them understand how to use IBEX
      - [ ] demonstrate the configurations & scripts (created above) to the instrument scientists and check that they are happy with the migrated configurations & scripts

**Comment by kjwoodsISIS** [comment] 2017-07-26 13:49
On 26/07/2017 MERLIN had the following local disk space:

- C: 89.9 GB free out of 126 GB
- T: 93.0 GB free out of 126 GB
- P: 5.54 GB free out of 19.9 GB

**Comment by AdrianPotter** [comment] 2017-08-07 12:53
The current McLennan driver was tested using a model PM304. As far as I know, the McLennans encountered on other machines have been the same model. The driver does theoretically support the PM600 that's on MERLIN, and without any different setup on our part, but I don't know whether it's ever been tested.

**Comment by kjwoodsISIS** [comment] 2017-08-07 12:56
@AdrianPotter : in that case, I think we ought to test the McLennan driver on MERLIN asap.

**Comment by AdrianPotter** [comment] 2017-08-08 13:41
Having discussed with David, my previous assertion was wrong. We've used lots of PM600s before, and is in fact most common, so this shouldn't be an issue

**Comment by AdrianPotter** [comment] 2017-08-08 13:49
The basic migration has been completed. There are a number of outstanding issues I'm working on:

- [ ] The Nim Chopper in the original config is read only. David has talked with Helen and they'd like the same applied in Ibex. I need to add Manager Mode support to the MK2 chopper to make this work.
- [ ]I haven't migrated the function `header` from their scripting file. It extracts run data from RAW data files so is better handled with Mantid. David is confirming that's fine with the instrument scientist.
- [ ] There is a bit of code in the scripts that calls an old FORTRAN executable to calculate and set the tcb file parameters. That'd be better handled using Python, but the source code for the existing program isn't kept alongside the executable. David is trying to find out if the source code is available.
- [ ] Set the Fermi chopper macros. The config.xml was missing from the original Fermi chopper ticket (I'm not sure how that got through review) so no macros can be set. Tom has updated the build but I need to wait until a new version is available from Jenkins before I can update them on NDXTEST2. The macros are:
    - Baud: 57600
    - Bits: 8
    - Parity: 0 
    - Stop: 1
    - Com: 8
- [ ] We need to check the Galil on Merlin can connect via ethernet since EPICS doesn't support serial axis. I think it should be fine since there is an IP address listed in the Jaws configuration file but we should double check.

**Comment by kjwoodsISIS** [comment] 2017-08-08 14:00
@AdrianPotter:
1. The network on MERLIN is being re-configured as a private network in anticipation of the communications with Galils being done over TCP/IP.
1. The phrase "old FORTRAN executable" screams risk at me ;-).  We should discuss this with the scientists, to discover how well they understand the original source code.

**Comment by AdrianPotter** [comment] 2017-08-08 14:05
1. Ah yes, I see now you've already discussed that in an earlier comment, thanks. I'll tick it off the list.

2. I've confirmed that it can be executed without issue from Python script, so the behaviour should be unchanged from Open Genie. I completely agree though, it's a 3rd party component that we should do our best to either understand or better yet, eliminate. The executable seems hard coded to write to a location in LabView Modules so it will stop working once SECI is no longer used (unless we put in a nasty Python hack to trick it).

**Comment by AdrianPotter** [comment] 2017-08-08 14:07
Impeded awaiting:

- [ ] Answers from @davidkeymer (2nd and 4th points above)
- [ ] A successful Jenkins build
- [ ] Ticket #2529

**Comment by AdrianPotter** [comment] 2017-08-08 14:32
Ticket #2529 was a duplicate of #2361 which is already complete, although one of the controls hadn't had manager mode applied. I've submitted a patch and am awaiting an updated Jenkins build

**Comment by kjwoodsISIS** [comment] 2017-09-04 12:58
@AdrianPotter : now that we can call the old FORTRAN executable (that sets the tcb parameters) from genie_python, this ticket should no longer be impeded.   Of course, we still want to track down the original FORTRAN source code, but that can happen independently of this ticket.

**Comment by AdrianPotter** [comment] 2017-09-04 14:13
Yes. Still no word from Toby

**Closed** 2017-09-21 10:37 UTC
Labels: 5, completed, fixed
